import {useState} from 'react';
import API from '../../data/api.js';
import useApi from '../../hooks/useApi.js';
import {useToast} from '../../context/ToastContext.jsx';
import {useLanguage} from '../../context/LanguageContext.jsx';
import Icon from '../../components/Icon.jsx';
import {Alert,ApiState,Badge,Button,Card,EmptyState,Field,PageHead,PasswordInput,Stats,Table,useConfirm} from '../../components/ui/index.jsx';
import {fmtDate} from '../../lib/format.js';
export default function Security(){
  const {t}=useLanguage(),toast=useToast(),confirm=useConfirm(),[password,setPassword]=useState(''),[code,setCode]=useState(''),[setup,setSetup]=useState(null),[codes,setCodes]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const data=useApi(async()=>{const [summary,devices,sessions,activity]=await Promise.all([API.security('GET',''),API.security('GET','/devices'),API.security('GET','/sessions'),API.security('GET','/activity')]);return {summary,devices,sessions,activity};},[]);
  async function action(method,path,body,done){setBusy(true);setError('');try{const r=await API.security(method,path,body);done?.(r);toast(t('Security settings updated.'));}catch(e){setError(e.message);}finally{setBusy(false);}}
  const auth={password,code},d=data.data;
  return <>
    <PageHead eyebrow={t('Account')} title={t('Security')} lead={t('Protect your account and review who has access.')}/>
    {error&&<div className="mb-5"><Alert type="danger">{error}</Alert></div>}
    <ApiState state={data}>{d&&<>
      <Stats items={[{label:t('Multi-factor authentication'),value:t(d.summary.mfa_enabled?'On':'Off'),icon:'key',tone:d.summary.mfa_enabled?'ok':'warn'},{label:t('Unused recovery codes'),value:d.summary.recovery_codes_remaining??0,icon:'list'},{label:t('Active sessions'),value:d.sessions.length,icon:'globe'},{label:t('Trusted devices'),value:d.devices.filter(x=>x.trusted).length,icon:'smartphone',tone:'info'}]}/>
      <div className="security-grid">
        <Card title={t('Confirm your identity')} subtitle={t('Sensitive actions require a recent password confirmation and an authenticator code when MFA is enabled.')}><form onSubmit={e=>{e.preventDefault();action('POST','/reauthenticate',auth,()=>{setPassword('');setCode('');});}}><PasswordInput label={t('Current password')} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/><Field label={t('Authenticator or recovery code')} value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code" hint={t('Required only when MFA is enabled. Use a fresh code for each sensitive action.')}/><Button busy={busy} type="submit" icon="lock">{t('Confirm password')}</Button></form></Card>
        <Card title={t('Multi-factor authentication')} actions={<Badge status={d.summary.mfa_enabled?'ENABLED':'NOT_ENABLED'}/>}>
          <p className="mb-4">{t('Use a standard authenticator app. Recovery codes can be used once if you lose access to your authenticator.')}</p>
          {setup?<><img className="setup-qr" src={setup.qr} alt={t('Authenticator setup QR code')}/><Field label={t('Manual setup key')} value={setup.secret} readOnly className="mono"/><Field label={t('Code from your authenticator')} className="code-field" value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code" inputMode="numeric"/><div className="page-actions"><Button busy={busy} icon="check" onClick={()=>action('POST','/mfa/activate',{code},r=>{setCodes(r.recovery_codes);setSetup(null);setCode('');})}>{t('Activate MFA')}</Button><Button variant="outline" onClick={()=>setSetup(null)}>{t('Cancel')}</Button></div></>
          :<div className="page-actions"><Button busy={busy} icon="key" onClick={()=>action('POST','/mfa/enroll',{},setSetup)}>{t(d.summary.mfa_enabled?'Replace authenticator':'Set up MFA')}</Button>{d.summary.mfa_enabled&&<><Button variant="outline" busy={busy} icon="refresh" onClick={()=>action('POST','/mfa/recovery-codes',auth,r=>setCodes(r.recovery_codes))}>{t('Regenerate recovery codes')}</Button><Button variant="danger" busy={busy} onClick={async()=>{if(await confirm({title:t('Disable MFA?'),message:t('Enter your current password and a fresh MFA code in the confirmation fields before continuing.'),confirmLabel:t('Disable MFA'),danger:true}))action('POST','/mfa/disable',auth);}}>{t('Disable MFA')}</Button></>}</div>}
          {codes&&<div className="recovery-codes mt-5"><h3>{t('Save these codes now')}</h3><p>{t('Each code works once. They will not be displayed again.')}</p><pre>{codes.join('\n')}</pre><Button variant="outline" icon="download" onClick={()=>{const blob=new Blob([codes.join('\n')],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='amap-recovery-codes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{t('Download codes')}</Button><Button icon="check" onClick={()=>setCodes(null)}>{t('I saved my codes')}</Button></div>}
        </Card>
      </div>
      <Card title={t('Trusted devices')} subtitle={t('Trusted devices lower the assurance needed for recovery on this browser.')} actions={<Button variant="outline" className="btn-sm" busy={busy} icon="smartphone" onClick={()=>action('POST','/devices/current/trust',{})}>{t('Trust this device')}</Button>} flush><Table rows={d.devices} caption={t('Trusted devices')} empty={<EmptyState icon="smartphone" title={t('No devices yet')} message={t('Devices appear after you sign in from them.')}/>} columns={[{key:'browser',label:t('Browser'),render:r=><span className="flex items-center gap-2"><Icon name="globe" size={16}/>{r.browser}{r.current&&<Badge status="ACTIVE">{t('Current')}</Badge>}</span>},{key:'last_seen',label:t('Last seen'),render:r=>fmtDate(r.last_seen,true)},{key:'trusted',label:t('Trust'),render:r=>t(r.trusted?'Trusted':'Not trusted')},{key:'action',label:t('Action'),action:true,render:r=><Button variant="outline" className="btn-sm" busy={busy} onClick={()=>action('DELETE','/devices/'+r.id)}>{t('Revoke device')}</Button>}]}/></Card>
      <Card className="mt-6" title={t('Active sessions')} actions={<Button variant="outline" className="btn-sm" busy={busy} icon="logout" onClick={()=>action('DELETE','/sessions/others')}>{t('Sign out other sessions')}</Button>} flush><Table rows={d.sessions} caption={t('Active sessions')} columns={[{key:'browser',label:t('Device'),render:r=><span className="flex items-center gap-2">{r.browser||t('Browser session')}{r.current&&<Badge status="ACTIVE">{t('This session')}</Badge>}</span>},{key:'created_at',label:t('Signed in'),render:r=>fmtDate(r.created_at,true)},{key:'expires_at',label:t('Expires'),render:r=>fmtDate(r.expires_at,true)},{key:'action',label:t('Action'),action:true,render:r=><Button variant="outline" className="btn-sm" busy={busy} onClick={()=>action('DELETE','/sessions/'+r.id)}>{t(r.current?'Sign out this session':'Revoke session')}</Button>}]}/></Card>
      <Card className="mt-6" title={t('Login and security activity')} subtitle={t('Report anything you do not recognise; linked sessions are revoked immediately.')} flush><Table rows={d.activity} caption={t('Security activity')} columns={[{key:'created_at',label:t('When'),render:r=>fmtDate(r.created_at,true)},{key:'event',label:t('Event'),render:r=>r.event.replaceAll('_',' ').toLowerCase().replace(/^\w/,c=>c.toUpperCase())},{key:'outcome',label:t('Result'),render:r=><Badge status={r.outcome==='SUCCESS'?'ACTIVE':r.outcome==='FAILURE'||r.outcome==='BLOCKED'?'REJECTED':'OPEN'}>{String(r.outcome).toLowerCase()}</Badge>},{key:'region',label:t('Approximate location'),render:r=>[r.region,r.country].filter(Boolean).join(', ')||t('Unavailable')},{key:'browser',label:t('Browser'),render:r=>r.browser||'—'},{key:'action',label:t('Action'),action:true,render:r=>r.event==='LOGIN_SUCCESS'?<Button variant="ghost" className="btn-sm" busy={busy} onClick={async()=>{if(await confirm({title:t('Report this sign-in?'),message:t('Associated sessions will be revoked and a security event recorded.'),confirmLabel:t('This was not me'),danger:true}))action('POST','/activity/'+r.id+'/report',{});}}>{t('This was not me')}</Button>:null}]}/></Card>
    </>}</ApiState>
  </>;
}
