/* Reproducible PRNG; the time anchor is stored with the dataset, never recomputed on reload. */
(function(){
  'use strict';
  function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
  const DOCUMENT_TYPES=['Identity proof','Address proof','Photograph','Income proof','Property document','Educational certificate','Medical certificate','Business registration'];
  function generate(anchor=new Date().toISOString()){
    const random=mulberry32(13022026),pick=a=>a[Math.floor(random()*a.length)],days=86400000,now=new Date(anchor).getTime();
    const db={version:1,anchor,departments:[],services:[],users:[],applications:[],documents:[],status_logs:[],grievances:[],notifications:[],preferences:{theme:'system'}};
    const specs=[['Revenue & Certificates','REV','certificate','Certificates and records for every milestone.',['Income Certificate','Residence Certificate','Birth Certificate','Caste Certificate']],['Municipal Services','MUN','building','Better neighborhoods, thoughtfully managed.',['Building Permit','Property Tax Assessment','Trade License']],['Transport','TRN','transport','Keeping people and communities moving.',['Driving License','Vehicle Registration','Parking Permit']],['Health & Welfare','HLT','health','Accessible care and support for everyone.',['Health Card','Disability Certificate','Senior Citizen Card']],['Education','EDU','education','Opportunity through education and learning.',['Scholarship Application','Student Pass','Qualification Verification']],['Water & Utilities','WTR','water','Reliable connections for everyday essentials.',['Water Connection','Sewerage Connection','Utility Subsidy']],['Environment','ENV','leaf','A cleaner, greener shared future.',['Environmental Clearance','Tree Removal Permit','Waste Collection License']],['Business & Labour','BUS','briefcase','Helping enterprise and livelihoods thrive.',['Shop Establishment License','Labour Registration','Business Renewal']]];
    specs.forEach((s,i)=>{db.departments.push({id:i+1,name:s[0],code:s[1],icon:s[2],description:s[3],active:true,created_at:new Date(now-400*days).toISOString()});s[4].forEach((name,j)=>db.services.push({id:db.services.length+1,department_id:i+1,name,description:'Apply online for '+name.toLowerCase()+'. Your department will verify the submitted details and keep you informed at every step.',fee:[0,50,100,250,500,1000][(i+j)%6],sla_days:[7,10,14,21,30][(i+j)%5],required_documents:j===0?['Identity proof','Address proof']:j===1?['Identity proof','Photograph']:['Identity proof'],active:true}));});
    const first=['Aarav','Ananya','Ishaan','Priya','Rohan','Meera','Arjun','Kavya','Aditya','Sana','Vikram','Neha','Rahul','Diya','Kiran','Aditi','Sanjay','Nisha','Varun','Pooja'],last=['Sharma','Reddy','Patel','Rao','Singh','Verma','Nair','Das','Gupta','Kumar'];
    function user(name,email,role,department_id,password){const id=db.users.length+1;db.users.push({id,name,email,role,department_id,password,phone:'98'+String(10000000+id*12345),address:id+' Lakeview Road, Hyderabad',active:true,created_at:new Date(now-(300-id)*days).toISOString()});return id;}
    user('Aarav Sharma','citizen@demo.gov','citizen',null,'citizen123');user('Priya Reddy','officer@demo.gov','officer',1,'officer123');user('Dhruv Kumar','admin@demo.gov','admin',null,'admin123');
    for(let d=1;d<=8;d++)for(let j=0;j<2;j++)user(pick(first)+' '+pick(last),'officer'+d+j+'@demo.gov','officer',d,'officer123');
    for(let i=0;i<31;i++)user(pick(first)+' '+pick(last),'citizen'+(i+1)+'@demo.gov','citizen',null,'citizen123');
    const citizens=db.users.filter(u=>u.role==='citizen'),iso=t=>new Date(t).toISOString();
    function log(a,from,to,at,actor,remarks){const l={id:db.status_logs.length+1,application_id:a.id,actor_id:actor,from_status:from,to_status:to,remarks,created_at:iso(at)};db.status_logs.push(l);db.notifications.push({id:db.notifications.length+1,user_id:a.citizen_id,application_id:a.id,title:a.reference+' · '+to.toLowerCase().replace(/_/g,' '),message:remarks,read:at<now-8*days,created_at:iso(at)});}
    let ordinal=0;
    for(let month=11;month>=0;month--){const count=13+(11-month)*4;for(let n=0;n<count;n++){
      ordinal++;const age=month*30+Math.floor(random()*28)+(month===0?0:2);const created=now-age*days-Math.floor(random()*9)*3600000;
      let service=pick(db.services);const citizen=ordinal%7===0||n===0?db.users[0]:pick(citizens);if(citizen.id===1&&ordinal%2===0)service=pick(db.services.filter(s=>s.department_id===1));
      const department_id=service.department_id,officer=pick(db.users.filter(u=>u.role==='officer'&&u.department_id===department_id));
      const roll=random();let status=age>55?(roll<.72?'APPROVED':roll<.89?'REJECTED':roll<.96?'WITHDRAWN':'UNDER_REVIEW'):(roll<.26?'APPROVED':roll<.33?'REJECTED':roll<.39?'WITHDRAWN':roll<.62?'UNDER_REVIEW':roll<.78?'SUBMITTED':roll<.91?'NEEDS_INFO':'FORWARDED');
      if(age===0)status='SUBMITTED';
      const a={id:ordinal,reference:'GOV-'+new Date(created).getUTCFullYear()+'-'+String(ordinal).padStart(6,'0'),citizen_id:citizen.id,service_id:service.id,department_id,officer_id:status==='SUBMITTED'?null:officer.id,status,priority:pick(['normal','normal','normal','high','urgent']),form_data:{full_name:citizen.name,email:citizen.email,phone:citizen.phone,address:citizen.address,purpose:'Requesting '+service.name.toLowerCase()+' for personal and official records.'},fee:service.fee,sla_days:service.sla_days,created_at:iso(created),updated_at:iso(created),decided_at:null};
      db.applications.push(a);log(a,null,'SUBMITTED',created,citizen.id,'Application submitted with the required supporting documents.');
      const reviewAt=Math.min(created+(1+random()*2)*days,now-3600000),endAt=Math.min(created+(3+random()*service.sla_days*1.5)*days,now-1800000);
      if(status==='WITHDRAWN'){log(a,'SUBMITTED','WITHDRAWN',endAt,citizen.id,'The applicant withdrew this request as it is no longer required.');a.decided_at=iso(endAt);a.officer_id=null;}
      else if(status!=='SUBMITTED'){
        log(a,'SUBMITTED','UNDER_REVIEW',reviewAt,officer.id,'Application assigned and document verification started.');
        if(status==='APPROVED'&&ordinal%5===0){const infoAt=reviewAt+(endAt-reviewAt)*.3,responseAt=reviewAt+(endAt-reviewAt)*.6;log(a,'UNDER_REVIEW','NEEDS_INFO',infoAt,officer.id,'Please provide a clearer copy of your identity document.');log(a,'NEEDS_INFO','UNDER_REVIEW',responseAt,citizen.id,'A clear replacement document has been provided for verification.');}
        if(status!=='UNDER_REVIEW'){log(a,'UNDER_REVIEW',status,endAt,officer.id,({APPROVED:'All submitted records have been verified. The application meets the service requirements.',REJECTED:'The submitted supporting records do not meet eligibility requirements for this service.',NEEDS_INFO:'Please provide a recent address proof so that verification can continue.',FORWARDED:'Forwarded to the specialist desk in this department for additional verification.'})[status]);if(['APPROVED','REJECTED'].includes(status))a.decided_at=iso(endAt);}
      }
      a.updated_at=db.status_logs[db.status_logs.length-1].created_at;
      service.required_documents.forEach(label=>{const text='CIVIC DESK DEMO DOCUMENT\n'+label+'\nReference: '+a.reference+'\nThis is a synthetic supporting document for the college capstone.';db.documents.push({id:db.documents.length+1,application_id:a.id,label,name:label.toLowerCase().replace(/ /g,'-')+'.txt',mime:'text/plain',size:text.length,content:'data:text/plain;base64,'+btoa(text),created_at:a.created_at});});
    }}
    // Guarantee a useful fresh portfolio for the three fixed demo accounts.
    const lastApps=db.applications.slice(-10);lastApps.forEach((a,i)=>{a.citizen_id=1;const s=db.services[i%4];a.service_id=s.id;a.department_id=1;a.fee=s.fee;a.sla_days=s.sla_days;a.officer_id=a.status==='SUBMITTED'?null:2;a.form_data={...a.form_data,full_name:db.users[0].name,email:db.users[0].email,phone:db.users[0].phone,address:db.users[0].address,purpose:'Requesting '+s.name.toLowerCase()+' for personal records.'};db.notifications.filter(n=>n.application_id===a.id).forEach(n=>n.user_id=1);db.status_logs.filter(l=>l.application_id===a.id).forEach(l=>l.actor_id=l.from_status===null||l.to_status==='WITHDRAWN'||l.from_status==='NEEDS_INFO'?1:2);db.documents=db.documents.filter(d=>d.application_id!==a.id);s.required_documents.forEach(label=>{const text='Demo '+label+' for '+a.reference;db.documents.push({id:Math.max(0,...db.documents.map(d=>d.id))+1,application_id:a.id,label,name:label.replace(/ /g,'-')+'.txt',mime:'text/plain',size:text.length,content:'data:text/plain;base64,'+btoa(text),created_at:a.created_at});});});
    for(let i=0;i<42;i++){const a=i<8?pick(db.applications.filter(a=>a.citizen_id===1)):pick(db.applications);const created=Math.max(new Date(a.created_at).getTime()+days,now-(1+Math.floor(random()*50))*days);const status=i%4===0?'OPEN':i%4===1?'IN_PROGRESS':'RESOLVED';db.grievances.push({id:i+1,reference:'GRV-'+String(i+1).padStart(5,'0'),application_id:a.id,service_id:a.service_id,citizen_id:a.citizen_id,department_id:a.department_id,subject:pick(['Request for an update','Clarification about documents','Service timeline exceeded','Correction to application details']),description:'I would appreciate an update on this request and guidance on the next steps needed to complete the process.',status,officer_id:status==='OPEN'?null:db.users.find(u=>u.role==='officer'&&u.department_id===a.department_id).id,resolution:status==='RESOLVED'?'The records have been checked and the applicant has been informed of the next steps.':'',created_at:iso(Math.min(created,now-3600000)),updated_at:iso(Math.min(created+days,now)),resolved_at:status==='RESOLVED'?iso(Math.min(created+days,now)):null});}
    return db;
  }
  window.Seed={generate,mulberry32,DOCUMENT_TYPES};
})();
