const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('../../.test-tools/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const base=process.env.AMAP_REACT_URL||'http://127.0.0.1:4173';
const errors=[];
async function login(page,role,email,password){await page.goto(base+'/login');await page.getByRole('button',{name:'Fill '+role+' demo'}).click();if(email){await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);}await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(url=>!url.pathname.includes('login'));}
async function logout(page){await page.getByRole('button',{name:'Account menu'}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/login');}
async function settle(page){await page.locator('main h1').first().waitFor();await page.waitForFunction(()=>!document.querySelector('[aria-label="Loading records"]'));await page.waitForTimeout(100);}
async function matrix(browser){let visits=0;const findings=[];for(const role of ['public','Citizen','Officer','Admin']){
 const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text()+' '+m.location().url); });
 await page.goto(base);if(role!=='public')await login(page,role);
 const routes=role==='public'?['/','/login','/register','/track']:role==='Citizen'?['/citizen','/citizen/apply','/citizen/applications','/citizen/applications/6006','/citizen/grievances','/profile']:role==='Officer'?['/officer','/officer/queue','/officer/review/6001','/officer/grievances','/profile']:['/admin','/admin/applications','/admin/departments','/admin/users','/admin/reports','/officer/grievances','/profile'];
 for(const theme of ['light','dark'])for(const width of [1536,1440,1280,1024,768,390]){await page.setViewportSize({width,height:960});await page.emulateMedia({colorScheme:theme});await page.evaluate(theme=>{localStorage.setItem('amap.theme',theme);},theme);for(const route of routes){await page.goto(base+route);await settle(page);const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,alerts:[...document.querySelectorAll('[role="alert"]')].map(n=>n.innerText),charts:[...document.querySelectorAll('.chart-box svg')].map(n=>({width:n.getBoundingClientRect().width,container:n.parentElement.getBoundingClientRect().width}))}));if(result.scroll>width+1||result.alerts.length||result.charts.some(c=>c.width>c.container+2))findings.push({role,theme,width,route,...result});visits++;if(width===1440&&theme==='light'&&['/','/citizen','/officer/queue','/admin'].includes(route))await page.screenshot({path:path.join(out,'react-'+(route==='/'?'home':route.slice(1).replaceAll('/','-'))+'.png'),fullPage:true});}console.log(role,theme,width,'checked');}
 await context.close();}
 fs.writeFileSync(path.join(out,'react-matrix.json'),JSON.stringify({visits,errors,findings},null,2));assert.deepEqual(errors,[]);assert.deepEqual(findings,[]);console.log('MATRIX PASSED:',visits);return visits;
}
async function workflow(browser){const context=await browser.newContext({acceptDownloads:true}),page=await context.newPage();page.setDefaultTimeout(20000);page.setDefaultNavigationTimeout(20000);page.on('framenavigated',frame=>{if(frame===page.mainFrame())console.log('Workflow:',frame.url());});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(base+'/register');
 const stamp=Date.now(),name='Nila Workflow',email='nila'+stamp+'@example.test';
 for(const [label,value] of [['Full name',name],['Email address',email],['Mobile number','9876543210'],['Residential address','42 Academic Lane, Hyderabad'],['Password','Workflow123!'],['Confirm password','Workflow123!']])await page.getByLabel(label,{exact:true}).fill(value);
 await page.getByLabel('City / District').selectOption('Hyderabad');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create account',exact:true}).click();await page.waitForURL('**/citizen');await page.goto(base+'/citizen/apply');await page.getByRole('button',{name:/Revenue Department/}).click();await page.getByRole('button',{name:/Income Certificate/}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Subject',{exact:true}).fill('Workflow income certificate');await page.getByLabel('Purpose / additional details').fill('Academic workflow verification with supporting identity evidence.');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Upload supporting documents').setInputFiles({name:'identity-proof.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRz0AAAAASUVORK5CYII=','base64')});await page.getByText('identity-proof.png',{exact:true}).waitFor();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue anyway'}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Submit application',exact:true}).click();const ref=await page.getByTestId('application-reference').innerText();const acknowledgment=page.waitForEvent('popup');await page.getByRole('button',{name:'Print acknowledgment'}).click();const popup=await acknowledgment;await popup.waitForLoadState();assert.ok((await popup.locator('body').innerText()).includes(ref));await popup.close();await page.getByRole('link',{name:'View application',exact:true}).click();const id=new URL(page.url()).pathname.split('/').at(-1);await logout(page);
 await page.goto(base+'/track?ref='+ref);await page.getByText('A clear record of every step').count();await settle(page);await page.getByText(ref,{exact:true}).first().waitFor();const body=await page.locator('body').innerText();assert.ok(!body.includes(name));assert.ok(!body.includes(email));assert.ok(body.includes('N. W.')); assert.ok(body.includes('n***@e***.test'));
 await login(page,'Officer');await page.goto(base+'/officer/review/'+id);await settle(page);await page.getByRole('button',{name:'Verify all',exact:true}).click();await page.getByRole('button',{name:'Insert suggested remarks'}).click();await page.getByRole('button',{name:'Review and confirm'}).click();await page.getByRole('button',{name:'Confirm decision',exact:true}).click();await page.getByRole('radio',{name:'Approve',exact:true}).waitFor();await page.getByRole('radio',{name:'Approve',exact:true}).check();await page.getByLabel('Decision remarks').fill('All documents have been verified and the application meets the income certificate requirements.');await page.getByRole('button',{name:'Review and confirm'}).click();await page.getByRole('button',{name:'Confirm decision',exact:true}).click();await page.getByText('This application is closed.',{exact:false}).waitFor();await logout(page);
 await login(page,'Citizen',email,'Workflow123!');await page.goto(base+'/citizen/applications/'+id);await settle(page);assert.ok((await page.locator('.timeline').innerText()).includes('Approved'));await page.getByRole('button',{name:/^Notifications/}).click();await page.getByText('Application approved',{exact:true}).waitFor();await page.keyboard.press('Escape');await page.goto(base+'/citizen/grievances');await page.getByLabel('Department',{exact:true}).selectOption('1');await page.getByLabel('Subject',{exact:true}).fill('Workflow grievance '+stamp);await page.getByLabel('What happened?').fill('Please clarify the delivery process for the certificate after approval.');await page.getByRole('button',{name:'Submit grievance'}).click();await page.getByText('Workflow grievance '+stamp,{exact:true}).waitFor();await logout(page);
 await login(page,'Officer');await page.goto(base+'/officer/grievances');await page.getByLabel('Search grievances').fill('Workflow grievance '+stamp);const row=page.locator('tr').filter({hasText:'Workflow grievance '+stamp});await row.getByRole('button',{name:'View details'}).click();await page.getByRole('button',{name:'Take up grievance'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await row.getByText('In progress',{exact:true}).waitFor();await row.getByRole('button',{name:'View details'}).click();await page.getByLabel('How was this resolved?').fill('The certificate delivery process was explained and the acknowledgment is available in the portal.');await page.getByRole('button',{name:'Confirm resolution'}).click();await row.getByText('Resolved',{exact:true}).waitFor();await logout(page);
 await login(page,'Admin');await page.goto(base+'/admin/applications?q='+ref);await page.getByRole('link',{name:ref,exact:true}).waitFor();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();const file=await download;await file.saveAs(path.join(out,'react-workflow-applications.csv'));assert.ok(fs.readFileSync(await file.path(),'utf8').includes(ref));await page.goto(base+'/admin');await settle(page);await page.getByText(ref,{exact:true}).first().waitFor();
 await page.goto(base+'/admin/departments');await page.getByRole('button',{name:'New department',exact:true}).click();await page.getByLabel('Department name').fill('Workflow Department '+stamp);await page.getByLabel('Code',{exact:true}).fill('W'+String(stamp).slice(-8));await page.getByLabel('Description',{exact:true}).fill('A department created during full browser verification.');await page.getByRole('button',{name:'Save department'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'New service',exact:true}).click();await page.getByLabel('Service name').fill('Workflow service '+stamp);await page.getByLabel('Code',{exact:true}).fill('S'+String(stamp).slice(-8));await page.getByLabel('Description',{exact:true}).fill('A service created during full browser verification.');await page.getByRole('dialog').getByLabel('Department',{exact:true}).selectOption({label:'Workflow Department '+stamp});await page.getByRole('button',{name:'Identity proof',exact:true}).click();await page.getByRole('button',{name:'Save service'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.goto(base+'/admin/users');await page.getByRole('button',{name:'Create staff account',exact:true}).click();await page.getByLabel('Full name',{exact:true}).fill('Workflow Officer');const officerEmail='officer'+stamp+'@example.test';await page.getByLabel('Email address',{exact:true}).fill(officerEmail);await page.getByLabel('Assigned department').selectOption({label:'Workflow Department '+stamp});await page.getByLabel('Temporary password',{exact:true}).fill('OfficerTest123!');await page.getByRole('button',{name:'Save staff account'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await logout(page);await login(page,'Officer',officerEmail,'OfficerTest123!');await settle(page);assert.ok((await page.locator('body').innerText()).includes('Workflow Department '+stamp));assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'react-workflow.json'),JSON.stringify({passed:true,ref,id,registered:email,newOfficer:officerEmail,steps:['register','wizard with file','print acknowledgment','masked public tracking','document verification','take up','approval','citizen audit and notification','grievance filing and resolution','admin register and analytics','CSV download','department and service creation','staff creation and login']},null,2));console.log('WORKFLOW PASSED',ref);await context.close();
}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{if(!process.argv.includes('--matrix-only'))await workflow(browser);if(!process.argv.includes('--workflow-only'))await matrix(browser);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
