import {useId,useRef,useState} from 'react';
import useResizeObserver from '../../hooks/useResizeObserver.js';
import {useTheme} from '../../context/ThemeContext.jsx';
import {num} from '../../lib/format.js';
export function palette(){const style=getComputedStyle(document.documentElement);return Array.from({length:8},(_,i)=>style.getPropertyValue('--series-'+(i+1)).trim());}
function color(token,fallback){return token?.startsWith('--')?getComputedStyle(document.documentElement).getPropertyValue(token).trim():token||fallback;}
export function Legend({items=[]}){useTheme();const p=palette();return <ul className="legend">{items.map((r,i)=><li className="legend-item" key={r.label}><span className="swatch" style={{background:color(r.color,p[i%8])}} aria-hidden="true"/>{r.label}{r.value!=null&&<b className="lv">{num(r.value)}</b>}</li>)}</ul>;}
export function ChartTooltip({tip}){return tip?<div className="viz-tip is-on chart-tooltip" role="tooltip" style={{left:tip.x,top:tip.y}}><b>{tip.label}</b>{tip.rows.map((r,i)=><div className="tip-row" key={i}><span>{r.name}</span><b>{num(r.value)}</b></div>)}</div>:null;}
function Frame({title='Chart',height=240,children}) {
  const ref=useRef(),{width}=useResizeObserver(ref),[tip,setTip]=useState(null);useTheme();const p=palette(),w=Math.max(180,width);
  const hot=(label,rows)=>({tabIndex:0,role:'graphics-symbol','aria-label':label+': '+rows.map(r=>r.name+' '+num(r.value)).join(', '),onMouseMove:e=>show(e,label,rows),onFocus:e=>show(e,label,rows),onMouseLeave:()=>setTip(null),onBlur:()=>setTip(null)});
  function show(e,label,rows){const r=ref.current.getBoundingClientRect();const t=e.currentTarget.getBoundingClientRect();setTip({label,rows,x:Math.max(4,Math.min(w-210,(e.clientX||t.x)-r.x+12)),y:Math.max(4,Math.min(height-60,(e.clientY||t.y)-r.y-20))});}
  return <div className="chart-box" ref={ref}><svg viewBox={`0 0 ${w} ${height}`} width={w} height={height} role="img" aria-label={title}><title>{title}</title>{children({w,h:height,p,hot})}</svg><ChartTooltip tip={tip}/></div>;
}
function scale(max){if(max<=0)return {max:4,ticks:[0,1,2,3,4]};const raw=max/4,mag=10**Math.floor(Math.log10(raw)),norm=raw/mag,step=(norm<=1?1:norm<=2?2:norm<=2.5?2.5:norm<=5?5:10)*mag;const top=Math.ceil(max/step)*step;return {max:top,ticks:Array.from({length:Math.round(top/step)+1},(_,i)=>i*step)};}
function Grid({sc,y,w,h}){return <g>{sc.ticks.map(t=><g key={t}><line x1={42} y1={y(t)} x2={w-18} y2={y(t)} stroke="var(--chart-grid)"/><text x={34} y={y(t)+4} textAnchor="end" fill="var(--chart-label)" fontSize={11}>{num(t)}</text></g>)}<line x1={42} y1={h-32} x2={w-18} y2={h-32} stroke="var(--chart-axis)"/></g>;}
export function AreaChart({labels=[],fullLabels,series=[],height=260,title='Application volume',fill=true}) {
  const id=useId().replaceAll(':','');
  return <Frame title={title} height={height}>{({w,h,p,hot})=>{const n=labels.length,pw=w-60,ph=h-48,sc=scale(Math.max(0,...series.flatMap(s=>s.data))),x=i=>42+(n<=1?pw/2:pw*i/(n-1)),y=v=>16+ph-ph*(v||0)/sc.max,every=Math.max(1,Math.ceil(n*48/pw));return <><Grid sc={sc} y={y} w={w} h={h}/><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color(series[0]?.color,p[0])} stopOpacity=".23"/><stop offset="100%" stopColor={color(series[0]?.color,p[0])} stopOpacity="0"/></linearGradient></defs>{!n&&<text x={w/2} y={h/2} textAnchor="middle" fill="var(--ink-muted)">No data in this period</text>}{series.map((s,k)=>{const points=s.data.map((v,i)=>`${x(i)},${y(v)}`).join(' '),c=color(s.color,p[k%8]);return <g key={s.name}>{fill&&k===0&&n>0&&<polygon fill={`url(#${id})`} points={`${x(0)},${h-32} ${points} ${x(n-1)},${h-32}`}/>}<polyline points={points} fill="none" stroke={c} strokeWidth={2} strokeLinejoin="round"/></g>;})}{labels.map((label,i)=><g className="chart-hot" key={i} {...hot(fullLabels?.[i]||label,series.map(s=>({name:s.name,value:s.data[i]})))}>{(i%every===0||i===n-1)&&<text x={x(i)} y={h-9} textAnchor="middle" fontSize={11} fill="var(--chart-label)">{label}</text>}<rect x={Math.max(42,x(i)-pw/Math.max(n-1,1)/2)} y={16} width={Math.min(pw/Math.max(n-1,1),w-18-Math.max(42,x(i)-pw/Math.max(n-1,1)/2))} height={ph} fill="transparent"/><line className="cross" x1={x(i)} x2={x(i)} y1={16} y2={h-32} stroke="var(--chart-axis)" strokeDasharray="3 3"/>{series.map((s,k)=><circle className="focus" key={s.name} cx={x(i)} cy={y(s.data[i])} r={4} fill={color(s.color,p[k%8])} stroke="var(--surface)" strokeWidth={2}/>)}</g>)}</>;}}</Frame>;
}
export function BarChart({labels=[],series=[],stacked=false,height=240,title='Applications by period'}) {return <Frame title={title} height={height}>{({w,h,p,hot})=>{const pw=w-60,ph=h-48,slot=pw/Math.max(1,labels.length),group=Math.min(52,slot*.72),bw=group/Math.max(1,stacked?1:series.length),sc=scale(Math.max(0,...(stacked?labels.map((_,i)=>series.reduce((n,s)=>n+(s.data[i]||0),0)):series.flatMap(s=>s.data)))),y=v=>16+ph-ph*v/sc.max;return <><Grid sc={sc} y={y} w={w} h={h}/>{labels.map((label,i)=>{let acc=0;const x=42+slot*i+(slot-group)/2;return <g className="chart-hot" key={i} {...hot(label,series.map(s=>({name:s.name,value:s.data[i]||0})))}><rect x={42+slot*i} y={16} width={slot} height={ph} fill="transparent"/><line className="cross" x1={42+slot*(i+.5)} x2={42+slot*(i+.5)} y1={16} y2={h-32} stroke="var(--chart-axis)" strokeDasharray="3 3"/>{series.map((s,k)=>{const value=s.data[i]||0,base=stacked?acc:0;acc+=value;return <rect key={s.name} x={x+(stacked?0:k*bw)} y={y(base+value)} width={Math.max(1,bw-2)} height={ph*value/sc.max} rx={3} fill={color(s.color,p[k%8])}/>;})}{i%Math.max(1,Math.ceil(labels.length*45/pw))===0&&<text x={42+slot*(i+.5)} y={h-10} textAnchor="middle" fontSize={11} fill="var(--chart-label)">{label}</text>}</g>;})}</>;}}</Frame>;}
export function HBarChart({rows=[],height,color:token,title='Ranked applications',rowHeight=35}) {return <Frame title={title} height={height||Math.max(120,rows.length*rowHeight+14)}>{({w,p,hot})=>{const labelW=Math.min(190,w*.42),pw=w-labelW-48,max=Math.max(1,...rows.map(r=>r.value));return rows.length?rows.map((r,i)=><g key={r.label} {...hot(r.label,[{name:'Total',value:r.value}])}><text x={0} y={25+i*rowHeight} fontSize={12} fill="var(--ink)">{r.label.length>labelW/7?r.label.slice(0,Math.floor(labelW/7)-1)+'…':r.label}</text><rect x={labelW} y={12+i*rowHeight} width={pw} height={16} rx={4} fill="var(--chart-grid)"/><rect x={labelW} y={12+i*rowHeight} width={pw*r.value/max} height={16} rx={4} fill={color(r.color||token,p[0])}/><text x={w-2} y={25+i*rowHeight} textAnchor="end" fontSize={12} fill="var(--ink)">{num(r.value)}</text></g>):<text x={w/2} y={65} textAnchor="middle" fill="var(--ink-muted)">No matching activity</text>;}}</Frame>;}
export function HBarStacked({rows=[],names=[],colors=[],title='Department load'}) {return <Frame title={title} height={Math.max(120,rows.length*38+12)}>{({w,p,hot})=>{const labelW=Math.min(180,w*.36),pw=w-labelW-46,max=Math.max(1,...rows.map(r=>r.parts.reduce((s,n)=>s+n,0)));return rows.map((r,i)=>{let acc=0;return <g key={r.label} {...hot(r.label,r.parts.map((value,k)=>({name:names[k],value})))}><text x={0} y={25+i*38} fontSize={12} fill="var(--ink)">{r.label.length>labelW/7?r.label.slice(0,Math.floor(labelW/7)-1)+'…':r.label}</text>{r.parts.map((v,k)=>{const x=labelW+pw*acc/max;acc+=v;return <rect key={k} x={x} y={12+i*38} width={pw*v/max} height={18} fill={color(colors[k],p[k%8])} stroke="var(--surface)" strokeWidth={1}/>;})}<text x={w-2} y={25+i*38} textAnchor="end" fontSize={12} fill="var(--ink)">{num(acc)}</text></g>;});}}</Frame>;}
export function Donut({slices=[],centerLabel='applications',height=220,title='Status breakdown',legend=true}) {const rows=slices.filter(s=>s.value>0);return <><Frame title={title} height={height}>{({w,h,p,hot})=>{const total=rows.reduce((n,s)=>n+s.value,0),cx=w/2,cy=h/2,r=Math.min(w,h)/2-18,sw=r*.35,circ=2*Math.PI*r;let offset=0;return <><circle cx={cx} cy={cy} r={r} fill="none" stroke="var(--chart-grid)" strokeWidth={sw}/>{rows.map((s,i)=>{const length=s.value/total*circ,start=offset;offset+=length;return <circle key={s.label} cx={cx} cy={cy} r={r} fill="none" stroke={color(s.color,p[i%8])} strokeWidth={sw} strokeDasharray={`${Math.max(0,length-2)} ${circ}`} strokeDashoffset={-start} transform={`rotate(-90 ${cx} ${cy})`} {...hot(s.label,[{name:centerLabel,value:s.value},{name:'Percent',value:Math.round(s.value/total*1000)/10}])}/>;})}<text x={cx} y={cy} fontSize={26} fontWeight={700} textAnchor="middle" fill="var(--ink)">{num(total)}</text><text x={cx} y={cy+21} fontSize={12} textAnchor="middle" fill="var(--chart-label)">{total?centerLabel:'No records'}</text></>;}}</Frame>{legend&&<Legend items={rows}/>}</>;}
export function Gauge({value=0,max=100,label='of decisions',suffix='%',title='Approval rate'}) {return <Frame title={title} height={185}>{({w,h,p,hot})=>{const cx=w/2,cy=h-32,r=Math.min(w/2-28,h-54),path=`M ${cx-r},${cy} A ${r},${r} 0 0 1 ${cx+r},${cy}`,len=Math.PI*r;return <g {...hot(title,[{name:label,value}])}><path d={path} fill="none" stroke="var(--chart-grid)" strokeWidth={20} strokeLinecap="round"/><path d={path} fill="none" stroke={p[2]} strokeWidth={20} strokeDasharray={`${len*Math.min(1,Math.max(0,value/max))} ${len}`} strokeLinecap="round"/><text x={cx} y={cy-8} textAnchor="middle" fontSize={30} fontWeight={700} fill="var(--ink)">{num(value)}{suffix}</text><text x={cx} y={cy+20} textAnchor="middle" fontSize={12} fill="var(--chart-label)">{label}</text></g>;}}</Frame>;}
export function Sparkline({data=[],title='Recent trend'}) {return <Frame title={title} height={48}>{({w,p,hot})=>{const min=Math.min(0,...data),max=Math.max(1,...data),y=v=>43-(v-min)/(max-min||1)*38,x=i=>4+(w-8)*i/Math.max(1,data.length-1);return <g {...hot(title,[{name:'Latest',value:data.at(-1)||0}])}><polyline points={data.map((v,i)=>`${x(i)},${y(v)}`).join(' ')} fill="none" stroke={p[0]} strokeWidth={2}/></g>;}}</Frame>;}
