import {createContext,useContext,useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Link} from 'react-router';
import Icon from '../Icon.jsx';
import {initials,fmtDate,timeAgo,num,fileSize} from '../../lib/format.js';
import {STATUS_LABEL,STATUS_ICON,STATUS_TONE,STATUS_ORDER,statusColor,lifecyclePercent,statusHelp} from '../../lib/status.js';
export function Button({children,variant='primary',icon,busy=false,type='button',className='',...props}) {return <button type={type} className={`btn btn-${variant} ${className}`} {...props} disabled={busy||props.disabled} aria-busy={busy||undefined}>{busy?<span className="spinner"/>:icon?<Icon name={icon} size={16}/>:null}{busy?'Please wait…':children}</button>;}
export function ButtonLink({to,children,variant='primary',icon,...p}) {return <Link className={'btn btn-'+variant} to={to} {...p}>{icon&&<Icon name={icon} size={16}/>} {children}</Link>;}
export function Card({title,subtitle,actions,children,className='',flush=false}) {return <section className={'card '+className}>{title&&<div className="card-head"><div><h2>{title}</h2>{subtitle&&<p className="sub">{subtitle}</p>}</div>{actions}</div>}<div className={flush?'':'card-body'}>{children}</div></section>;}
export function PageHead({title,lead,children}) {return <div className="page-head"><div><h1>{title}</h1>{lead&&<p className="lead">{lead}</p>}</div><div className="page-actions">{children}</div></div>;}
export function StatTile({label,value,sub,icon='files',tone=''}) {return <div className="stat"><div className="stat-top"><span className="stat-label">{label}</span><span className={'stat-ico '+tone}><Icon name={icon}/></span></div><div className="stat-value sm" key={String(value)}>{typeof value==='number'?num(value):value}</div>{sub&&<div className="stat-sub">{sub}</div>}</div>;}
export function Stats({items}) {return <div className="kpi-strip mb-6">{items.map((t,i)=><StatTile key={t.label||i} {...t}/>)}</div>;}
export function Badge({status,children}) {const token=STATUS_ORDER.includes(status)?'var('+statusColor(status)+')':null;return <span style={token?{color:token,background:'color-mix(in srgb, '+token+' 10%, var(--surface))'}:undefined} className={'badge no-dot badge-'+String(status||'').toLowerCase()}><Icon name={STATUS_ICON[status]||'info'} size={13}/>{children||STATUS_LABEL[status]||status}</span>;}
export function Priority({value='NORMAL'}) {return <span className={'pri pri-'+value.toLowerCase()}>{value[0]+value.slice(1).toLowerCase()}</span>;}
export function Avatar({name,size=''}) {return <span className={'avatar '+size} aria-hidden="true">{initials(name)}</span>;}
export function EmptyState({title='No matching records',message='Try clearing a filter to see more results.',children}) {return <div className="empty"><div className="e-ico"><Icon name="inbox" size={26}/></div><h3>{title}</h3><p>{message}</p>{children&&<div className="mt-4">{children}</div>}</div>;}
export function Skeleton({rows=4}) {return <div className="loading-layout" role="status" aria-label="Loading records"><span className="sr-only">Loading…</span>{Array.from({length:rows},(_,i)=><div key={i} className="skeleton" style={{height:i===0?76:48,marginBottom:12}}/>)}</div>;}
export function Alert({children,type='info'}) {return <div className={'alert '+type} role={type==='danger'?'alert':undefined}><Icon name={type==='danger'||type==='warning'?'alert':'info'} size={18}/><div>{children}</div></div>;}
export function ApiState({state,children}) {if(state.error)return <Alert type="danger"><p>{state.error.message}</p><Button variant="outline" onClick={state.refetch}>Try again</Button></Alert>;if(state.loading&&!state.data)return <Skeleton/>;return children;}
export function Field({label,id:given,hint,as='input',children,className='',...props}) {const uid=useId(),id=given||uid,[error,setError]=useState('');const Tag=as;return <div className={'field '+(error?'has-error ':'')+className}><label className="label" htmlFor={id}>{label}{props.required&&<span className="req" aria-hidden="true">*</span>}</label><Tag id={id} aria-label={label} className={as==='select'?'select':as==='textarea'?'textarea':'input'} {...props} aria-describedby={hint||error?id+'-hint':undefined} aria-invalid={!!error} onBlur={e=>{setError(e.target.validationMessage);props.onBlur?.(e);}} onChange={e=>{if(error)setError(e.target.validationMessage);props.onChange?.(e);}}>{children}</Tag>{(hint||error)&&<span id={id+'-hint'} className={error?'err':'hint'}>{error||hint}</span>}</div>;}
export function PasswordMeter({value=''}) {const score=Number(value.length>=8)+Number(/[A-Z]/.test(value)&&/[a-z]/.test(value))+Number(/\d/.test(value))+Number(/[^a-z0-9]/i.test(value)||value.length>=12);return <div><div className="pw-meter" data-level={value?Math.max(1,score):0} aria-hidden="true">{[1,2,3,4].map(i=><span key={i}/>)}</div><p className="hint">{value?['Very short','Weak','Fair','Good','Strong'][score]:'Use at least 8 characters.'}</p></div>;}
export function PasswordInput({label='Password',value,onChange,showMeter=false,...props}) {const [show,setShow]=useState(false);return <div className="password-field"><Field label={label} type={show?'text':'password'} value={value} onChange={onChange} {...props}/><button type="button" className="password-toggle icon-btn" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}><Icon name={show?'eyeOff':'eye'} size={16}/></button>{showMeter&&<PasswordMeter value={value}/>}</div>;}
export function Seg({items,value,onChange,label='Choose an option'}) {return <div className="seg" role="group" aria-label={label}>{items.map(item=><button type="button" key={item.value} aria-pressed={value===item.value} className={value===item.value?'is-active':''} onClick={()=>onChange(item.value)}>{item.label}</button>)}</div>;}
export function Tabs(props){return <Seg {...props}/>;}
export function Stepper({step,labels=['Choose service','Your details','Documents','Review & submit']}) {return <ol className="stepper" aria-label="Application progress">{labels.map((label,i)=><li key={label} className={'step '+(i+1<step?'is-done':i+1===step?'is-active':'')} aria-current={i+1===step?'step':undefined}><span className="step-num">{i+1<step?<Icon name="check" size={16}/>:i+1}</span><span className="step-label">{label}</span></li>)}</ol>;}
export function Timeline({logs=[]}) {if(!logs.length)return <p className="muted">No activity recorded yet.</p>;return <ol className="timeline">{logs.map((l,i)=><li className="tl-item" key={l.id}><span style={STATUS_ORDER.includes(l.to_status)?{color:'var('+statusColor(l.to_status)+')',borderColor:'var('+statusColor(l.to_status)+')'}:undefined} className={'tl-dot '+(STATUS_TONE[l.to_status]||'')+(i===logs.length-1?' current':'')}><Icon name={STATUS_ICON[l.to_status]||'info'} size={11}/></span><div className="tl-title">{STATUS_LABEL[l.to_status]||l.to_status}</div><div className="tl-meta">{fmtDate(l.created_at,true)} · {l.actor_name||(l.actor_role==='CITIZEN'?'Applicant':l.actor_role==='OFFICER'?'Department officer':l.actor_role==='ADMIN'?'Administrator':'System')}</div>{l.remarks&&<p className="tl-note">{l.remarks}</p>}</li>)}</ol>;}
export function Activity({rows=[]}) {return rows.length?<ol className="feed">{rows.map(a=><li className="feed-item" key={a.id}><Badge status={a.to_status}/><div className="flex-1"><strong>{a.actor}</strong><p className="mono text-xs">{a.ref}</p><p className="text-xs muted">{a.remarks}</p></div><time className="text-xs muted" dateTime={a.at}>{timeAgo(a.at)}</time></li>)}</ol>:<EmptyState title="No recent activity" message="Updates will appear here as applications move forward."/>;}
export function Progress({application:a}) {return <div className="mb-5"><div className="flex justify-between gap-3 mb-3"><Badge status={a.status}/><span className="muted text-sm">{a.sla_days} day timeline</span></div><div className="progress" role="progressbar" aria-label="Application progress" aria-valuenow={lifecyclePercent(a.status)} aria-valuemin={0} aria-valuemax={100}><span style={{width:lifecyclePercent(a.status)+'%'}}/></div><p className="muted text-sm mt-2">{statusHelp[a.status]}</p></div>;}
export function Details({items}) {return <dl className="dl">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl>;}
export function Pagination({total=0,offset=0,limit=12,onChange}) {const page=Math.floor(offset/limit)+1,pages=Math.max(1,Math.ceil(total/limit));return <div className="pager"><span aria-live="polite">{total?`${num(offset+1)}–${num(Math.min(total,offset+limit))} of ${num(total)}`:'0 records'}</span><div className="pager-btns"><button disabled={page===1} onClick={()=>onChange(Math.max(0,offset-limit))} aria-label="Previous page">‹</button><span className="page-number">Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>onChange(offset+limit)} aria-label="Next page">›</button></div></div>;}
export function Table({rows=[],columns,total,offset=0,limit=12,onPage,loading=false,sort,direction,onSort,selected,onSelect,canSelect=()=>true,empty,caption='Records',rowKey='id'}) {
  const eligible=rows.filter(canSelect),all=eligible.length>0&&eligible.every(r=>selected?.includes(r[rowKey]));
  return <div aria-busy={loading}><div className="table-wrap" tabIndex={0} role="region" aria-label={caption+' table; scroll for more columns'}><table className={'table '+(columns.length>7?'table-wide':'')}><caption className="sr-only">{caption}</caption><thead><tr>{onSelect&&<th><input type="checkbox" aria-label="Select current page" checked={all} disabled={!eligible.length} onChange={()=>onSelect(all?selected.filter(id=>!eligible.some(r=>r[rowKey]===id)):[...new Set([...selected,...eligible.map(r=>r[rowKey])])])}/></th>}{columns.map(c=><th key={c.key} className={c.action?'actions':''} aria-sort={c.sortKey&&sort===c.sortKey?(direction==='asc'?'ascending':'descending'):undefined}>{c.sortKey&&onSort?<button className="sort-button" onClick={()=>onSort(c.sortKey,sort===c.sortKey&&direction==='asc'?'desc':'asc')}>{c.label}<span aria-hidden="true">{sort===c.sortKey?(direction==='asc'?' ↑':' ↓'):' ↕'}</span></button>:c.label}</th>)}</tr></thead><tbody>{loading&&!rows.length?<tr><td colSpan={columns.length+(onSelect?1:0)}><Skeleton rows={3}/></td></tr>:rows.length?rows.map(r=><tr key={r[rowKey]} className={selected?.includes(r[rowKey])?'row-selected':''}>{onSelect&&<td><input type="checkbox" aria-label={'Select '+(r.ref||r.full_name||r.id)} disabled={!canSelect(r)} checked={selected.includes(r[rowKey])} onChange={()=>onSelect(selected.includes(r[rowKey])?selected.filter(id=>id!==r[rowKey]):[...selected,r[rowKey]])}/></td>}{columns.map(c=><td key={c.key} className={c.action?'actions':c.className||''}>{c.render?c.render(r):r[c.key]??'—'}</td>)}</tr>):<tr><td colSpan={columns.length+(onSelect?1:0)}>{empty||<EmptyState/>}</td></tr>}</tbody></table></div>{onPage&&<Pagination total={total??rows.length} offset={offset} limit={limit} onChange={onPage}/>}</div>;
}
export function Modal({title,children,onClose,actions,size='lg',busy=false}) {
  const ref=useRef(),id=useId(),closeRef=useRef(onClose);closeRef.current=onClose;
  useEffect(()=>{const prev=document.activeElement,old=document.body.style.overflow;document.body.style.overflow='hidden';const node=ref.current;const focus=()=>[...node.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(n=>n.getClientRects().length);(focus()[0]||node).focus();const key=e=>{if(e.key==='Escape'){e.preventDefault();closeRef.current();}if(e.key==='Tab'){const els=focus(),first=els[0],last=els.at(-1);if(!first){e.preventDefault();node.focus();}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;prev?.focus();};},[]);
  return createPortal(<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><section className={'modal modal-'+size} ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={id}><div className="modal-head"><h2 id={id}>{title}</h2><button className="modal-close" aria-label="Close dialog" disabled={busy} onClick={onClose}><Icon name="x"/></button></div><div className="modal-body">{children}</div>{actions&&<div className="modal-foot">{actions}</div>}</section></div>,document.body);
}
const ConfirmContext=createContext(null);
export function ConfirmProvider({children}) {const [dialog,setDialog]=useState(null);const confirm=options=>new Promise(resolve=>setDialog({...options,resolve}));const finish=value=>{dialog.resolve(value);setDialog(null);};return <ConfirmContext.Provider value={confirm}>{children}{dialog&&<Modal title={dialog.title||'Confirm this action'} size="sm" onClose={()=>finish(false)} actions={<><Button variant="outline" onClick={()=>finish(false)}>Cancel</Button><Button variant={dialog.danger?'danger':'primary'} onClick={()=>finish(true)}>{dialog.confirmLabel||'Confirm'}</Button></>}>{dialog.message}</Modal>}</ConfirmContext.Provider>;}
export const useConfirm=()=>useContext(ConfirmContext);
export function Dropdown({label,trigger,children,className=''}) {const [open,setOpen]=useState(false),ref=useRef();useEffect(()=>{const listener=e=>{if(!ref.current?.contains(e.target))setOpen(false);};const key=e=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',listener);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',listener);document.removeEventListener('keydown',key);};},[]);return <div className={'dd '+className} ref={ref}><button className="icon-btn" aria-label={label} aria-expanded={open} onClick={()=>setOpen(!open)}>{trigger}</button>{open&&<div className="dd-menu" onClick={e=>{if(e.target.closest('a'))setOpen(false);}}>{typeof children==='function'?children(()=>setOpen(false)):children}</div>}</div>;}
export function Dropzone({files,onChange,requiredDocs=[]}) {
  const input=useRef(),[drag,setDrag]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function add(fileList){setBusy(true);setError('');try{const next=[...files];for(const file of fileList){if(!['application/pdf','image/png','image/jpeg'].includes(file.type)||file.size>5*1024*1024||!file.size)throw Error('Choose a PDF, JPG or PNG, up to 5 MB per file.');if(next.some(f=>f.file_name===file.name))continue;const content=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read the file.'));r.readAsDataURL(file);});const lower=file.name.toLowerCase().replace(/[_-]/g,' '),name=requiredDocs.find(d=>d.toLowerCase().split(/\W+/).some(w=>w.length>3&&lower.includes(w)))||requiredDocs[0]||'Supporting document';next.push({name,file_name:file.name,mime:file.type,size_kb:file.size/1024,content});}onChange(next);}catch(e){setError(e.message);}finally{setBusy(false);if(input.current)input.current.value='';}}
  return <div>{requiredDocs.length>0&&<Alert>Required: {requiredDocs.join(' · ')}</Alert>}<div className={'dropzone mt-4 '+(drag?'is-over':'')} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);add([...e.dataTransfer.files]);}}><div className="dz-ico"><Icon name="upload"/></div><Button variant="outline" onClick={()=>input.current.click()} busy={busy}>Choose documents</Button><p className="muted text-sm mt-2">Or drop files here · PDF, JPG, PNG · up to 5 MB each</p><input ref={input} className="sr-only" type="file" multiple accept=".pdf,.jpg,.jpeg,.png" aria-label="Upload supporting documents" onChange={e=>add([...e.target.files])}/></div>{error&&<Alert type="danger">{error}</Alert>}{files.map((f,i)=><div className="file-row" key={f.file_name}><Icon name="fileText"/><div className="flex-1"><b className="file-name">{f.file_name}</b><p className="hint">{fileSize(f.size_kb)}</p><Field label={'Document type for '+f.file_name} as="select" value={f.name} onChange={e=>onChange(files.map((x,j)=>i===j?{...x,name:e.target.value}:x))}>{[...new Set([...requiredDocs,'Supporting document',f.name])].map(d=><option key={d}>{d}</option>)}</Field></div><button type="button" className="icon-btn" aria-label={'Remove '+f.file_name} onClick={()=>onChange(files.filter((_,j)=>i!==j))}><Icon name="trash"/></button></div>)}</div>;
}
