UI.run(async()=>{
  const user=await Auth.guard(['admin']);if(!user)return;
  await Shell.mount({title:'Turn the records into a clearer story.',subtitle:'Build a scoped report, compare outcomes, and share the results.',eyebrow:'Reports & insights',actions:'<button class="btn" id="report-csv">'+Icons('download')+'Export applications</button><button class="btn primary" id="report-print">'+Icons('print')+'Print / Save PDF</button>'});
  const departments=await API.departments.list();let generatedScope={},currentData;
  function iso(d){return d.toISOString().slice(0,10);}const today=new Date(),start=new Date();start.setDate(start.getDate()-90);
  UI.$('#page').innerHTML='<form class="card no-print" id="report-form"><div class="filters">'+UI.select('Period','report-preset',[{id:'30',name:'Last 30 days'},{id:'90',name:'Last 90 days'},{id:'365',name:'Last 12 months'},{id:'month',name:'This month'},{id:'custom',name:'Custom date range'}],'90',null)+UI.field('From','report-from','date',iso(start),'required')+UI.field('Through','report-to','date',iso(today),'required')+UI.select('Department','report-department',departments,'','All departments')+UI.select('Status','report-status',Views.statuses,'','All statuses')+'<button type="submit" class="btn primary" style="align-self:flex-end">Generate report'+Icons('arrow')+'</button></div></form><div class="report-banner" id="report-banner"></div><div class="stack" id="report-content"></div>';
  async function generate(){const from=UI.$('#report-from').value,to=UI.$('#report-to').value;if(from>to){UI.toast('The start date must be before the end date.','error');return;}const scope={from,to,department_id:UI.$('#report-department').value,status:UI.$('#report-status').value};const data=await API.analytics.dashboard(scope);generatedScope=scope;currentData=data;const d=departments.find(d=>d.id===Number(scope.department_id));UI.$('#report-banner').innerHTML='<div class="eyebrow">SERVICE DELIVERY REPORT</div><h2>'+(d?UI.e(d.name):'All departments')+' · '+UI.e(scope.status?UI.labels[scope.status]:'All statuses')+'</h2><p>'+UI.e(UI.date(from))+' – '+UI.e(UI.date(to))+' · '+data.kpis.total+' applications · Generated '+UI.e(UI.date(new Date(),true))+'</p>';UI.$('#report-content').innerHTML=Views.analyticsMarkup(data,true);Views.drawAnalytics(data,true);}
  UI.$('#report-preset').onchange=ev=>{const value=ev.target.value;if(value==='custom')return;const from=new Date();if(value==='month')from.setDate(1);else from.setDate(from.getDate()-Number(value));UI.$('#report-from').value=iso(from);UI.$('#report-to').value=iso(new Date());};['report-from','report-to'].forEach(id=>UI.$('#'+id).onchange=()=>UI.$('#report-preset').value='custom');
  UI.$('#report-form').onsubmit=ev=>{ev.preventDefault();UI.busy(UI.$('button[type=submit]',ev.target),generate);};UI.$('#report-csv').onclick=()=>UI.busy(UI.$('#report-csv'),async()=>UI.csv('service-delivery-report',await API.applications.list(generatedScope),Views.exportColumns));UI.$('#report-print').onclick=()=>{if(currentData){Charts.redrawAll();window.print();}};await generate();
});

