UI.run(async()=>{
  const user=await Auth.guard(['citizen']);if(!user)return;
  await Shell.mount({title:'Start something. We’ll help you finish.',subtitle:'A few details today. A clear path to your service.',eyebrow:'New application'});
  const [departments,services]=await Promise.all([API.departments.list(),API.services.list()]);
  let step=1,departmentId='',serviceId='',documents=[],form={full_name:user.name,email:user.email,phone:user.phone,address:user.address,purpose:''},reading=false;
  const requested=services.find(s=>s.id===Number(new URLSearchParams(location.search).get('service')));if(requested){departmentId=requested.department_id;serviceId=requested.id;}
  const service=()=>services.find(s=>s.id===Number(serviceId));
  function summary(){const s=service();return '<aside class="card service-summary">'+Views.head('Your service at a glance')+(s?'<span class="badge">'+Icons('building')+UI.e(departments.find(d=>d.id===s.department_id).name)+'</span><h2 style="margin:1rem 0">'+UI.e(s.name)+'</h2><p class="small muted">'+UI.e(s.description)+'</p><dl class="details"><dt>Service fee</dt><dd>'+UI.e(UI.currency(s.fee))+'</dd><dt>Timeline</dt><dd>'+s.sla_days+' days</dd></dl><div class="divider"></div><h3>Documents to keep ready</h3><ul>'+s.required_documents.map(d=>'<li>'+UI.e(d)+'</li>').join('')+'</ul><small>No payment is collected in this demo.</small>':'<p class="small muted">Select a department and service to see its fee, processing timeline, and required documents.</p>')+'</aside>';}
  function render(){const s=service();UI.$('#page').innerHTML='<ol class="steps" aria-label="Application progress">'+['Choose service','Your details','Documents','Review & submit'].map((name,i)=>'<li class="step '+(i+1<=step?'active':'')+'" '+(i+1===step?'aria-current="step"':'')+'><span>'+(i+1)+'</span>'+name+'</li>').join('')+'</ol><div class="wizard-layout"><section class="card"><form id="wizard-form"><div id="wizard-step"></div><div class="wizard-actions"><button type="button" class="btn" id="wizard-back" '+(step===1?'disabled':'')+'>'+Icons('back')+'Back</button><button class="btn primary" type="submit" id="wizard-next">'+(step===4?'Submit application':'Continue')+Icons(step===4?'send':'arrow')+'</button></div></form></section>'+summary()+'</div>';
    const root=UI.$('#wizard-step');
    if(step===1){root.innerHTML='<h2>Which service do you need?</h2><p class="small muted">Start with a department, then choose your service.</p>'+UI.select('Department','department',departments,departmentId,'Choose a department','required')+'<div id="service-options" class="wizard-options"></div>';function showServices(){const list=services.filter(s=>s.department_id===Number(departmentId)&&s.active);UI.$('#service-options').innerHTML=list.length?list.map(s=>'<label class="option-card '+(Number(serviceId)===s.id?'selected':'')+'"><input type="radio" name="service" value="'+s.id+'" '+(Number(serviceId)===s.id?'checked':'')+' required><span><strong>'+UI.e(s.name)+'</strong><small>'+UI.e(UI.currency(s.fee))+' · '+s.sla_days+' day timeline</small></span></label>').join(''):'<p class="muted small">Choose a department to see its services.</p>';UI.$$('input[name=service]').forEach(n=>n.onchange=()=>{serviceId=Number(n.value);documents=[];render();});}UI.$('#department').onchange=ev=>{departmentId=ev.target.value;serviceId='';documents=[];render();};showServices();}
    if(step===2){root.innerHTML='<h2>Tell us about your request</h2><p class="small muted">Check your details carefully. They’ll be included in the application.</p><div class="form-grid">'+UI.field('Full name','full_name','text',form.full_name,'required minlength="3" maxlength="100" autocomplete="name"')+UI.field('Email address','email','email',form.email,'required autocomplete="email"')+UI.field('Mobile number','phone','tel',form.phone,'required pattern="[0-9]{10,15}" autocomplete="tel"')+UI.field('Address','address','text',form.address,'required minlength="8" maxlength="300" autocomplete="street-address"')+'</div><div class="field"><label for="purpose">Purpose of application</label><textarea id="purpose" name="purpose" required minlength="15" maxlength="2000" placeholder="Tell the department why you need this service.">'+UI.e(form.purpose)+'</textarea><span class="hint">At least 15 characters. Include details that will help the officer review your request.</span></div>';}
    if(step===3){root.innerHTML='<h2>A little proof goes a long way.</h2><p class="small muted">Attach clear copies of your required documents and check each label.</p><div class="dropzone" id="upload-dropzone">'+Icons('upload')+'<p><strong>Drop your files here</strong>, or select them below</p><input id="document-upload" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.txt" aria-label="Upload supporting documents"><p class="small muted">PDF, PNG, JPG, TXT · 1 MB per file · 2 MB total</p></div><div id="file-list"></div><div id="document-warning" aria-live="polite" style="margin-top:1rem"></div>';
      UI.dropzone(UI.$('#upload-dropzone'),async files=>{
        if(reading){UI.toast('Please wait for the selected documents to finish loading.');return;}
        reading=true;const controls=[UI.$('#wizard-next'),UI.$('#wizard-back'),UI.$('#document-upload')];controls.forEach(n=>n.disabled=true);
        try{const added=await UI.files(files,s.required_documents);if([...documents,...added].reduce((n,d)=>n+d.size,0)>2*1024*1024)throw Error('Keep total attachments under 2 MB.');documents.push(...added);renderFiles();}
        catch(err){UI.toast(err.message,'error');}
        finally{reading=false;controls.forEach(n=>n.disabled=false);}
      });renderFiles();}
    if(step===4){root.innerHTML='<h2>Everything look right?</h2><p class="small muted">Review your details before sending your application.</p><h3>'+UI.e(s.name)+'</h3>'+Views.formDetails(form)+'<div class="divider"></div><h3>Supporting documents</h3>'+documents.map(d=>'<div class="file-item">'+Icons('file')+'<div class="file-info"><strong class="small">'+UI.e(d.label)+'</strong><small style="display:block">'+UI.e(d.name)+' · '+UI.fileSize(d.size)+'</small></div></div>').join('')+'<label class="check" style="margin-top:1.4rem"><input id="declaration" type="checkbox" required> I confirm the details and documents are accurate.</label>';}
    UI.$('#wizard-back').onclick=()=>{if(step===2)form=UI.formData(UI.$('#wizard-form'));step--;render();};
    UI.$('#wizard-form').onsubmit=ev=>{ev.preventDefault();if(step===1&&!service()){UI.toast('Choose a service to continue.','error');return;}if(step===2)form=UI.formData(ev.target);if(step===3){if(reading)return;const missing=s.required_documents.filter(t=>!documents.some(d=>d.label===t));if(missing.length){UI.toast('Attach required documents: '+missing.join(', '),'error');return;}}if(step<4){step++;render();return;}UI.busy(UI.$('#wizard-next'),async()=>{const a=await API.applications.create({service_id:serviceId,form_data:form,documents});await Shell.refresh();UI.$('#page').innerHTML='<section class="card success-panel">'+Icons('approved')+'<div class="eyebrow">APPLICATION RECEIVED</div><h1 style="margin-top:.8rem">You’re on your way.</h1><p class="muted">Your '+UI.e(a.service_name.toLowerCase())+' request is with the department.</p><div class="success-reference" id="submitted-reference">'+UI.e(a.reference)+'</div><p class="small muted">Keep this reference number. You can follow every update on the tracking page.</p><div class="actions" style="justify-content:center"><button class="btn" id="print-ack">'+Icons('print')+'Print acknowledgment</button><a class="btn primary" href="citizen-application.html?id='+a.id+'">View application'+Icons('arrow')+'</a><a class="btn" href="track.html?ref='+encodeURIComponent(a.reference)+'">Track publicly</a></div></section>';UI.$('#print-ack').onclick=()=>UI.printApplication(a);});};
  }
  function renderFiles(){const s=service();UI.$('#file-list').innerHTML=documents.map((d,i)=>'<div class="file-item">'+Icons('file')+'<span class="file-info small">'+UI.e(d.name)+'<small style="display:block">'+UI.fileSize(d.size)+'</small></span><select class="control" aria-label="Document type for '+UI.e(d.name)+'" data-label="'+i+'">'+UI.options([...new Set([...s.required_documents,'Supporting document'])],d.label,null)+'</select><button type="button" class="btn ghost icon-only" data-remove="'+i+'" aria-label="Remove '+UI.e(d.name)+'">'+Icons('trash')+'</button></div>').join('');UI.$$('[data-label]').forEach(n=>n.onchange=()=>{documents[Number(n.dataset.label)].label=n.value;renderFiles();});UI.$$('[data-remove]').forEach(n=>n.onclick=()=>{documents.splice(Number(n.dataset.remove),1);renderFiles();});const missing=s.required_documents.filter(t=>!documents.some(d=>d.label===t));UI.$('#document-warning').innerHTML=missing.length?'<div class="alert warning">'+Icons('info')+'Still needed: '+UI.e(missing.join(', '))+'</div>':'<div class="alert">'+Icons('approved')+'All required document types are attached.</div>';}
  render();
});
