UI.run(async()=>{
  await Auth.guard([]);
  if(Auth.redirectIfSignedIn())return;
  await UI.initTheme();
  let role='citizen';
  const accounts={citizen:['citizen@demo.gov','citizen123'],officer:['officer@demo.gov','officer123'],admin:['admin@demo.gov','admin123']};
  UI.$('#app').innerHTML='<main class="auth-layout">'+Shell.authAside()+'<section class="auth-form-panel"><div class="auth-box"><div class="eyebrow">WELCOME TO CIVIC DESK</div><h1 style="margin-top:.7rem">Good to see you again.</h1><p>Sign in to pick up where you left off.</p><div class="tabs" role="tablist" aria-label="Sign in role">'+Object.keys(accounts).map(r=>'<button class="tab '+(r===role?'active':'')+'" role="tab" id="role-'+r+'" data-role="'+r+'" aria-selected="'+(r===role)+'">'+r[0].toUpperCase()+r.slice(1)+'</button>').join('')+'</div><form id="login-form">'+UI.field('Email address','email','email','','required autocomplete="username" placeholder="you@example.com"')+UI.field('Password','password','password','','required autocomplete="current-password" minlength="8"')+'<div id="login-error" class="field error" role="alert"></div><button class="btn primary full" type="submit">Sign in to your workspace'+Icons('arrow')+'</button></form><div class="demo-accounts"><div class="eyebrow">Try the demo · One click to fill</div>'+Object.entries(accounts).map(([r,a])=>'<div class="demo-account"><span>'+r[0].toUpperCase()+r.slice(1)+'<small>'+a[0]+' / '+a[1]+'</small></span><button class="btn sm" data-demo="'+r+'">Use '+r+'</button></div>').join('')+'</div><div class="auth-bottom"><span>New here? <a href="register.html">Create an account</a></span><button class="btn ghost icon-only" data-theme-toggle aria-label="Toggle color theme">'+Icons(UI.isDark()?'sun':'moon')+'</button></div><a class="small muted" href="index.html">← Back to public services</a></div></section></main>';
  function choose(r){role=r;UI.$$('[data-role]').forEach(b=>{b.classList.toggle('active',b.dataset.role===r);b.setAttribute('aria-selected',b.dataset.role===r);});UI.$('#login-error').textContent='';}
  UI.$$('[data-role]').forEach(b=>b.onclick=()=>choose(b.dataset.role));
  UI.$$('.tabs')[0].addEventListener('keydown',ev=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(ev.key)){ev.preventDefault();const roles=Object.keys(accounts),idx=roles.indexOf(role);choose(ev.key==='Home'?roles[0]:ev.key==='End'?roles[2]:roles[(idx+(ev.key==='ArrowRight'?1:2))%3]);UI.$('#role-'+role).focus();}});
  UI.$$('[data-demo]').forEach(b=>b.onclick=()=>{choose(b.dataset.demo);UI.$('#email').value=accounts[role][0];UI.$('#password').value=accounts[role][1];UI.$('#login-form button[type=submit]').focus();});
  UI.$('#login-form').onsubmit=async ev=>{ev.preventDefault();const button=UI.$('button[type=submit]',ev.target);await UI.busy(button,async()=>{try{const u=await Auth.login(UI.$('#email').value,UI.$('#password').value,role);location.href=Auth.homeFor(u.role);}catch(err){UI.$('#login-error').textContent=err.message;UI.$('#login-error').classList.add('text-danger');}});};
});

