UI.run(async()=>{
  await Auth.guard([]);
  if(Auth.redirectIfSignedIn())return;
  await UI.initTheme();
  UI.$('#app').innerHTML='<main class="auth-layout">'+Shell.authAside()+'<section class="auth-form-panel"><div class="auth-box"><div class="eyebrow">YOUR SERVICES START HERE</div><h1 style="margin-top:.7rem">One account. More access.</h1><p>Create your citizen account to apply and track progress.</p><form id="register-form"><div class="form-grid">'+UI.field('Full name','name','text','','required minlength="3" maxlength="100" autocomplete="name"')+UI.field('Mobile number','phone','tel','','required pattern="[0-9]{10,15}" autocomplete="tel"')+'</div>'+UI.field('Email address','email','email','','required autocomplete="email"')+UI.field('Residential address','address','text','','required minlength="8" maxlength="300" autocomplete="street-address"')+UI.field('Password','password','password','','required minlength="8" maxlength="100" autocomplete="new-password" aria-describedby="strength-label"')+'<div class="strength"><span id="strength-bar" style="width:0"></span></div><p class="small muted" id="strength-label" aria-live="polite">Use at least 8 characters, letters and a number.</p>'+UI.field('Confirm password','confirm-password','password','','required autocomplete="new-password"')+'<div id="validation-message" class="small text-danger" aria-live="polite"></div><label class="check" style="margin:1rem 0"><input type="checkbox" id="consent" required> I understand this is a college demonstration portal.</label><button class="btn primary full" type="submit">Create citizen account'+Icons('arrow')+'</button></form><div class="auth-bottom"><span>Already registered? <a href="login.html">Sign in</a></span><button class="btn ghost icon-only" data-theme-toggle aria-label="Toggle color theme">'+Icons(UI.isDark()?'sun':'moon')+'</button></div></div></section></main>';
  const pass=UI.$('#password'),confirm=UI.$('#confirm-password');
  function validate(){const p=pass.value,score=[p.length>=8,/[a-z]/.test(p)&&/[A-Z]/.test(p),/[0-9]/.test(p),/[^A-Za-z0-9]/.test(p)].filter(Boolean).length;UI.$('#strength-bar').style.width=(score*25)+'%';UI.$('#strength-label').textContent=['Use at least 8 characters, letters and a number.','Weak — add length and variety.','Fair — mixed case or a symbol will help.','Good password strength.','Strong password.'][score];pass.setCustomValidity(p.length&&(!/[A-Za-z]/.test(p)||!/[0-9]/.test(p))?'Include letters and a number.':'');confirm.setCustomValidity(confirm.value&&confirm.value!==p?'Passwords do not match.':'');const invalid=UI.$$('input',UI.$('#register-form')).find(n=>n.value&&!n.validity.valid);UI.$('#validation-message').textContent=invalid?invalid.validationMessage:'';}
  UI.$('#register-form').addEventListener('input',validate);
  UI.$('#register-form').onsubmit=ev=>{ev.preventDefault();UI.busy(UI.$('button[type=submit]',ev.target),async()=>{await Auth.register(UI.formData(ev.target));location.href='citizen-dashboard.html';});};
});

