UI.run(async()=>{
  await Auth.guard([]);
  await Shell.publicPage();
  const reference=new URLSearchParams(location.search).get('ref')||'';
  UI.$('#page').innerHTML='<section class="track-box"><div class="track-heading"><div class="eyebrow">EVERY STEP, IN THE OPEN</div><h1 style="margin-top:.7rem">Where does your application stand?</h1><p class="muted">Enter your reference number to see its latest status.</p></div><form class="card" id="track-form"><div class="filters">'+UI.field('Application reference','reference','text',reference,'required placeholder="GOV-2026-000420" pattern="GOV-[0-9]{4}-[0-9]{6}" style="text-transform:uppercase"')+'<button type="submit" class="btn primary" style="align-self:flex-end">'+Icons('search')+'Track application</button></div><small>Find this number on your acknowledgment or in My applications.</small></form><div id="track-result" style="margin-top:1.5rem"></div></section>';
  async function track(){const target=UI.$('#track-result');try{const a=await API.applications.track(UI.$('#reference').value);target.innerHTML='<div class="card stack"><div class="row between"><div><div class="eyebrow">APPLICATION STATUS</div><h2 style="margin:.4rem 0">'+UI.e(a.service_name)+'</h2><span class="mono">'+UI.e(a.reference)+'</span></div>'+UI.badge(a.status)+'</div><div class="alert">'+Icons('shield')+'Applicant details are masked to protect privacy.</div><dl class="details"><dt>Applicant</dt><dd data-masked-name>'+UI.e(a.applicant_name)+'</dd><dt>Email</dt><dd data-masked-email>'+UI.e(a.applicant_email)+'</dd><dt>Department</dt><dd>'+UI.e(a.department_name)+'</dd><dt>Submitted</dt><dd>'+UI.e(UI.date(a.created_at))+'</dd><dt>Service timeline</dt><dd>'+a.sla_days+' days'+(a.isOverdue?' · <span class="text-danger">Past timeline</span>':'')+'</dd></dl><h2>Application journey</h2>'+UI.timeline(a.logs)+'</div>';}catch(err){target.innerHTML='<div class="alert error" role="alert">'+Icons('info')+UI.e(err.message)+'</div>';}}
  UI.$('#track-form').onsubmit=ev=>{ev.preventDefault();UI.busy(UI.$('button[type=submit]',ev.target),track);};if(reference)await track();
});

