'use strict';
const express=require('express'),{pool,rows,transaction,normalize}=require('./db.cjs'),S=require('./security.cjs'),V=require('./validation.cjs'),R=require('./repository.cjs'),P=require('./passwords.cjs'),Q=require('./portal-repository.cjs'),Auth=require('./identity/auth.cjs');
const all=S.allow('citizen','officer','admin','verification_agent'),portal=S.allow('citizen','officer','admin'),staff=S.allow('officer','admin'),admin=S.allow('admin'),citizen=S.allow('citizen');
function own(req,id){if(Number(id)!==req.user.id)V.fail('You can only access your own account.',403);}
function routes(){const api=express.Router();api.use(express.json({limit:'15mb',strict:true}));const authRate=S.rateLimit(30,15*60000),accountRate=S.rateLimit(10,15*60000,r=>r.ip+':'+String(r.body?.email||'').toLowerCase().slice(0,150));
 api.get('/auth/me',(req,res)=>res.json(Q.user(req.user)));
 api.post('/auth/login',authRate,accountRate,async(req,res)=>res.json(await Auth.login(req,res,true)));
 api.post('/auth/challenge',authRate,async(req,res)=>res.json(await Auth.challenge(req,res)));
 api.post('/auth/logout',async(req,res)=>res.json(await S.logout(req,res)));
 api.post('/auth/forgot-password',authRate,async(req,res)=>res.json(await Auth.forgot(req)));
 api.post('/auth/reset-password',authRate,async(req,res)=>res.json(await Auth.reset(req)));
 api.post('/auth/register',authRate,async(req,res)=>{const d=V.fields(req.body,['full_name','email','password','phone','address','city','id_last4']);const hash=await P.hash(V.password(d.password));const u=await transaction(async c=>{const [r]=await c.execute("INSERT INTO users(name,email,password_hash,phone,address,city,role) VALUES(?,?,?,?,?,?,'citizen')",[V.text(d.full_name,'Full name',3,100),V.email(d.email),hash,V.phone(d.phone),V.text(d.address,'Address',8,300),String(d.city||'').slice(0,100)]);const u=await R.one(c,'users',r.insertId);await R.notify(c,u.id,null,'Welcome to AMAP','Your account is ready to apply for services.');await S.issueSession(req,res,u,c);return u;});res.status(201).json({user:Q.user(u)});});
 api.get('/departments',async(req,res)=>res.json(await R.departments.list()));
 api.get('/departments/:id',async(req,res)=>res.json(await R.one(pool,'departments',req.params.id)));
 async function department(req,res){const d=req.body;const name=V.text(d.name,'Department name',3,100),code=V.text(d.code,'Code',2,16).toUpperCase();if(!/^[A-Z0-9_-]+$/.test(code))V.fail('Use a simple department code.');const values=[name,code,String(d.description||'').slice(0,500),String(d.icon||'building').slice(0,40),String(d.head||'').slice(0,100),String(d.email||'').slice(0,150),String(d.phone||'').slice(0,20)];let id=req.params.id;await R.write(req.user,async c=>{if(id){await R.one(c,'departments',id,true);await c.execute('UPDATE departments SET name=?,code=?,description=?,icon=?,head=?,email=?,phone=? WHERE id=?',[...values,V.id(id)]);}else{const [r]=await c.execute('INSERT INTO departments(name,code,description,icon,head,email,phone) VALUES(?,?,?,?,?,?,?)',values);id=r.insertId;}});res.json(await R.one(pool,'departments',id));}
 api.post('/departments',admin,department);api.put('/departments/:id',admin,department);api.delete('/departments/:id',admin,async(req,res)=>res.json(await R.departments.remove(req.params.id,req.user)));
 async function services(req,res){let list=(await R.services.list(req.params.id?{department_id:req.params.id}:req.query.department_id?{department_id:req.query.department_id}:{})).map(Q.service);if(req.query.q)list=list.filter(s=>(s.name+' '+s.code).toLowerCase().includes(req.query.q.toLowerCase()));if(req.query.active)list=list.filter(s=>s.is_active===!!Number(req.query.active));res.json(Q.page(Q.sort(list,{direction:'asc',...req.query},'name'),req.query));}
 api.get('/services',services);api.get('/departments/:id/services',services);api.get('/services/:id',async(req,res)=>res.json(Q.service(await R.one(pool,'services',req.params.id))));
 async function saveService(req,res){let id=req.params.id;await R.write(req.user,async c=>{const old=id?Q.service(await R.one(c,'services',id,true)):{},d={...old,...req.body},department=await R.one(c,'departments',d.department_id);if(!department.active)V.fail('Choose an active department.');if(id&&old.department_id!==Number(d.department_id)&&(await rows(c,'SELECT id FROM applications WHERE service_id=? LIMIT 1',[id])).length)V.fail('A service with history cannot move departments.');if(!Array.isArray(d.docs)||!d.docs.length||d.docs.length>20)V.fail('Choose required document types.');const docs=d.docs.map(x=>V.text(x,'Document type',2,100)),fee=Number(d.fee),sla=Number(d.sla_days);if(!Number.isFinite(fee)||fee<0||fee>100000||!Number.isInteger(sla)||sla<1||sla>365)V.fail('Enter a valid fee and service timeline.');const values=[Number(d.department_id),V.text(d.name,'Name',3,100),V.text(d.code,'Code',2,32),String(d.description||'').slice(0,1000),fee,sla,JSON.stringify(docs),!!d.is_active];if(id)await c.execute('UPDATE services SET department_id=?,name=?,code=?,description=?,fee=?,sla_days=?,required_documents=?,active=? WHERE id=?',[...values,V.id(id)]);else{const [r]=await c.execute('INSERT INTO services(department_id,name,code,description,fee,sla_days,required_documents,active) VALUES(?,?,?,?,?,?,?,?)',values);id=r.insertId;}});res.json(Q.service(await R.one(pool,'services',id)));}
 api.post('/services',admin,saveService);api.put('/services/:id',admin,saveService);api.delete('/services/:id',admin,async(req,res)=>res.json(await R.services.remove(req.params.id,req.user)));
 api.get('/applications/track/examples',async(req,res)=>{const list=await rows(pool,"SELECT a.reference ref FROM applications a JOIN users u ON u.id=a.citizen_id WHERE u.email='citizen@demo.gov' ORDER BY a.created_at DESC LIMIT 3");res.json(list);});
 api.get('/applications/track/:ref',S.rateLimit(40,15*60000),async(req,res)=>{const t=await R.track(req.params.ref);res.json({ref:t.reference,status:t.status,statusLabel:Q.expand({...t,priority:'normal',created_at:t.created_at}).statusLabel,service:{name:t.service_name},department:{name:t.department_name},submitted_at:t.created_at,decided_at:t.decided_at,sla_days:t.sla_days,isOverdue:t.isOverdue,isOpen:V.OPEN.includes(t.status),citizen:{full_name:t.applicant_name,email:t.applicant_email},logs:t.logs});});
 api.get('/applications',portal,async(req,res)=>res.json(await Q.applications(req.query,req.user)));
 api.post('/applications',citizen,async(req,res)=>res.status(201).json(await Q.create(req.body,req.user)));
 api.patch('/applications/assign',staff,async(req,res)=>{const data=await R.assign({ids:req.body.ids,officer_id:req.body.officer_id},req.user);res.json(await Promise.all(data.map(a=>Q.application(a.id,req.user))));});
 api.get('/applications/:id',portal,async(req,res)=>res.json(await Q.application(req.params.id,req.user)));
 api.get('/applications/:id/logs',portal,async(req,res)=>res.json(await Q.logs(req.params.id,req.user)));
 api.get('/applications/:id/documents',portal,async(req,res)=>res.json(await Q.documents(req.params.id,req.user)));
 api.patch('/applications/:id/status',portal,async(req,res)=>{const d=V.fields(req.body,['status','remarks','extra']),extra=d.extra||{};V.fields(extra,['department_id','officer_id','documents']);await R.transition(req.params.id,{status:d.status,remarks:d.remarks,...extra,...(extra.documents?{documents:Q.docsInput(extra.documents)}:{})},req.user,{portal:true});const a=await Q.application(req.params.id,{role:'admin'});res.json(a);});
 api.post('/applications/:id/documents',citizen,async(req,res)=>{await R.write(req.user,async c=>{const a=await Q.application(req.params.id,req.user,c);if(!['SUBMITTED','NEEDS_INFO'].includes(a.status))V.fail('Documents can only be added before review or when requested.',409);const [size]=await rows(c,'SELECT COALESCE(SUM(size),0) total FROM documents WHERE application_id=?',[a.id]);const docs=require('./uploads.cjs').documents(Q.docsInput(req.body.documents),Number(size.total),{maxFile:5242880,maxTotal:10485760});for(const d of docs)await c.execute('INSERT INTO documents(application_id,label,name,mime,size,content) VALUES(?,?,?,?,?,?)',[a.id,d.label,d.name,d.mime,d.size,d.content]);});res.json(await Q.documents(req.params.id,req.user));});
 api.patch('/documents/:id',staff,async(req,res)=>{if(typeof req.body.verified!=='boolean')V.fail('Choose a document verification status.');await R.write(req.user,async c=>{const d=await R.one(c,'documents',req.params.id,true);const a=await Q.application(d.application_id,req.user,c);if(!a.isOpen)V.fail('Closed files cannot be changed.',409);await c.execute('UPDATE documents SET verified=?,verified_by=? WHERE id=?',[req.body.verified,req.user.id,d.id]);await c.execute('UPDATE applications SET last_actor_id=?,last_remarks=? WHERE id=?',[req.user.id,'Document verification updated: '+d.label,a.id]);});res.json({ok:true});});
 api.get('/users',staff,async(req,res)=>res.json(await Q.users(req.query,req.user)));
 api.get('/users/:id',all,async(req,res)=>{if(req.user.role!=='admin')own(req,req.params.id);res.json(Q.user(await R.one(pool,'users',req.params.id)));});
 api.post('/users',admin,async(req,res)=>{const d=req.body;res.json(Q.user(await R.users.create({name:d.full_name,email:d.email,role:String(d.role).toLowerCase(),department_id:d.department_id,password:d.password,phone:d.phone||undefined},req.user)));});
 async function profile(req,res){const id=V.id(req.params.id);if(req.user.role!=='admin')own(req,id);const d=req.body,old=await R.one(pool,'users',id);if(d.role&&d.role!==old.role.toUpperCase())V.fail('Create a separate staff account to change its role.');const update={};for(const [from,to] of [['full_name','name'],['phone','phone'],['address','address']])if(d[from]!=null&&d[from]!=='')update[to]=d[from];if(req.user.role==='admin'){if(d.status)update.active=d.status==='ACTIVE';if(d.department_id&&old.role==='officer')update.department_id=d.department_id;}await R.users.update(id,update,req.user);if('city'in d)await pool.execute('UPDATE users SET city=? WHERE id=?',[String(d.city).slice(0,100),id]);if('id_last4'in d&&String(d.id_last4)&&!/^\d{4}$/.test(d.id_last4))V.fail('Enter four digits.');if('id_last4'in d)await pool.execute('UPDATE users SET id_last4=? WHERE id=?',[String(d.id_last4).slice(0,4),id]);res.json(Q.user(await R.one(pool,'users',id)));}
 api.patch('/users/:id',all,profile);api.put('/users/:id',admin,profile);api.patch('/users/:id/status',admin,profile);
 api.patch('/users/:id/password',all,authRate,async(req,res)=>{own(req,req.params.id);const old=await R.one(pool,'users',req.user.id);if(!await P.verify(req.body.current,old.password_hash))V.fail('Current password is incorrect.');const [m]=await rows(pool,'SELECT enabled FROM mfa_methods WHERE user_id=?',[req.user.id]);if(m?.enabled)Auth.recent(req);const hash=await P.hash(V.password(req.body.next));await transaction(async c=>{await c.execute('UPDATE users SET password_hash=? WHERE id=?',[hash,req.user.id]);await c.execute('DELETE FROM sessions WHERE user_id=? AND token_hash<>?',[req.user.id,S.digest(req.sessionToken)]);});res.json({ok:true});});
 api.get('/grievances',portal,async(req,res)=>res.json(await Q.grievances(req.query,req.user)));
 api.post('/grievances',citizen,async(req,res)=>{const d=req.body;const [s]=await rows(pool,'SELECT id FROM services WHERE department_id=? AND active=TRUE ORDER BY id LIMIT 1',[V.id(d.department_id)]);if(!s)V.fail('Choose a department with an active service.');const g=await R.grievances.create({service_id:s.id,subject:d.subject,description:d.description,category:d.category,location:d.location,priority:String(d.priority||'NORMAL').toLowerCase()},req.user);res.json({...g,ref:g.reference});});
 api.patch('/grievances/:id',staff,async(req,res)=>{if(req.body.status==='CLOSED'){await R.write(req.user,async c=>{const g=await R.one(c,'grievances',req.params.id,true);R.access(g,req.user);if(g.status!=='RESOLVED')V.fail('Resolve the grievance before closing it.',409);await c.execute("UPDATE grievances SET status='CLOSED',last_actor_id=? WHERE id=?",[req.user.id,g.id]);});res.json({ok:true});}else res.json(await R.grievances.update(req.params.id,{status:req.body.status,resolution:req.body.resolution},req.user));});
 api.get('/grievances/:id/logs',portal,async(req,res)=>{const g=await R.one(pool,'grievances',req.params.id);R.access(g,req.user);res.json(await R.logs(pool,'grievance_id',g.id));});
 for(const part of ['overview','monthly','daily','status','departments','services','officers','decisions','processing','activity','grievances','sla','users'])api.get('/analytics/'+part,part==='users'?admin:portal,async(req,res)=>res.json(await Q.analytics(part,req.query,req.user)));
 api.get('/users/:id/notifications',all,async(req,res)=>{own(req,req.params.id);res.json((await R.notifications.list(req.user)).map(n=>({...n,is_read:n.read,link:n.link||(n.application_id?'/citizen/applications/'+n.application_id:'/security')})));});
 api.get('/users/:id/notifications/unread',all,async(req,res)=>{own(req,req.params.id);const [n]=await rows(pool,'SELECT COUNT(*) n FROM notifications WHERE user_id=? AND `read`=FALSE',[req.user.id]);res.json(Number(n.n));});
 api.post('/users/:id/notifications/read',all,async(req,res)=>{own(req,req.params.id);res.json(await R.notifications.read('all',req.user));});
 const prefKeys=['theme','text','contrast','language'];
 api.get('/preferences/:key',async(req,res)=>{if(!prefKeys.includes(req.params.key))V.fail('Unknown preference.');const [p]=req.user?await rows(pool,'SELECT * FROM preferences WHERE user_id=?',[req.user.id]):[];res.json(p?.settings?.[req.params.key]??(req.params.key==='theme'?p?.theme:null)??req.cookies['amap-pref-'+req.params.key]??null);});
 api.put('/preferences/:key',async(req,res)=>{const key=req.params.key;if(!prefKeys.includes(key))V.fail('Unknown preference.');const value=V.text(String(req.body.value),'Preference',1,30);if(req.user)await transaction(async c=>{await c.execute('INSERT IGNORE INTO preferences(user_id,settings) VALUES(?,JSON_OBJECT())',[req.user.id]);const [p]=await rows(c,'SELECT settings FROM preferences WHERE user_id=? FOR UPDATE',[req.user.id]);await c.execute('UPDATE preferences SET settings=? WHERE user_id=?',[JSON.stringify({...p.settings,[key]:value}),req.user.id]);});res.cookie('amap-pref-'+key,value,{...S.cookieOptions,maxAge:365*86400000});res.json(value);});
 api.get('/demo/storage',(req,res)=>res.json({persistent:true,backend:'mysql'}));
 api.use('/security',require('./identity/security-routes.cjs').routes());
 api.use('/identity',require('./identity/routes.cjs').routes());
 api.use('/verification',require('./identity/appointments.cjs').routes());
 return api;
}
module.exports={routes};
