/* Small SVG charts. Every color is resolved from CSS variables on each draw. */
(function(){
  'use strict';
  const registry=new Map(),e=v=>UI.e(v),NS='http://www.w3.org/2000/svg';let serial=0,tip;
  const color=(variable='--chart-1')=>getComputedStyle(document.documentElement).getPropertyValue(variable).trim();
  const statusColor=s=>'--'+String(s).toLowerCase().replace(/_/g,'-');
  function palette(i){return '--chart-'+(i%8+1);}
  function text(x,y,value,anchor='start',size=10,fill='--muted',extra=''){return '<text x="'+x+'" y="'+y+'" text-anchor="'+anchor+'" fill="'+color(fill)+'" font-size="'+size+'" font-family="Segoe UI,system-ui,sans-serif" '+extra+'>'+e(value)+'</text>';}
  function mark(content,label){return '<g tabindex="0" role="img" aria-label="'+e(label)+'" data-tip="'+e(label)+'">'+content+'<title>'+e(label)+'</title></g>';}
  function tooltip(ev){const n=ev.target.closest('[data-tip]');if(!n)return;if(!tip){tip=document.createElement('div');tip.className='chart-tooltip';tip.setAttribute('role','tooltip');document.body.append(tip);}tip.textContent=n.dataset.tip;tip.hidden=false;const r=n.getBoundingClientRect();const x=ev.clientX||r.left+r.width/2,y=ev.clientY||r.top;tip.style.left=Math.max(8,Math.min(innerWidth-tip.offsetWidth-10,x+12))+'px';tip.style.top=Math.max(8,y-tip.offsetHeight-12)+'px';}
  function hide(){if(tip)tip.hidden=true;}
  function mount(target,type,data,opts={}){registry.forEach((chart,node)=>{if(!node.isConnected){chart.observer?.disconnect();registry.delete(node);}});const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;let chart=registry.get(root);if(!chart){chart={root,id:++serial,width:0};registry.set(root,chart);root.addEventListener('pointermove',tooltip);root.addEventListener('focusin',tooltip);root.addEventListener('pointerleave',hide);root.addEventListener('focusout',hide);if(window.ResizeObserver){chart.observer=new ResizeObserver(entries=>{const w=entries[0].contentRect.width;if(Math.abs(w-chart.width)>1){chart.width=w;draw(chart);}});chart.observer.observe(root);}}Object.assign(chart,{type,data,opts});draw(chart);return chart;}
  function draw(c){const {root,type,data,opts}=c;if(!root.isConnected)return;const width=Math.max(root.clientWidth||300,200),height=root.clientHeight||230;c.width=root.clientWidth;let body='';const rows=Array.isArray(data)?data:[];
    if(type==='donut'){
      const total=rows.reduce((s,d)=>s+Math.max(0,Number(d.value)||0),0),cx=width/2,cy=height/2,r=Math.min(width,height)*.34,stroke=Math.min(27,r*.32),circ=2*Math.PI*r;body='<circle cx="'+cx+'" cy="'+cy+'" r="'+r+'" fill="none" stroke="'+color('--surface-3')+'" stroke-width="'+stroke+'"/>';let offset=0;
      rows.forEach((d,i)=>{const value=Math.max(0,Number(d.value)||0),length=total?value/total*circ:0;if(value)body+=mark('<circle cx="'+cx+'" cy="'+cy+'" r="'+r+'" fill="none" stroke="'+color(d.color|| (d.status?statusColor(d.status):palette(i)))+'" stroke-width="'+stroke+'" stroke-dasharray="'+Math.max(0,length-3)+' '+(circ-Math.max(0,length-3))+'" stroke-dashoffset="'+(-offset)+'" transform="rotate(-90 '+cx+' '+cy+')"/>',(UI.labels[d.label]||d.label)+': '+value+' ('+(value/total*100).toFixed(1)+'%)');offset+=length;});body+=text(cx,cy+5,opts.center||total,'middle',30,'--text','font-weight="650"')+text(cx,cy+26,opts.label||'applications','middle',10);
    }else if(type==='gauge'){
      const value=Math.max(0,Math.min(100,Number(data.value)||0)),cx=width/2,cy=height*.73,r=Math.min(width*.4,height*.57),len=Math.PI*r,path='M '+(cx-r)+' '+cy+' A '+r+' '+r+' 0 0 1 '+(cx+r)+' '+cy;body='<path d="'+path+'" fill="none" stroke="'+color('--surface-3')+'" stroke-width="18" stroke-linecap="round"/>'+mark('<path d="'+path+'" fill="none" stroke="'+color('--chart-1')+'" stroke-width="18" stroke-linecap="round" stroke-dasharray="'+len*value/100+' '+len+'"/>',value.toFixed(1)+'% '+(opts.label||'approval rate'))+text(cx,cy-8,value.toFixed(1)+'%','middle',30,'--text','font-weight="650"')+text(cx,cy+14,opts.label||'of decided applications','middle',10)+text(cx-r,cy+28,'0%','middle',9)+text(cx+r,cy+28,'100%','middle',9);
    }else if(type==='horizontal'){
      const left=Math.min(150,width*.43),right=35,top=9,rowH=(height-18)/Math.max(rows.length,1),max=Math.max(1,...rows.map(d=>Number(d.value)||0));rows.forEach((d,i)=>{const y=top+i*rowH;body+=text(left-10,y+rowH*.55,String(d.label).length>24?String(d.label).slice(0,23)+'…':d.label,'end',9)+mark('<rect x="'+left+'" y="'+(y+rowH*.22)+'" width="'+Math.max(0,(width-left-right)*(Number(d.value)||0)/max)+'" height="'+Math.max(4,rowH*.43)+'" rx="3" fill="'+color(d.color||palette(i))+'"/>',d.label+': '+d.value)+text(width-5,y+rowH*.55,d.value,'end',10,'--text');});
    }else{
      const spark=type==='sparkline',left=spark?2:34,right=12,top=12,bottom=spark?3:30,w=width-left-right,h=height-top-bottom,series=opts.series||[{key:'value',label:opts.label||'Applications',color:'--chart-1'}];
      const stacked=type==='stacked';const max=Math.max(1,...rows.map(d=>stacked?series.reduce((s,ser)=>s+(Number(d[ser.key])||0),0):Math.max(...series.map(ser=>Number(d[ser.key])||0))));const ceiling=Math.max(1,Math.ceil(max/4)*4);const y=v=>top+h-(v/ceiling)*h,x=i=>left+(rows.length<2?w/2:i*w/(rows.length-1));
      if(!spark){for(let i=0;i<=4;i++){const yy=top+i*h/4;body+='<line x1="'+left+'" y1="'+yy+'" x2="'+(width-right)+'" y2="'+yy+'" stroke="'+color('--border')+'" stroke-dasharray="3 4"/>'+text(left-8,yy+3,Math.round(ceiling*(1-i/4)),'end',9);} }
      if(['area','line','sparkline'].includes(type)){
        series.forEach((ser,si)=>{const points=rows.map((d,i)=>[x(i),y(Number(d[ser.key])||0)]),line=points.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' '),fill=color(ser.color||palette(si));if(type==='area'&&points.length){const id='chart-gradient-'+c.id+'-'+si;body+='<defs><linearGradient id="'+id+'" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="'+fill+'" stop-opacity=".23"/><stop offset="100%" stop-color="'+fill+'" stop-opacity=".01"/></linearGradient></defs><path d="'+line+' L '+x(rows.length-1)+' '+(top+h)+' L '+x(0)+' '+(top+h)+' Z" fill="url(#'+id+')"/>';}body+='<path d="'+line+'" fill="none" stroke="'+fill+'" stroke-width="2.3" stroke-linejoin="round" stroke-linecap="round"/>';points.forEach((p,i)=>body+=mark('<circle cx="'+p[0]+'" cy="'+p[1]+'" r="5" fill="'+fill+'" fill-opacity=".08" stroke="'+fill+'" stroke-opacity=".4"/>',rows[i].label+' · '+ser.label+': '+(rows[i][ser.key]||0)));});
      }else{
        const slot=w/Math.max(rows.length,1),groupWidth=slot*.64;rows.forEach((d,i)=>{let cumulative=0;series.forEach((ser,j)=>{const value=Number(d[ser.key])||0,barW=stacked?groupWidth:groupWidth/series.length,bx=left+i*slot+(slot-groupWidth)/2+(stacked?0:j*barW),by=y(value+(stacked?cumulative:0));body+=mark('<rect x="'+bx+'" y="'+by+'" width="'+Math.max(1,barW-2)+'" height="'+Math.max(0,value/ceiling*h)+'" rx="2" fill="'+color(ser.color||palette(j))+'"/>',d.label+' · '+ser.label+': '+value);cumulative+=value;});});
      }
      if(!spark){const step=Math.max(1,Math.ceil(rows.length/(width<400?6:12)));rows.forEach((d,i)=>{if(i%step===0){const xx=['grouped','stacked'].includes(type)?left+(i+.5)*w/rows.length:x(i);body+=text(xx,height-8,d.label,'middle',9);}});}
    }
    root.innerHTML='<svg xmlns="'+NS+'" viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+e(opts.title||opts.label||type+' chart')+'">'+body+'</svg>';
  }
  function legend(items){return '<div class="legend">'+items.map((d,i)=>'<span><i style="background:var('+e(d.color||(d.status?statusColor(d.status):palette(i)))+')"></i>'+e(UI.labels[d.label]||d.label)+(d.value!==undefined?' <b>'+e(d.value)+'</b>':'')+'</span>').join('')+'</div>';}
  window.Charts={area:(t,d,o)=>mount(t,'area',d,o),line:(t,d,o)=>mount(t,'line',d,o),groupedBars:(t,d,o)=>mount(t,'grouped',d,o),stackedBars:(t,d,o)=>mount(t,'stacked',d,o),horizontalBars:(t,d,o)=>mount(t,'horizontal',d,o),donut:(t,d,o)=>mount(t,'donut',d,o),gauge:(t,v,o)=>mount(t,'gauge',{value:v},o),sparkline:(t,d,o)=>mount(t,'sparkline',d,o),legend,statusColor,redrawAll(){registry.forEach((c,r)=>{if(!r.isConnected){c.observer?.disconnect();registry.delete(r);}else draw(c);});}};
})();
