(function () {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s), $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const e = v => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels = {SUBMITTED:'Submitted',UNDER_REVIEW:'Under review',NEEDS_INFO:'Needs information',FORWARDED:'Forwarded',APPROVED:'Approved',REJECTED:'Rejected',WITHDRAWN:'Withdrawn',OPEN:'Open',IN_PROGRESS:'In progress',RESOLVED:'Resolved'};
  const statusIcons = {SUBMITTED:'submitted',UNDER_REVIEW:'review',NEEDS_INFO:'info',FORWARDED:'forward',APPROVED:'approved',REJECTED:'rejected',WITHDRAWN:'withdrawn',OPEN:'grievance',IN_PROGRESS:'review',RESOLVED:'approved'};
  const date = (v, time = false) => v ? new Date(v).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',...(time ? {hour:'2-digit',minute:'2-digit'} : {})}) : '—';
  const initials = s => String(s || '?').trim().split(/\s+/).map(v=>v[0]).slice(0,2).join('').toUpperCase();
  function relative(v) { const days = Math.floor((Date.now()-new Date(v))/86400000); return days < 0 ? date(v) : days===0 ? 'Today' : days===1 ? 'Yesterday' : days < 30 ? days+' days ago' : date(v); }
  function el(tag, props={}, children=[]) { const n=document.createElement(tag); Object.entries(props).forEach(([k,v])=>{if(k==='text')n.textContent=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else n.setAttribute(k,v);}); (Array.isArray(children)?children:[children]).forEach(c=>n.append(c instanceof Node?c:document.createTextNode(String(c)))); return n; }
  function on(root,event,selector,fn) { root.addEventListener(event, ev=>{const target=ev.target.closest(selector);if(target&&root.contains(target))fn(ev,target);}); }
  function toast(message,type='success') { let region=$('#toasts');if(!region){region=el('div',{id:'toasts',class:'toast-region','aria-live':'polite'});document.body.append(region);} const t=el('div',{class:'toast '+type,role:type==='error'?'alert':'status'});t.innerHTML=Icons(type==='error'?'info':'approved');t.append(el('span',{text:message}));const close=el('button',{class:'btn ghost icon-only','aria-label':'Dismiss notification',onclick:()=>t.remove()});close.innerHTML=Icons('close');t.append(close);region.append(t);setTimeout(()=>t.remove(),6500); }
  function modal(title,html,options={}) { const d=el('dialog',{'aria-label':title}); d.innerHTML='<div class="modal-head"><h2>'+e(title)+'</h2><button class="btn ghost icon-only" data-close aria-label="Close dialog">'+Icons('close')+'</button></div>'+html;document.body.append(d);const previous=document.activeElement; const close=()=>{d.close();d.remove();previous?.focus();};$('[data-close]',d).onclick=close;d.addEventListener('cancel',ev=>{ev.preventDefault();close();});d.addEventListener('click',ev=>{if(ev.target===d){const r=d.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)close();}}); d.addEventListener('close',()=>{options.onClose?.();d.remove();});d.showModal();return {element:d,close}; }
  function confirm(title,message,ok='Confirm') { return new Promise(resolve=>{let done=false;const finish=v=>{if(!done){done=true;resolve(v);}m.close();};const m=modal(title,'<p>'+e(message)+'</p><div class="modal-actions"><button class="btn" data-cancel>Cancel</button><button class="btn primary" data-confirm>'+e(ok)+'</button></div>',{onClose:()=>{if(!done){done=true;resolve(false);}}});$('[data-cancel]',m.element).onclick=()=>finish(false);$('[data-confirm]',m.element).onclick=()=>finish(true);}); }
  function badge(status) { return '<span class="badge" data-status="'+e(status)+'">'+Icons(statusIcons[status]||'info')+e(labels[status]||status)+'</span>'; }
  function timeline(logs) { if(!logs.length)return empty('No activity yet','Activity will appear here.');return '<ol class="timeline">'+[...logs].sort((a,b)=>b.created_at.localeCompare(a.created_at)||(Number(b.id)||0)-(Number(a.id)||0)).map(l=>'<li data-status="'+e(l.to_status||l.status)+'"><span class="timeline-dot">'+Icons(statusIcons[l.to_status||l.status]||'activity')+'</span><strong>'+e(l.title||labels[l.to_status||l.status]||'Activity')+'</strong><p>'+e(l.remarks||l.message||'')+'</p><time datetime="'+e(l.created_at)+'">'+e(date(l.created_at,true))+(l.actor_name?' · '+e(l.actor_name):'')+'</time></li>').join('')+'</ol>'; }
  function empty(title='Nothing to show',message='Try adjusting your filters.',action='') { return '<div class="empty">'+Icons('inbox')+'<h3>'+e(title)+'</h3><p>'+e(message)+'</p>'+action+'</div>'; }
  function stat(label,value,icon='chart',note='From stored application records') { return '<div class="card stat"><div class="stat-top"><span>'+e(label)+'</span>'+Icons(icon)+'</div><strong>'+e(value)+'</strong><small>'+e(note)+'</small></div>'; }
  function options(rows,selected='',first='All') { return (first!==null?'<option value="">'+e(first)+'</option>':'')+rows.map(r=>{const id=typeof r==='object'?r.id:r;const name=typeof r==='object'?r.name:(labels[r]||r);return '<option value="'+e(id)+'"'+(String(id)===String(selected)?' selected':'')+'>'+e(name)+'</option>';}).join(''); }
  function field(label,name,type='text',value='',extra='') { return '<div class="field"><label for="'+e(name)+'">'+e(label)+'</label><input id="'+e(name)+'" name="'+e(name)+'" type="'+e(type)+'" value="'+e(value)+'" '+extra+'></div>'; }
  function select(label,name,rows,value='',first='All',extra='') { return '<div class="field"><label for="'+e(name)+'">'+e(label)+'</label><select id="'+e(name)+'" name="'+e(name)+'" '+extra+'>'+options(rows,value,first)+'</select></div>'; }
  function table(target,columns,rows,opts={}) { const root=typeof target==='string'?$(target):target;let page=1;const size=opts.pageSize||8;const selected=opts.selected||new Set();function draw(){page=Math.max(1,Math.min(page,Math.ceil(rows.length/size)||1));const slice=rows.slice((page-1)*size,page*size);root.innerHTML=rows.length?'<div class="table-wrap"><table><caption class="sr-only">'+e(opts.caption||'Records')+'</caption><thead><tr>'+(opts.selectable?'<th><input type="checkbox" aria-label="Select current page" data-select-all '+(slice.every(r=>selected.has(r.id))?'checked':'')+'></th>':'')+columns.map(c=>'<th scope="col">'+e(c.label)+'</th>').join('')+'</tr></thead><tbody>'+slice.map(r=>'<tr>'+(opts.selectable?'<td><input type="checkbox" aria-label="Select '+e(r.reference||r.name||r.id)+'" data-row-id="'+e(r.id)+'" '+(selected.has(r.id)?'checked':'')+'></td>':'')+columns.map(c=>'<td>'+(c.render?c.render(r):e(r[c.key]))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><div class="pagination"><span>Showing '+((page-1)*size+1)+'–'+Math.min(page*size,rows.length)+' of '+rows.length+' records</span><div class="actions"><button class="btn sm" data-prev '+(page===1?'disabled':'')+'>'+Icons('left')+'Previous</button><span>'+page+' / '+Math.ceil(rows.length/size)+'</span><button class="btn sm" data-next '+(page*size>=rows.length?'disabled':'')+'>Next'+Icons('chevron')+'</button></div></div>':empty(opts.emptyTitle||'No matching records',opts.emptyMessage||'Try another filter or add a record.');if($('[data-prev]',root)){$('[data-prev]',root).onclick=()=>{page--;draw();};$('[data-next]',root).onclick=()=>{page++;draw();};}$$('[data-row-id]',root).forEach(n=>n.onchange=()=>{n.checked?selected.add(Number(n.dataset.rowId)):selected.delete(Number(n.dataset.rowId));opts.onSelect?.(selected);draw();});const all=$('[data-select-all]',root);if(all)all.onchange=()=>{slice.forEach(r=>all.checked?selected.add(r.id):selected.delete(r.id));opts.onSelect?.(selected);draw();};}draw();return {refresh:draw,selected}; }
  function download(blob,name) { const url=URL.createObjectURL(blob),a=el('a',{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000); }
  function csv(name,rows,columns) { if(!rows.length){toast('No records to export.','error');return;}const keys=columns||Object.keys(rows[0]).filter(k=>!['password','password_hash','content'].includes(k)&&typeof rows[0][k]!=='object');const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,m=>"'"+m).replace(/"/g,'""')+'"';download(new Blob(['\uFEFF'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8;'}),name.endsWith('.csv')?name:name+'.csv');toast('CSV exported.'); }
  function applyTheme(value) { if(value==='system')delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=value;window.Charts?.redrawAll();$$('[data-theme-toggle]').forEach(b=>{b.innerHTML=Icons(isDark()?'sun':'moon');b.setAttribute('aria-label',isDark()?'Switch to light mode':'Switch to dark mode');}); }
  function isDark(){return document.documentElement.dataset.theme==='dark'||(!document.documentElement.dataset.theme&&matchMedia('(prefers-color-scheme: dark)').matches);}
  async function theme(value){applyTheme(value);if(window.API)await API.preferences.set({theme:value});}
  async function initTheme(){if(window.API){try{const p=await API.preferences.get();applyTheme(p.theme||'system');}catch{applyTheme('system');}}}
  document.addEventListener('click',ev=>{if(ev.target.closest('[data-theme-toggle]'))theme(isDark()?'light':'dark').catch(err=>toast(err.message,'error'));});
  matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(!document.documentElement.dataset.theme)applyTheme('system');});
  function formData(form) { return Object.fromEntries(new FormData(form).entries()); }
  async function busy(button,fn) { const html=button.innerHTML;button.disabled=true;button.innerHTML='<span class="spinner"></span>Working…';try{return await fn();}catch(err){toast(err.message,'error');return null;}finally{if(button.isConnected){button.disabled=false;button.innerHTML=html;}} }
  function run(fn){document.addEventListener('DOMContentLoaded',()=>{
    document.body.setAttribute('aria-busy','true');
    Promise.resolve().then(fn).catch(err=>{toast(err.message,'error');const target=$('#page')||$('main')||$('#app');if(target)target.innerHTML='<div class="alert error" role="alert">'+e(err.message)+'</div><a class="btn" href="index.html">Return home</a>';}).finally(()=>document.body.setAttribute('aria-busy','false'));
  },{once:true});}
  function printApplication(a){const w=window.open('','_blank');if(!w){toast('Allow popups to open the printable document.','error');return;}const approved=a.status==='APPROVED';w.document.write('<!doctype html><html lang="en"><head><meta charset="utf-8"><title>'+e(a.reference)+' — '+(approved?'Certificate':'Acknowledgment')+'</title><style>body{font:15px/1.8 Georgia,serif;color:#173b2d;max-width:760px;margin:50px auto;padding:40px;border:double 5px #23543d}header{text-align:center;border-bottom:1px solid;padding-bottom:24px}h1{font-size:28px}dl{display:grid;grid-template-columns:180px 1fr}dd{margin:0}footer{margin-top:40px;font:12px sans-serif}button{padding:12px 24px;margin-top:20px}@media print{button{display:none}body{margin:0}}</style></head><body><header><p>CIVIC DESK · PUBLIC SERVICES</p><h1>'+ (approved?'Service approval certificate':'Application acknowledgment')+'</h1><p>'+e(a.reference)+'</p></header><dl><dt>Applicant</dt><dd>'+e(a.citizen_name)+'</dd><dt>Service</dt><dd>'+e(a.service_name)+'</dd><dt>Department</dt><dd>'+e(a.department_name)+'</dd><dt>Submitted</dt><dd>'+e(date(a.created_at))+'</dd><dt>Current status</dt><dd>'+e(labels[a.status])+'</dd><dt>Decision date</dt><dd>'+e(date(a.decided_at))+'</dd><dt>Service fee</dt><dd>'+e(UI.currency(a.fee))+'</dd></dl><p>'+e(approved?'This application has been approved by the reviewing department.':'Your application has been received. Keep this reference number to track progress.')+'</p><footer>College capstone demonstration · Not a legally valid government document.<br>Verify status using the portal’s public tracking page.</footer><button id="print-record">Print / Save as PDF</button></body></html>');w.document.close();w.document.getElementById('print-record').onclick=()=>w.print();}
  function suggestDocumentLabel(filename,required){
    const words=filename.toLowerCase().replace(/\.[^.]+$/,'').replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/);
    const synonyms={'Identity proof':['identity','id','aadhaar','aadhar','passport'],'Address proof':['address','utility','residence'],'Photograph':['photo','photograph','portrait'],'Income proof':['income','salary','payslip'],'Property document':['property','deed','ownership'],'Educational certificate':['education','educational','degree','marksheet'],'Medical certificate':['medical','health','doctor'],'Business registration':['business','registration','company']};
    const ranked=required.map(label=>{const meaningful=label.toLowerCase().split(' ').filter(w=>!['proof','document','certificate'].includes(w)),tokens=[...new Set([...meaningful,...(synonyms[label]||[])])];return {label,score:tokens.filter(token=>words.includes(token)).length};}).sort((a,b)=>b.score-a.score);
    return ranked[0]?.score?ranked[0].label:required[0]||'Supporting document';
  }
  async function files(input,required=[]) {const result=[];for(const file of Array.from(input)){if(file.size>1024*1024)throw Error('Each file must be 1 MB or smaller.');if(!/\.(pdf|png|jpe?g|txt)$/i.test(file.name))throw Error('Use PDF, PNG, JPG, or TXT documents.');const content=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read '+file.name));r.readAsDataURL(file);});result.push({name:file.name,size:file.size,mime:file.type||'text/plain',label:suggestDocumentLabel(file.name,required),content});}return result;}
  function dropzone(root,callback){const input=$('input[type=file]',root);input.addEventListener('change',()=>callback(input.files));['dragenter','dragover'].forEach(event=>root.addEventListener(event,ev=>{ev.preventDefault();root.classList.add('dragover');}));['dragleave','drop'].forEach(event=>root.addEventListener(event,ev=>{ev.preventDefault();root.classList.remove('dragover');}));root.addEventListener('drop',ev=>callback(ev.dataTransfer.files));}
  async function openDocument(id){try{const d=await API.documents.get(id);const parts=d.content.split(',');const bytes=Uint8Array.from(atob(parts[1]),c=>c.charCodeAt(0));download(new Blob([bytes],{type:d.mime}),d.name);}catch(err){toast(err.message,'error');}}
  function documents(docs){return docs.length?'<div class="document-grid">'+docs.map(d=>'<button class="document-link btn" data-document="'+e(d.id)+'">'+Icons('file')+'<span class="file-meta">'+e(d.label)+'<small>'+e(d.name)+' · '+e(UI.fileSize(d.size))+'</small></span>'+Icons('download')+'</button>').join('')+'</div>':empty('No documents','No documents are attached.');}
  document.addEventListener('click',ev=>{const b=ev.target.closest('[data-document]');if(b)openDocument(Number(b.dataset.document));});
  window.UI={$,$$,e,el,on,date,relative,initials,currency:v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v)||0),fileSize:v=>v<1024?v+' B':v<1048576?(v/1024).toFixed(1)+' KB':(v/1048576).toFixed(1)+' MB',toast,modal,confirm,badge,labels,statusIcons,timeline,empty,stat,options,field,select,table,csv,download,theme,applyTheme,initTheme,isDark,formData,busy,run,printApplication,files,dropzone,documents};
})();
