UI.run(async()=>{
  const user=await Auth.guard(['admin']);if(!user)return;
  await Shell.mount({title:'The people behind public service.',subtitle:'Manage access and make sure each officer has the right department.',eyebrow:'User management',actions:'<button class="btn" id="users-export">'+Icons('download')+'Export CSV</button><button class="btn primary" id="new-user">'+Icons('plus')+'Create staff account</button>'});
  const departments=await API.departments.list();let users=[],filtered=[];
  UI.$('#page').innerHTML='<div class="stat-grid" id="user-stats"></div><section class="card"><div class="filters">'+UI.field('Search people','user-search','search','','placeholder="Name or email address"')+UI.select('Role','user-role',[{id:'citizen',name:'Citizen'},{id:'officer',name:'Officer'},{id:'admin',name:'Admin'}],'','All roles')+UI.select('Department','user-department',departments,'','All departments')+UI.select('Account status','user-active',[{id:'active',name:'Active'},{id:'inactive',name:'Inactive'}],'','All accounts')+'</div><div id="user-table"></div></section>';
  function render(){const q=UI.$('#user-search').value.toLowerCase(),r=UI.$('#user-role').value,d=UI.$('#user-department').value,active=UI.$('#user-active').value;filtered=users.filter(u=>(!q||[u.name,u.email].some(x=>x.toLowerCase().includes(q)))&&(!r||u.role===r)&&(!d||u.department_id===Number(d))&&(!active||u.active===(active==='active')));UI.table('#user-table',[{label:'Person',render:u=>'<span class="row gap-sm"><span class="avatar">'+UI.e(UI.initials(u.name))+'</span><span>'+UI.e(u.name)+'<span class="secondary">'+UI.e(u.email)+'</span></span></span>'},{label:'Role',render:u=>'<span class="badge">'+UI.e(u.role)+'</span>'},{label:'Department',render:u=>UI.e(departments.find(d=>d.id===u.department_id)?.name||(u.role==='admin'?'All departments':'Citizen account'))},{label:'Status',render:u=>'<span class="badge" data-status="'+(u.active?'APPROVED':'WITHDRAWN')+'">'+(u.active?'Active':'Inactive')+'</span>'},{label:'Joined',render:u=>UI.e(UI.date(u.created_at))},{label:'Actions',render:u=>'<div class="actions">'+(u.role==='officer'?'<button class="btn sm" data-edit-user="'+u.id+'">Department</button>':'')+'<button class="btn sm '+(u.active?'danger':'')+'" data-toggle-user="'+u.id+'" '+(u.id===user.id?'disabled aria-label="Your own account cannot be deactivated"':'')+'>'+(u.active?'Deactivate':'Activate')+'</button></div>'}],filtered,{caption:'User management',pageSize:10});}
  async function load(){users=await API.users.list({});UI.$('#user-stats').innerHTML=UI.stat('Total accounts',users.length,'users','Registered portal users')+UI.stat('Citizens',users.filter(u=>u.role==='citizen').length,'user','Self-service access')+UI.stat('Department officers',users.filter(u=>u.role==='officer').length,'briefcase','Reviewing service requests')+UI.stat('Active accounts',users.filter(u=>u.active).length,'shield','Accounts that can sign in');render();}
  UI.$$('.filters input,.filters select').forEach(n=>n.addEventListener(n.tagName==='INPUT'?'input':'change',render));
  UI.on(UI.$('#user-table'),'click','[data-toggle-user]',async(_,b)=>{const u=users.find(u=>u.id===Number(b.dataset.toggleUser));if(!await UI.confirm((u.active?'Deactivate ':'Activate ')+u.name+'?',u.active?'This user will lose access at their next session check. Their records will be retained.':'This user will be able to sign in again.',u.active?'Deactivate account':'Activate account'))return;UI.busy(b,async()=>{await API.users.update(u.id,{active:!u.active});UI.toast('Account status updated.');await load();await Shell.refresh();});});
  UI.on(UI.$('#user-table'),'click','[data-edit-user]',(_,b)=>{const u=users.find(u=>u.id===Number(b.dataset.editUser));const m=UI.modal('Change officer department','<form id="officer-department-form"><p class="small muted">Reassign open applications before moving an officer to another department.</p>'+UI.select('Department','department_id',departments,u.department_id,null,'required')+'<button class="btn primary" type="submit">Save department</button></form>');UI.$('#officer-department-form',m.element).onsubmit=ev=>{ev.preventDefault();UI.busy(UI.$('button[type=submit]',ev.target),async()=>{await API.users.update(u.id,UI.formData(ev.target));m.close();UI.toast('Department updated.');await load();});};});
  UI.$('#new-user').onclick=()=>{const m=UI.modal('Create staff account','<form id="create-user-form">'+UI.field('Full name','name','text','','required minlength="3" maxlength="100"')+UI.field('Email address','email','email','','required autocomplete="off"')+'<div class="form-grid">'+UI.select('Role','role',[{id:'officer',name:'Officer'},{id:'admin',name:'Admin'}],'officer',null)+UI.select('Department','department_id',departments,'','Choose department','required')+'</div>'+UI.field('Initial password','password','password','','required minlength="8" maxlength="100" autocomplete="new-password"')+'<p class="small muted">Use at least 8 characters with letters and a number. Share credentials directly with the account holder.</p><div class="modal-actions"><button class="btn primary" type="submit">Create account</button></div></form>');UI.$('#role',m.element).onchange=ev=>{const d=UI.$('#department_id',m.element);d.disabled=ev.target.value==='admin';d.required=ev.target.value==='officer';};UI.$('#create-user-form',m.element).onsubmit=ev=>{ev.preventDefault();UI.busy(UI.$('button[type=submit]',ev.target),async()=>{await API.users.create(UI.formData(ev.target));m.close();UI.toast('Staff account created.');await load();await Shell.refresh();});};};
  UI.$('#users-export').onclick=()=>UI.csv('portal-users',filtered,['id','name','email','role','department_id','active','created_at']);await load();
});

