UI.run(async()=>{
  const user=await Auth.guard(['citizen','officer','admin']);if(!user)return;
  await Shell.mount({title:'Make yourself at home.',subtitle:'Manage your details, account security, and preferences.',eyebrow:'My profile'});
  const [departments,activity,preferences]=await Promise.all([API.departments.list(),API.analytics.activity({}),API.preferences.get()]);
  UI.$('#page').innerHTML='<div class="dashboard-grid"><div class="stack"><section class="card"><div class="profile-head"><span class="avatar large">'+UI.e(UI.initials(user.name))+'</span><div><h2>'+UI.e(user.name)+'</h2><span class="badge">'+UI.e(user.role)+'</span><small style="display:block">'+UI.e(user.email)+'</small></div></div><form id="profile-form"><div class="form-grid">'+UI.field('Full name','name','text',user.name,'required minlength="3" maxlength="100" autocomplete="name"')+UI.field('Mobile number','phone','tel',user.phone,'required pattern="[0-9]{10,15}" autocomplete="tel"')+'</div>'+UI.field('Address','address','text',user.address,'required minlength="8" maxlength="300" autocomplete="street-address"')+'<p class="small muted">'+(user.role==='officer'?'Assigned department: '+UI.e(departments.find(d=>d.id===user.department_id)?.name||'Unassigned'):user.role==='admin'?'Administrator access covers all departments and service records.':'Your details are used to prefill new applications.')+'</p><button class="btn primary" type="submit">'+Icons('save')+'Save profile</button></form></section><section class="card">'+Views.head('Change password','Use a unique password with at least 8 characters, letters, and a number.')+'<form id="password-form">'+UI.field('Current password','current_password','password','','required autocomplete="current-password"')+'<div class="form-grid">'+UI.field('New password','new_password','password','','required minlength="8" maxlength="100" autocomplete="new-password"')+UI.field('Confirm new password','confirm_password','password','','required minlength="8" autocomplete="new-password"')+'</div><button class="btn" type="submit">'+Icons('lock')+'Update password</button></form></section></div><div class="stack"><section class="card">'+Views.head('Your preferred view','Choose how Civic Desk looks on this device.')+UI.select('Color theme','theme',[{id:'system',name:'Match device setting'},{id:'light',name:'Light'},{id:'dark',name:'Dark'}],preferences.theme,null)+'</section><section class="card">'+Views.head('Recent activity',user.role==='citizen'?'Your application updates':'Updates from your workspace')+'<div class="activity-feed">'+UI.timeline(activity.slice(0,8))+'</div></section></div></div>';
  UI.$('#profile-form').onsubmit=ev=>{ev.preventDefault();UI.busy(UI.$('button[type=submit]',ev.target),async()=>{await API.users.update(user.id,UI.formData(ev.target));await Auth.refresh();UI.toast('Profile updated.');});};
  const confirm=UI.$('#confirm_password'),pass=UI.$('#new_password');[confirm,pass].forEach(n=>n.oninput=()=>confirm.setCustomValidity(confirm.value&&confirm.value!==pass.value?'Passwords do not match.':''));
  UI.$('#password-form').onsubmit=ev=>{ev.preventDefault();UI.busy(UI.$('button[type=submit]',ev.target),async()=>{await API.users.changePassword(UI.formData(ev.target));ev.target.reset();UI.toast('Password updated.');});};
  UI.$('#theme').onchange=ev=>UI.theme(ev.target.value).then(()=>UI.toast('Theme preference saved.')).catch(err=>UI.toast(err.message,'error'));
});

