UI.run(async()=>{
  const user=await Auth.guard(['officer']);if(!user)return;
  await Shell.mount({title:'Every request deserves a next step.',subtitle:'Find your priorities and keep your department moving.',eyebrow:'Work queue',actions:'<button class="btn" id="queue-export">'+Icons('download')+'Export CSV</button><button class="btn primary" id="bulk-assign" disabled>'+Icons('assignment')+'Assign selected to me</button>'});
  const services=await API.services.list({});let apps=[],filtered=[],view='open',selected=new Set();
  const predicates={open:a=>Views.statuses.slice(0,4).includes(a.status),mine:a=>a.officer_id===user.id&&Views.statuses.slice(0,4).includes(a.status),unassigned:a=>!a.officer_id&&Views.statuses.slice(0,4).includes(a.status),overdue:a=>a.isOverdue,waiting:a=>a.status==='NEEDS_INFO',decided:a=>!Views.statuses.slice(0,4).includes(a.status),all:()=>true};
  const names={open:'Open',mine:'Assigned to me',unassigned:'Unassigned',overdue:'Past timeline',waiting:'Awaiting applicant',decided:'Decided',all:'Everything'};
  UI.$('#page').innerHTML='<div id="queue-views" class="chips" aria-label="Saved queue views"></div><section class="card"><div class="filters">'+UI.field('Search','queue-search','search',new URLSearchParams(location.search).get('q')||'','placeholder="Reference, applicant, or service"')+UI.select('Service','queue-service',services,'','All services')+UI.select('Priority','queue-priority',[{id:'normal',name:'Normal'},{id:'high',name:'High'},{id:'urgent',name:'Urgent'}],'','All priorities')+UI.select('Sort by','queue-sort',[{id:'oldest',name:'Oldest first'},{id:'newest',name:'Newest first'},{id:'priority',name:'Highest priority'},{id:'sla',name:'Closest to breach'}],'oldest',null)+'</div><p class="small muted" id="selection-label">Select open applications to assign them to yourself.</p><div id="queue-table"></div></section>';
  function render(){UI.$('#queue-views').innerHTML=Object.keys(names).map(k=>'<button class="chip '+(view===k?'active':'')+'" aria-pressed="'+(view===k)+'" data-view="'+k+'">'+names[k]+'<b>'+apps.filter(predicates[k]).length+'</b></button>').join('');const q=UI.$('#queue-search').value.toLowerCase(),s=UI.$('#queue-service').value,p=UI.$('#queue-priority').value;filtered=Views.sort(apps.filter(a=>predicates[view](a)&&(!q||[a.reference,a.service_name,a.citizen_name].some(x=>x.toLowerCase().includes(q)))&&(!s||a.service_id===Number(s))&&(!p||a.priority===p)),UI.$('#queue-sort').value);const columns=Views.columns('officer');columns.splice(3,0,{label:'Assignment / Priority',render:a=>UI.e(a.officer_name)+'<span class="secondary">'+UI.e(a.priority[0].toUpperCase()+a.priority.slice(1))+' priority</span>'});UI.table('#queue-table',columns,filtered,{selectable:true,selected,onSelect:updateSelection,pageSize:10,caption:'Department work queue'});updateSelection();}
  function updateSelection(){UI.$('#bulk-assign').disabled=!selected.size;UI.$('#selection-label').textContent=selected.size?selected.size+' selected · Only open applications can be assigned.':'Select open applications to assign them to yourself.';}
  async function load(){apps=await API.applications.list({});selected.clear();render();}
  UI.on(UI.$('#queue-views'),'click','[data-view]',(_,b)=>{view=b.dataset.view;selected.clear();render();});UI.$$('.filters input,.filters select').forEach(n=>n.addEventListener(n.tagName==='INPUT'?'input':'change',()=>{selected.clear();render();}));
  UI.$('#bulk-assign').onclick=()=>UI.busy(UI.$('#bulk-assign'),async()=>{await API.applications.assign([...selected],user.id);UI.toast('Applications assigned to you.');await Shell.refresh();await load();}).then(updateSelection);
  UI.$('#queue-export').onclick=()=>UI.csv('department-work-queue',filtered,Views.exportColumns);await load();
});

