UI.run(async()=>{
  const user=await Auth.guard(['officer','admin']);if(!user)return;
  await Shell.mount({title:'Give this request its next step.',subtitle:'Review the record, explain your decision, and keep the applicant informed.',eyebrow:'Application review',actions:'<a class="btn" href="'+(user.role==='admin'?'admin-applications':'officer-queue')+'.html">'+Icons('back')+'Back to register</a>'});
  let id=Number(new URLSearchParams(location.search).get('id'));if(!id){const list=await API.applications.list({});id=list.find(a=>['SUBMITTED','UNDER_REVIEW','FORWARDED'].includes(a.status))?.id||list[0]?.id;}if(!id){UI.$('#page').innerHTML=UI.empty('No application to review','Applications will appear here when citizens submit them.');return;}
  const departments=await API.departments.list();
  const templates={UNDER_REVIEW:['Document verification has started. I will check the supplied records against the service requirements.','The forwarded application has been accepted for review by this department.'],APPROVED:['All submitted documents have been verified and the applicant meets the service eligibility requirements.','Verification is complete. The records are consistent and this service request is approved.'],REJECTED:['The submitted evidence does not establish eligibility for this service. Please review the requirements before reapplying.','The documents contain inconsistencies that could not be resolved during verification. This request is rejected.'],NEEDS_INFO:['Please provide a clear and recent address proof so that verification can continue.','Please clarify the purpose of this request and attach a legible identity document.'],FORWARDED:['This request requires specialist verification and is being forwarded to the appropriate department.','The application falls within the receiving department’s area of responsibility. Please continue the review.']};
  async function render(){const a=await API.applications.get(id),allowed=a.status==='SUBMITTED'||a.status==='FORWARDED'?['UNDER_REVIEW']:a.status==='UNDER_REVIEW'?['APPROVED','REJECTED','NEEDS_INFO','FORWARDED']:[],names={UNDER_REVIEW:'Take up for review',APPROVED:'Approve',REJECTED:'Reject',NEEDS_INFO:'Request more information',FORWARDED:'Forward to another department'};
    UI.$('#page').innerHTML='<div class="scope-bar"><div class="row"><span class="mono">'+UI.e(a.reference)+'</span>'+UI.badge(a.status)+(a.isOverdue?'<span class="text-danger small">'+Icons('clock')+' Past service timeline</span>':'')+'</div><span class="small muted">'+UI.e(a.department_name)+'</span></div><div class="review-layout"><div class="stack"><section class="card">'+Views.head('Applicant & service')+'<div class="profile-head"><span class="avatar large">'+UI.e(UI.initials(a.citizen_name))+'</span><div><h2>'+UI.e(a.citizen_name)+'</h2><small>'+UI.e(a.citizen_email)+'</small></div></div>'+Views.detail(a)+'</section><section class="card">'+Views.head('Submitted information')+Views.formDetails(a.form_data)+'</section><section class="card">'+Views.head('Uploaded documents','Download each file to inspect the submitted evidence.')+UI.documents(a.documents)+'</section><section class="card">'+Views.head('Complete audit trail')+UI.timeline(a.logs)+'</section></div><aside class="card decision-panel">'+Views.head('Review & decision','Every action becomes part of the permanent audit trail.')+(allowed.length?((user.role==='officer'&&a.officer_id&&a.officer_id!==user.id)?'<div class="alert warning">'+Icons('assignment')+'This application is assigned to '+UI.e(a.officer_name)+'.</div><button class="btn full" id="assign-review">Assign to me</button><div class="divider"></div>':'')+'<form id="decision-form"><fieldset><legend>Choose an action</legend>'+allowed.map((s,i)=>'<label class="decision-choice"><input type="radio" name="decision" value="'+s+'" '+(i===0?'checked':'')+'>'+Icons(UI.statusIcons[s])+names[s]+'</label>').join('')+'</fieldset><div id="forward-fields" hidden>'+UI.select('Destination department','forward-department',departments,'','Choose department')+UI.select('Destination officer (optional)','forward-officer',[],'','Department’s unassigned queue')+'</div><div class="field"><label for="decision-remarks">Decision remarks</label><textarea id="decision-remarks" required minlength="20" maxlength="2000" placeholder="Explain your decision clearly for the applicant."></textarea><span class="hint" id="remarks-count">At least 20 characters. Give a meaningful justification.</span></div><div class="eyebrow" style="margin-bottom:.5rem">Quick-insert starting points</div><div class="remark-templates" id="remark-templates"></div><div class="alert">'+Icons('bell')+'The citizen will receive a notification with these remarks.</div><button class="btn primary full" id="commit-decision" type="submit">Review & confirm'+Icons('arrow')+'</button></form>':a.status==='NEEDS_INFO'?'<div class="alert warning">'+Icons('clock')+'Waiting for the applicant to respond. Review resumes after their response.</div>':'<div class="alert">'+Icons('shield')+'This application is closed. Its audit history is retained below.</div><button class="btn full" id="review-print">'+Icons('print')+'Print application record</button>')+'</aside></div>';
    const assign=UI.$('#assign-review');if(assign)assign.onclick=()=>UI.busy(assign,async()=>{await API.applications.assign([id],user.id);await Shell.refresh();await render();UI.toast('Assigned to you.');});
    const print=UI.$('#review-print');if(print)print.onclick=()=>UI.printApplication(a);
    if(!allowed.length)return;
    function selected(){return UI.$('input[name=decision]:checked').value;}
    function choose(){const s=selected();UI.$('#forward-fields').hidden=s!=='FORWARDED';UI.$('#forward-department').required=s==='FORWARDED';UI.$('#remark-templates').innerHTML=templates[s].map((t,i)=>'<button type="button" class="btn sm" data-template="'+i+'">'+Icons('message')+'Template '+(i+1)+'</button>').join('');UI.$$('[data-template]').forEach(b=>b.onclick=()=>{UI.$('#decision-remarks').value=templates[s][Number(b.dataset.template)];UI.$('#decision-remarks').dispatchEvent(new Event('input'));UI.$('#decision-remarks').focus();});}
    UI.$$('input[name=decision]').forEach(n=>n.onchange=choose);choose();
    UI.$('#decision-remarks').oninput=ev=>{UI.$('#remarks-count').textContent=ev.target.value.trim().length+' / 20 minimum characters';};
    UI.$('#forward-department').onchange=async ev=>{try{const officers=await API.users.list({role:'officer',department_id:ev.target.value,active:true});UI.$('#forward-officer').innerHTML=UI.options(officers,'','Department’s unassigned queue');}catch(err){UI.toast(err.message,'error');}};
    UI.$('#decision-form').onsubmit=async ev=>{ev.preventDefault();const status=selected(),remarks=UI.$('#decision-remarks').value.trim();if(remarks.length<20){UI.toast('Provide at least 20 characters of meaningful remarks.','error');return;}if(!await UI.confirm('Confirm '+names[status].toLowerCase()+'?',a.reference+' · '+remarks,'Confirm decision'))return;UI.busy(UI.$('#commit-decision'),async()=>{const result=await API.applications.transition(id,{status,remarks,department_id:UI.$('#forward-department').value,officer_id:UI.$('#forward-officer').value});UI.toast('Decision recorded and citizen notified.');await Shell.refresh();if(user.role==='officer'&&result.department_id!==user.department_id)location.href='officer-queue.html';else await render();});};
  }await render();
});

