const {chromium}=require('../.test-tools/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const pages=fs.readdirSync(root).filter(f=>f.endsWith('.html'));
const browserPath=process.env.BROWSER_PATH||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
const allowed={};pages.forEach(f=>allowed[f]=f.startsWith('admin-')?['admin']:f.startsWith('officer-')?['officer']:f.startsWith('citizen-')?['citizen']:['guest','citizen','officer','admin']);allowed['citizen-profile.html']=['citizen','officer','admin'];allowed['officer-review.html']=['officer','admin'];allowed['officer-grievances.html']=['officer','admin'];
const home=role=>role==='guest'?'login.html':role+'-dashboard.html';
let cases=0;const errors=[],results=[];
const server=http.createServer((req,res)=>{let relative;try{relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400);res.end();return;}if(relative==='/')relative='/index.html';const file=path.resolve(root,'.'+relative);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end('Not found');return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.css':'text/css','.js':'text/javascript'})[path.extname(file)]||'application/octet-stream'});res.end(data);});});
function monitor(page,label){page.on('pageerror',err=>errors.push(label+': '+err.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(label+': '+msg.text());});}
async function ready(page,expected){await page.waitForFunction(expected=>location.pathname.endsWith('/'+expected)&&document.readyState==='complete'&&document.body.getAttribute('aria-busy')!=='true'&&!document.querySelector('.loading')&&!!document.querySelector('h1'),expected,{timeout:30000});}
async function login(page,url,role){await page.goto(url('login.html'));await ready(page,'login.html');await page.locator('[data-demo="'+role+'"]').click();await page.locator('#login-form button[type=submit]').click();await ready(page,home(role));}
async function logout(page){await page.locator('#user-toggle').click();await page.locator('#sign-out').click();await ready(page,'login.html');}
async function matrix(browser,url,mode){const quick=process.argv.includes('--quick');const styles=quick?[{theme:'light',width:1440,height:960}]:[{theme:'light',width:1440,height:960},{theme:'dark',width:1440,height:960},{theme:'light',width:390,height:844},{theme:'dark',width:390,height:844}];
  for(const style of styles)for(const role of ['guest','citizen','officer','admin']){
    const context=await browser.newContext({viewport:{width:style.width,height:style.height},colorScheme:style.theme,acceptDownloads:true});if(mode==='file')await context.setOffline(true);
    await context.addInitScript(mode=>{let api;Object.defineProperty(window,'API',{configurable:true,get:()=>api,set:value=>{api=value;api.MODE=mode==='live'?'live':'demo';api.LATENCY=0;}});},mode);
    const page=await context.newPage();monitor(page,mode+'/'+role+'/'+style.theme+'/'+style.width);
    await page.goto(url('index.html'));await ready(page,'index.html');if(role!=='guest')await login(page,url,role);
    for(const file of pages){let expected=allowed[file].includes(role)?file:home(role);if(['login.html','register.html'].includes(file)&&role!=='guest')expected=home(role);
      await page.goto(url(file));await ready(page,expected);await page.waitForTimeout(35);
      assert.equal(await page.locator('.toast.error').count(),0,'Error toast on '+mode+'/'+role+'/'+file);
      const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,bg:getComputedStyle(document.documentElement).getPropertyValue('--bg').trim(),dark:UI.isDark()}));
      assert.ok(dimensions.scroll<=dimensions.width+2,'Horizontal overflow '+mode+'/'+role+'/'+file+'/'+style.width+': '+JSON.stringify(dimensions));assert.equal(dimensions.dark,style.theme==='dark','Theme does not follow OS preference');
      if(file==='admin-dashboard.html'&&role==='admin'){assert.ok(await page.locator('.chart svg').count()>=6);if(mode==='http')await page.screenshot({path:path.join(out,'admin-'+style.theme+'-'+style.width+'.png'),fullPage:true});}
      if(style.width===390&&file===home(role)&&role!=='guest'){await page.locator('#mobile-menu').click();assert.equal(await page.locator('#mobile-menu').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('#mobile-menu').getAttribute('aria-expanded'),'false');}
      cases++;
    }
    await context.close();console.log('PASS matrix '+mode+' '+role+' '+style.theme+' '+style.width+' ('+cases+' page visits)');
  }
}
async function workflow(browser,url,mode){
  const context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true});if(mode==='file')await context.setOffline(true);await context.addInitScript(mode=>{let api;Object.defineProperty(window,'API',{configurable:true,get:()=>api,set:value=>{api=value;api.MODE=mode==='live'?'live':'demo';api.LATENCY=0;}});},mode);const page=await context.newPage();monitor(page,mode+'/workflow');
  await login(page,url,'citizen');await page.goto(url('citizen-apply.html'));await ready(page,'citizen-apply.html');
  await page.locator('#department').selectOption('1');await page.locator('input[name=service][value="3"]').check();await page.locator('#wizard-next').click();
  await page.locator('#purpose').fill('I need a verified birth certificate for my college admission records.');await page.locator('#wizard-next').click();
  await page.locator('#document-upload').setInputFiles({name:'identity-proof.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic identity proof for end-to-end portal verification.')});await page.locator('#document-warning .alert').filter({hasText:'All required'}).waitFor();await page.locator('#wizard-next').click();await page.locator('#declaration').check();await page.locator('#wizard-next').click();await page.locator('#submitted-reference').waitFor();const reference=(await page.locator('#submitted-reference').textContent()).trim();assert.match(reference,/^GOV-\d{4}-\d{6}$/);
  const app=await page.evaluate(async ref=>(await API.applications.list({search:ref}))[0],reference);assert.equal(app.status,'SUBMITTED');
  const popupPromise=page.waitForEvent('popup');await page.locator('#print-ack').click();const popup=await popupPromise;await popup.waitForLoadState();assert.ok((await popup.locator('body').innerText()).includes(reference));await popup.close();
  await logout(page);await page.goto(url('track.html?ref='+reference));await ready(page,'track.html');await page.locator('[data-masked-name]').waitFor();const publicText=await page.locator('#track-result').innerText();assert.ok(!publicText.includes('Aarav Sharma'));assert.ok(!publicText.includes('citizen@demo.gov'));assert.ok(publicText.includes('A••• S•••'));assert.ok((await page.locator('[data-masked-email]').innerText()).includes('***'));
  const projection=await page.evaluate(ref=>API.applications.track(ref),reference);assert.ok(!JSON.stringify(projection).includes('citizen@demo.gov'));assert.equal(projection.documents,undefined);
  await login(page,url,'officer');await page.goto(url('officer-queue.html'));await ready(page,'officer-queue.html');await page.locator('#queue-search').fill(reference);await page.locator('#queue-table a').filter({hasText:reference}).click();await ready(page,'officer-review.html');
  await page.locator('input[name=decision][value=UNDER_REVIEW]').check();await page.locator('#decision-remarks').fill('I have taken ownership and started checking the applicant’s supporting document.');await page.locator('#commit-decision').click();await page.locator('[data-confirm]').click();await page.locator('input[name=decision][value=APPROVED]').waitFor();
  await page.locator('input[name=decision][value=APPROVED]').check();await page.locator('#decision-remarks').fill('The identity proof and submitted birth details have been verified. All requirements are satisfied.');await page.locator('#commit-decision').click();await page.locator('[data-confirm]').click();await page.locator('#review-print').waitFor();assert.equal(await page.evaluate(id=>API.applications.get(id).then(a=>a.status),app.id),'APPROVED');
  await logout(page);await login(page,url,'citizen');await page.locator('#notification-toggle').click();await page.locator('#notification-panel .notification').filter({hasText:reference+' · approved'}).waitFor();await page.goto(url('citizen-application.html?id='+app.id));await ready(page,'citizen-application.html');assert.ok((await page.locator('#print-document').innerText()).includes('certificate'));const documentDownload=page.waitForEvent('download');await page.locator('[data-document]').first().click();const downloadedDoc=await documentDownload;await downloadedDoc.saveAs(path.join(out,mode+'-identity-proof.txt'));assert.ok(fs.readFileSync(path.join(out,mode+'-identity-proof.txt'),'utf8').includes('Synthetic identity'));
  await page.goto(url('citizen-grievances.html'));await ready(page,'citizen-grievances.html');await page.locator('#new-grievance').click();await page.locator('#application_id').selectOption(String(app.id));await page.locator('#subject').fill('Workflow verification: certificate clarification');await page.locator('#description').fill('Please clarify how I can use the approved certificate and whether any additional office visit is required.');await page.locator('#grievance-form button[type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});await page.locator('#grievance-table tbody tr').filter({hasText:'Workflow verification'}).waitFor();const grievance=await page.evaluate(async()=> (await API.grievances.list({})).find(g=>g.subject==='Workflow verification: certificate clarification'));assert.equal(grievance.status,'OPEN');
  await logout(page);await login(page,url,'admin');await page.goto(url('admin-departments.html'));await ready(page,'admin-departments.html');await page.locator('#new-department').click();await page.locator('dialog #name').fill('Verification Services');await page.locator('dialog #code').fill('VFY');await page.locator('dialog #description').fill('Public services created during automated workflow verification.');await page.locator('dialog input[name=icon][value=shield]').check();await page.locator('#department-form button[type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});await page.locator('#new-service').waitFor();
  await page.locator('#new-service').click();await page.locator('dialog #name').fill('Community Verification Permit');await page.locator('dialog #description').fill('A community permit with a clear review timeline and identity document requirement.');await page.locator('dialog #fee').fill('150');await page.locator('dialog #sla_days').fill('12');await page.locator('#service-form button[type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});await page.locator('#service-table').filter({hasText:'Community Verification Permit'}).waitFor();
  await page.goto(url('admin-users.html'));await ready(page,'admin-users.html');await page.locator('#new-user').click();await page.locator('dialog #name').fill('Verification Officer');await page.locator('dialog #email').fill('verification.officer@demo.gov');await page.locator('dialog #department_id').selectOption({label:'Verification Services'});await page.locator('dialog #password').fill('VerifyOfficer123');await page.locator('#create-user-form button[type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});await page.locator('#user-search').fill('verification.officer@demo.gov');await page.locator('#user-table tbody tr').filter({hasText:'Verification Officer'}).waitFor();const csvPromise=page.waitForEvent('download');await page.locator('#users-export').click();const csv=await csvPromise;assert.ok(csv.suggestedFilename().endsWith('.csv'));await csv.saveAs(path.join(out,mode+'-users.csv'));assert.ok(fs.readFileSync(path.join(out,mode+'-users.csv'),'utf8').includes('verification.officer@demo.gov'));
  await page.goto(url('officer-grievances.html'));await ready(page,'officer-grievances.html');await page.locator('#grievance-search').fill(grievance.reference);await page.locator('#grievance-table [data-grievance]').click();await page.locator('#take-grievance').click();await page.locator('dialog').waitFor({state:'detached'});await page.locator('#grievance-table [data-grievance]').click();await page.locator('#resolution').fill('The approved certificate is available for download and printing. No additional office visit is required.');await page.locator('#resolve-form button[type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});await page.locator('#grievance-table [data-status=RESOLVED]').waitFor();
  await logout(page);await login(page,url,'citizen');await page.goto(url('citizen-grievances.html'));await ready(page,'citizen-grievances.html');await page.locator('#grievance-table tbody tr').filter({hasText:grievance.reference}).locator('[data-grievance]').click();assert.ok((await page.locator('dialog').innerText()).includes('No additional office visit is required.'));await page.locator('dialog [data-close]').click();
  await page.goto(url('citizen-profile.html'));await ready(page,'citizen-profile.html');await page.locator('#theme').selectOption('dark');assert.equal(await page.evaluate(()=>UI.isDark()),true);await page.goto(url('citizen-dashboard.html'));await ready(page,'citizen-dashboard.html');assert.equal(await page.evaluate(()=>UI.isDark()),true);await page.locator('[data-theme-toggle]').click();assert.equal(await page.evaluate(()=>UI.isDark()),false);
  await logout(page);await page.goto(url('register.html'));await ready(page,'register.html');await page.locator('#name').fill('New Citizen Tester');await page.locator('#phone').fill('9876543210');await page.locator('#email').fill('new.citizen@demo.gov');await page.locator('#address').fill('21 Civic Avenue, Hyderabad');await page.locator('#password').fill('CitizenTest123!');await page.locator('#confirm-password').fill('CitizenTest123!');await page.locator('#consent').check();await page.locator('#register-form button[type=submit]').click();await ready(page,'citizen-dashboard.html');assert.ok((await page.locator('h1').innerText()).includes('New'));
  assert.equal(errors.length,0,errors.join('\n'));results.push({mode,reference,grievance:grievance.reference,applicationStatus:'APPROVED',grievanceStatus:'RESOLVED',csv:mode+'-users.csv',passed:true});await context.close();console.log('PASS full UI workflow '+mode+': '+reference+', '+grievance.reference+', documents, notifications, configuration, CSV, registration, theme persistence.');
}
if(require.main===module)(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,...(browserPath?{executablePath:browserPath}:{})});try{
  for(const mode of ['http','file']){const url=file=>mode==='http'?base+'/'+file:pathToFileURL(path.join(root,file.split('?')[0])).href+(file.includes('?')?'?'+file.split('?').slice(1).join('?'):'');await matrix(browser,url,mode);await workflow(browser,url,mode);}
  assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify({timestamp:new Date().toISOString(),pageVisits:cases,consoleErrors:errors,workflows:results},null,2));console.log('PASS: '+cases+' page visits, both workflows, zero browser errors.');
}finally{await browser.close();server.close();}})().catch(err=>{console.error(err);fs.writeFileSync(path.join(out,'failure.txt'),err.stack+'\n'+errors.join('\n'));server.close();process.exitCode=1;});
module.exports={matrix,workflow,browserPath,ready,login,logout,errors,results,visits:()=>cases};
