const {chromium}=require('../.test-tools/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const url=file=>pathToFileURL(path.join(root,file.split('?')[0])).href+(file.includes('?')?'?'+file.split('?')[1]:'');
const executablePath=process.env.BROWSER_PATH||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
const errors=[];function monitor(page){page.on('pageerror',err=>errors.push(err.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});}
async function ready(page,file){await page.waitForFunction(file=>location.pathname.endsWith('/'+file)&&document.readyState==='complete'&&!document.querySelector('.loading')&&document.querySelector('h1'),file);}
const testFiles=['identity-proof.txt','address-proof.txt'];
function attachment(name){return {name,mimeType:'text/plain',buffer:Buffer.from('Demo supporting evidence for '+name)};}
(async()=>{const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});try{
  const quotaContext=await browser.newContext();await quotaContext.setOffline(true);await quotaContext.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Storage full','QuotaExceededError');};});const quotaPage=await quotaContext.newPage();monitor(quotaPage);await quotaPage.goto(url('index.html'));await ready(quotaPage,'index.html');assert.equal(await quotaPage.evaluate(()=>Store.storageMode),'memory');assert.equal(await quotaPage.evaluate(()=>API.analytics.public().then(a=>a.applications)),420);assert.equal(await quotaPage.locator('.toast.error').count(),0);await quotaContext.close();
  const context=await browser.newContext({viewport:{width:1440,height:960}});await context.setOffline(true);const page=await context.newPage();monitor(page);await page.goto(url('index.html'));await ready(page,'index.html');await page.evaluate(()=>Auth.login('citizen@demo.gov','citizen123','citizen'));await page.goto(url('citizen-apply.html'));await ready(page,'citizen-apply.html');await page.locator('#department').selectOption('1');await page.locator('input[name=service][value="1"]').check();await page.locator('#wizard-next').click();await page.locator('#purpose').fill('I need an income certificate to complete a scholarship application.');await page.locator('#wizard-next').click();
  await page.evaluate(()=>{const read=UI.files;UI.files=async(...args)=>{await new Promise(resolve=>setTimeout(resolve,500));return read(...args);};});await page.locator('#document-upload').setInputFiles(testFiles.map(attachment));assert.equal(await page.locator('#wizard-next').isDisabled(),true);assert.equal(await page.locator('#wizard-back').isDisabled(),true);await page.locator('#document-warning .alert').filter({hasText:'All required'}).waitFor();assert.deepEqual(await page.locator('[data-label]').evaluateAll(nodes=>nodes.map(n=>n.value)),['Identity proof','Address proof']);await page.locator('#wizard-next').click();await page.locator('#declaration').check();await page.locator('#wizard-next').click();await page.locator('#submitted-reference').waitFor();const ref=(await page.locator('#submitted-reference').innerText()).trim();const app=await page.evaluate(async ref=>(await API.applications.list({search:ref}))[0],ref);
  await page.evaluate(async id=>{await Auth.login('officer@demo.gov','officer123','officer');await API.applications.transition(id,{status:'UNDER_REVIEW',remarks:'Checking the required documents and verifying the applicant details.'});await API.applications.transition(id,{status:'NEEDS_INFO',remarks:'Please provide a recent address document to complete the verification.'});await Auth.login('citizen@demo.gov','citizen123','citizen');},app.id);await page.goto(url('citizen-application.html?id='+app.id));await ready(page,'citizen-application.html');
  await page.evaluate(()=>{const read=UI.files;UI.files=async(...args)=>{await new Promise(resolve=>setTimeout(resolve,500));return read(...args);};});await page.locator('#response').fill('I have attached the recent address proof requested by the reviewing officer.');await page.locator('#response-files').setInputFiles(attachment('recent-address-proof.txt'));assert.equal(await page.locator('#response-form button[type=submit]').isDisabled(),true);await page.evaluate(()=>document.querySelector('#response-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal(await page.evaluate(id=>API.applications.get(id).then(a=>a.status),app.id),'NEEDS_INFO');await page.locator('#response-file-list').filter({hasText:'recent-address-proof.txt'}).waitFor();await page.locator('#response-form button[type=submit]').click();await page.locator('#response-form').waitFor({state:'detached'});const updated=await page.evaluate(id=>API.applications.get(id),app.id);assert.equal(updated.status,'UNDER_REVIEW');assert.equal(updated.documents.length,3);assert.equal(updated.documents.at(-1).label,'Address proof');
  await page.locator('#user-toggle').click();assert.equal(await page.locator('#user-toggle').getAttribute('aria-expanded'),'true');await page.locator('#notification-toggle').click();assert.equal(await page.locator('#user-toggle').getAttribute('aria-expanded'),'false');await page.keyboard.press('Escape');assert.equal(await page.locator('#notification-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>document.activeElement.id),'notification-toggle');await page.locator('#user-toggle').click();await page.locator('h1').click();assert.equal(await page.locator('#user-toggle').getAttribute('aria-expanded'),'false');
  const timeline=await page.evaluate(()=>UI.timeline([{id:1,to_status:'SUBMITTED',remarks:'First entry',created_at:'2026-09-08T10:00:00.000Z'},{id:2,to_status:'UNDER_REVIEW',remarks:'Second entry',created_at:'2026-09-08T10:00:00.000Z'}]));assert.ok(timeline.indexOf('Second entry')<timeline.indexOf('First entry'));
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'edge-cases.json'),JSON.stringify({timestamp:new Date().toISOString(),quotaStartup:true,documentLabels:true,pendingUploadProtection:true,accessibleDropdowns:true,auditTieOrder:true,consoleErrors:errors},null,2));await context.close();console.log('PASS: full-storage startup, document labels, pending wizard/response uploads, menu accessibility, and equal-time audit order. Zero browser errors.');
}finally{await browser.close();}})().catch(err=>{console.error(err);console.error(errors);process.exitCode=1;});
