'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {setup,Client,report}=require('./live-support.cjs'),B=require('../server/identity/biometrics.cjs');
const PREFIX='/api/portal';let checks=0;
function equal(actual,expected,message){checks++;assert.equal(actual,expected,message);}
function ok(value,message){checks++;assert.ok(value,message);}
async function request(c,method,url,data,status=200,token){const r=await c.request(method,PREFIX+url,data,token?{headers:{'X-Identity-Token':token}}:{});equal(r.status,status,method+' '+url+' '+JSON.stringify(r.body));return r.body;}
async function signin(c,role,email=role+'@demo.gov',password=role+'123'){await request(c,'GET','/auth/me');const r=await request(c,'POST','/auth/login',{role:role.toUpperCase(),email,password});return r;}
async function outbox(id){const dir=path.join(__dirname,'../.runtime/outbox');const files=fs.readdirSync(dir).map(n=>JSON.parse(fs.readFileSync(path.join(dir,n),'utf8')));return files.find(m=>m.session===id);}
async function sequence(c,s,fixtures,{wrong=false}={}){let state=await request(c,'POST','/identity/sessions/'+s.id+'/camera',{},200,s.token);let step=0;while(state.state==='CAMERA_STARTED'&&step++<6){const action=state.challenge.action;const f=wrong?'WRONG':action;const frames=action==='BLINK'?fixtures.BLINK:fixtures[f].slice(action==='FORWARD'&&step>1?3:0,action==='FORWARD'&&step>1?6:3);state=await request(c,'POST','/identity/sessions/'+s.id+'/frames',{nonce:state.challenge.nonce,frames},200,s.token);if(wrong&&state.feedback==='FOLLOW_CHALLENGE')return state;equal(state.accepted,true,'challenge should accept synthetic pose '+action+' '+JSON.stringify(state).slice(0,400));if(action==='BLINK'){blinkSteps++;equal(state.blink.count,3,'three synthetic blinks are measured');equal(state.blink.trace.length,fixtures.BLINK.length);}}return state;}
let blinkSteps=0;
// Drives a session to its BLINK step, passing the steps before it.
async function untilBlink(c,s,fixtures){let state=await request(c,'POST','/identity/sessions/'+s.id+'/camera',{},200,s.token);while(state.challenge.action!=='BLINK'){const action=state.challenge.action;state=await request(c,'POST','/identity/sessions/'+s.id+'/frames',{nonce:state.challenge.nonce,frames:action==='FORWARD'?fixtures.BYSTANDER.slice(0,3):fixtures[action].slice(0,3),region:{cx:.5,cy:.487,rx:.21,ry:.36}},200,s.token);equal(state.accepted,true,'a bystander outside the oval does not fail '+action);}return state;}
(async()=>{const ctx=await setup();const MFA=require('../server/identity/mfa.cjs');try{
 const citizen=new Client(ctx.base),other=new Client(ctx.base),admin=new Client(ctx.base),officer=new Client(ctx.base),guest=new Client(ctx.base);
 await signin(citizen,'citizen');await signin(admin,'admin');await signin(officer,'officer');await request(guest,'GET','/auth/me');
 await request(guest,'GET','/identity/overview',undefined,401);await request(citizen,'GET','/verification/control-center',undefined,403);await request(officer,'GET','/verification/agents',undefined,403);
 const apps=await request(citizen,'GET','/applications?limit=12');ok(apps.rows.length>0);ok(apps.rows[0].service.docs);ok(apps.rows[0].citizen.full_name);await request(citizen,'GET','/applications/999999',undefined,404);
 for(const part of ['overview','monthly','daily','status','departments','services','officers','decisions','processing','activity','grievances','sla','users'])await request(admin,'GET','/analytics/'+part);
 const s=await request(citizen,'POST','/identity/sessions',{kind:'ENROLLMENT',dob:'1996-01-01'},201);await request(citizen,'POST','/identity/sessions/'+s.id+'/complete',{},409,s.token);await request(other,'GET','/auth/me');await request(other,'GET','/identity/sessions/'+s.id,undefined,404,s.token);await request(citizen,'POST','/identity/sessions/'+s.id+'/consent',{accepted:true,age_accepted:true,policy_version:s.policy_version},200,s.token);
 const fixtures=JSON.parse(fs.readFileSync(path.join(__dirname,'../.test-tools/identity/face-inputs.json'),'utf8'));
 const enrolled=await sequence(citizen,s,fixtures);equal(enrolled.state,'VERIFIED');const result=await request(citizen,'POST','/identity/sessions/'+s.id+'/complete',{},200,s.token);ok(/^XXXX XXXX \d{4}$/.test(result.aadhaar));await request(citizen,'POST','/identity/sessions/'+s.id+'/complete',{},409,s.token);const overview=await request(citizen,'GET','/identity/overview');equal(overview.face_enrolled,true);
 // Real frames are evaluated; an empty image and duplicate stills cannot advance.
 const bad=await request(citizen,'POST','/identity/sessions',{kind:'VERIFICATION'},201);await request(citizen,'POST','/identity/sessions/'+bad.id+'/consent',{accepted:true,age_accepted:true,policy_version:bad.policy_version},200,bad.token);const cam=await request(citizen,'POST','/identity/sessions/'+bad.id+'/camera',{},200,bad.token);await request(citizen,'POST','/identity/sessions/'+bad.id+'/frames',{nonce:cam.challenge.nonce,frames:Array(3).fill(fixtures.FORWARD[0])},400,bad.token);await request(citizen,'POST','/identity/sessions/'+bad.id+'/frames',{nonce:cam.challenge.nonce,frames:fixtures.FORWARD.slice(0,3),region:{cx:'centre'}},400,bad.token);const rejected=await request(citizen,'POST','/identity/sessions/'+bad.id+'/frames',{nonce:cam.challenge.nonce,frames:fixtures.BLACK.slice(0,3)},200,bad.token);equal(rejected.accepted,false);await request(citizen,'POST','/identity/sessions/'+bad.id+'/frames',{nonce:cam.challenge.nonce,frames:fixtures.FORWARD.slice(0,3)},409,bad.token);const crowded=await request(citizen,'POST','/identity/sessions/'+bad.id+'/frames',{nonce:rejected.challenge.nonce,frames:fixtures.CROWDED.slice(0,3)},200,bad.token);equal(crowded.feedback,'MULTIPLE_FACES','two faces inside the oval are refused');await request(citizen,'DELETE','/identity/sessions/'+bad.id,undefined,200,bad.token);
 // Blink liveness: staring frames fail, pose-sized batches are refused, a real blink sequence passes.
 equal(blinkSteps,1,'every session includes one blink step');const enrolledHistory=await request(citizen,'GET','/identity/history');equal(enrolledHistory.find(h=>h.id===s.id).blink_count,3,'blink count is recorded');
 const blinkSession=await request(citizen,'POST','/identity/sessions',{kind:'VERIFICATION'},201);await request(citizen,'POST','/identity/sessions/'+blinkSession.id+'/consent',{accepted:true,age_accepted:true,policy_version:blinkSession.policy_version},200,blinkSession.token);
 let blinkState=await untilBlink(citizen,blinkSession,fixtures);const blinkStep=blinkState.challenge.step;
 await request(citizen,'POST','/identity/sessions/'+blinkSession.id+'/frames',{nonce:blinkState.challenge.nonce,frames:fixtures.LEFT.slice(3,6)},400,blinkSession.token);
 await request(citizen,'POST','/identity/sessions/'+blinkSession.id+'/frames',{nonce:blinkState.challenge.nonce,frames:[...fixtures.STARE,...fixtures.BLINK]},400,blinkSession.token);
 blinkState=await request(citizen,'POST','/identity/sessions/'+blinkSession.id+'/frames',{nonce:blinkState.challenge.nonce,frames:fixtures.STARE},200,blinkSession.token);
 equal(blinkState.accepted,false);equal(blinkState.feedback,'BLINK_NOT_SEEN');equal(blinkState.blink.count,0);equal(blinkState.challenge.step,blinkStep,'a failed blink check repeats the step');ok(blinkState.blink.trace.every(v=>v===1),'staring frames stay open');
 blinkState=await request(citizen,'POST','/identity/sessions/'+blinkSession.id+'/frames',{nonce:blinkState.challenge.nonce,frames:[...fixtures.CLOSED,...fixtures.WRONG]},200,blinkSession.token);
 equal(blinkState.accepted,false,'closed eyes followed by a different open-eyed person do not pass');
 blinkState=await request(citizen,'POST','/identity/sessions/'+blinkSession.id+'/frames',{nonce:blinkState.challenge.nonce,frames:fixtures.BLINK},200,blinkSession.token);
 equal(blinkState.accepted,true);equal(blinkState.blink.count,3);ok(blinkState.challenge.step>blinkStep,'blink step advanced');
 await request(citizen,'DELETE','/identity/sessions/'+blinkSession.id,undefined,200,blinkSession.token);
 const forward=(await B.analyze(fixtures.FORWARD.slice(0,3))).results.map(x=>x.embedding),wrong=(await B.analyze(fixtures.WRONG.slice(0,3))).results.map(x=>x.embedding);ok(!B.matches(wrong,B.mean(forward)),'real model must reject the different synthetic subject');
 // Assigned agents require approval, MFA, a reviewed device and both one-time visit codes.
 const agentClient=new Client(ctx.base);await request(agentClient,'GET','/auth/me');
 const staff=await request(admin,'POST','/verification/agents',{name:'Synthetic Field Agent',email:'field-agent@example.test',password:'AgentTest123!',certification:'Academic synthetic test certification',authorized_until:'2027-12-31'},201);
 await request(agentClient,'POST','/auth/login',{email:'field-agent@example.test',password:'AgentTest123!',role:'VERIFICATION_AGENT'},403);
 await request(admin,'PATCH','/verification/agents/'+staff.id,{status:'APPROVED'});await signin(agentClient,'verification_agent','field-agent@example.test','AgentTest123!');
 await request(agentClient,'GET','/applications',undefined,403);await request(agentClient,'GET','/users',undefined,403);
 const appt=await request(citizen,'POST','/verification/appointments',{location_type:'CENTER',location:'Synthetic testing center, Academic Road',scheduled_date:new Date().toISOString().slice(0,10),time_window:'10:00 - 12:00',consent:true},201);
 await request(admin,'POST','/verification/appointments/'+appt.id+'/assign',{agent_id:staff.id});
 await request(agentClient,'POST','/verification/appointments/'+appt.id+'/advance',{},403);
 const agentMfa=await request(agentClient,'POST','/security/mfa/enroll',{});const agentCodes=await request(agentClient,'POST','/security/mfa/activate',{code:MFA.totp(agentMfa.secret)});
 await request(agentClient,'POST','/verification/devices',{label:'Synthetic camera test device',capabilities:{secure_context:true,screen_lock_confirmed:true},frames:fixtures.FORWARD.slice(0,1)},201);
 const devices=await request(agentClient,'GET','/verification/devices');await request(agentClient,'POST','/verification/appointments/'+appt.id+'/advance',{},403);
 await request(admin,'PATCH','/verification/devices/'+devices[0].id,{status:'APPROVED'});
 equal((await request(agentClient,'POST','/verification/appointments/'+appt.id+'/advance',{})).status,'AGENT_ACCEPTED');
 equal((await request(agentClient,'POST','/verification/appointments/'+appt.id+'/advance',{})).status,'EN_ROUTE');
 const arrival=await request(agentClient,'POST','/verification/appointments/'+appt.id+'/advance',{});equal(arrival.status,'ARRIVED');ok(arrival.qr.startsWith('data:image/png;'));
 await request(citizen,'POST','/verification/appointments/'+appt.id+'/verify-agent',{token:'WRONG'},400);
 const mutual=await request(citizen,'POST','/verification/appointments/'+appt.id+'/verify-agent',{token:arrival.token});await request(citizen,'POST','/verification/appointments/'+appt.id+'/verify-agent',{token:arrival.token},409);
 await request(agentClient,'POST','/verification/appointments/'+appt.id+'/verify-appointment',{token:'WRONG'},400);
 const assisted=await request(agentClient,'POST','/verification/appointments/'+appt.id+'/verify-appointment',{token:mutual.token});
 await request(agentClient,'POST','/verification/appointments/'+appt.id+'/finish',{},409);
 await request(admin,'PATCH','/verification/devices/'+devices[0].id,{status:'REVOKED'});await request(agentClient,'POST','/identity/sessions/'+assisted.id+'/camera',{},403,assisted.token);
 await request(admin,'PATCH','/verification/devices/'+devices[0].id,{status:'APPROVED'});
 const assistedState=await sequence(agentClient,assisted,fixtures);equal(assistedState.state,'VERIFIED');
 const assistedResult=await request(agentClient,'POST','/identity/sessions/'+assisted.id+'/complete',{},200,assisted.token);ok(!assistedResult.aadhaar,'Agent must not receive citizen identifier');
 await request(agentClient,'POST','/verification/appointments/'+appt.id+'/finish',{});
 const appointmentHistory=await request(citizen,'GET','/verification/appointments/'+appt.id+'/history');ok(appointmentHistory.some(h=>h.to_status==='VERIFICATION_COMPLETED'));
 await request(agentClient,'POST','/verification/appointments/'+appt.id+'/finish',{},409);await request(officer,'GET','/verification/appointments',undefined,403);
 await request(agentClient,'POST','/security/mfa/disable',{password:'AgentTest123!',code:agentCodes.recovery_codes[0]});await request(agentClient,'POST','/verification/appointments/'+appt.id+'/advance',{},403);await request(admin,'PATCH','/verification/agents/'+staff.id,{status:'REVOKED'});await request(agentClient,'GET','/verification/appointments',undefined,401);
 // Known-device recovery without MFA; unknown devices get email step-up.
 await request(citizen,'POST','/security/devices/current/trust',{});
 const recovery=await request(citizen,'POST','/identity/sessions',{email:'citizen@demo.gov',kind:'RECOVERY'},201);await request(citizen,'POST','/identity/sessions/'+recovery.id+'/consent',{accepted:true,age_accepted:true,policy_version:recovery.policy_version},200,recovery.token);let recovered=await sequence(citizen,recovery,fixtures);if(recovered.state==='ADDITIONAL_VERIFICATION_REQUIRED'){await request(citizen,'POST','/identity/sessions/'+recovery.id+'/send-code',{},200,recovery.token);const mail=await outbox(recovery.id);await request(citizen,'POST','/identity/sessions/'+recovery.id+'/additional',{code:mail.code},200,recovery.token);}else equal(recovered.state,'VERIFIED');await request(citizen,'POST','/identity/sessions/'+recovery.id+'/complete',{},200,recovery.token);
 // MFA activation, login challenge, one-time recovery codes, legacy API cannot bypass.
 const setupMfa=await request(citizen,'POST','/security/mfa/enroll',{});ok(setupMfa.qr.startsWith('data:image/png;base64,'));const mfa=await request(citizen,'POST','/security/mfa/activate',{code:MFA.totp(setupMfa.secret)});equal(mfa.recovery_codes.length,10);
 const legacy=await other.request('POST','/api/auth/login',{email:'citizen@demo.gov',password:'citizen123',role:'citizen'});equal(legacy.status,200);equal(legacy.body.mfa_required,true);await request(other,'GET','/identity/overview',undefined,401);
 const challenge=await signin(other,'citizen');equal(challenge.mfa_required,true);await request(other,'POST','/auth/challenge',{challenge:challenge.challenge,code:'000000'},400);await request(other,'POST','/auth/challenge',{challenge:challenge.challenge,code:mfa.recovery_codes[0]});await request(other,'POST','/auth/challenge',{challenge:challenge.challenge,code:mfa.recovery_codes[0]},401);
 const recoveryMfa=await request(other,'POST','/identity/sessions',{email:'citizen@demo.gov',kind:'RECOVERY'},201);await request(other,'POST','/identity/sessions/'+recoveryMfa.id+'/consent',{accepted:true,age_accepted:true,policy_version:recoveryMfa.policy_version},200,recoveryMfa.token);const mfaState=await sequence(other,recoveryMfa,fixtures);equal(mfaState.state,'MFA_REQUIRED');await request(other,'POST','/identity/sessions/'+recoveryMfa.id+'/mfa',{code:mfa.recovery_codes[0]},400,recoveryMfa.token);await request(other,'POST','/identity/sessions/'+recoveryMfa.id+'/mfa',{code:mfa.recovery_codes[1]},200,recoveryMfa.token);await request(other,'POST','/identity/sessions/'+recoveryMfa.id+'/complete',{},200,recoveryMfa.token);
 const sessions=await request(citizen,'GET','/security/sessions');ok(sessions.length>=2);await request(citizen,'DELETE','/security/sessions/others');await request(other,'GET','/identity/overview',undefined,401);
 // Anonymous identity sessions never disclose account existence; expired sessions fail.
 const unknown=await request(guest,'POST','/identity/sessions',{email:'unknown@example.test',kind:'RECOVERY'},201);equal(unknown.state,'ACCOUNT_IDENTIFIED');await request(guest,'GET','/identity/sessions/'+unknown.id,undefined,200,unknown.token);await ctx.owner.execute('UPDATE identity_verification_sessions SET expires_at=UTC_TIMESTAMP(3)-INTERVAL 1 MINUTE WHERE id=?',[unknown.id]);await request(guest,'POST','/identity/sessions/'+unknown.id+'/consent',{accepted:true,age_accepted:true,policy_version:unknown.policy_version},409,unknown.token);
 const [logs]=await ctx.owner.execute('SELECT COUNT(*) n FROM status_logs WHERE identity_session_id=?',[s.id]);ok(logs[0].n>=7);const [secrets]=await ctx.owner.execute('SELECT template_cipher FROM face_templates WHERE user_id=?',[(await request(citizen,'GET','/auth/me')).id]);ok(!secrets[0].template_cipher.includes('embedding'));const activity=await request(citizen,'GET','/security/activity');ok(!JSON.stringify(activity).includes(setupMfa.secret));
 report('identity-api.json',{passed:true,checks,verified:['migration preservation on isolated DB','real model enrollment','blink liveness (count, staring rejection, frame limits, history)','nonce replay','state skipping','cookie binding','quality rejection','different-face rejection','no-MFA recovery','MFA recovery','MFA single-use codes','legacy MFA enforcement','session revocation','expired recovery','audit logging','approved agent and device','mutual one-time visit codes','assisted real-model completion','mid-session device revocation','agent revocation']});console.log('PASS integrated identity API:',checks,'checks');
 }finally{B.stop();await ctx.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
