/* Additional checks for live tabs, lifecycle branches, management CRUD, and charts. */
const {chromium}=require('../.test-tools/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const url=file=>pathToFileURL(path.join(root,file.split('?')[0])).href+(file.includes('?')?'?'+file.split('?')[1]:'');
const executablePath=process.env.BROWSER_PATH||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
const errors=[];
async function ready(page,file){await page.waitForFunction(file=>location.pathname.endsWith('/'+file)&&document.readyState==='complete'&&!document.querySelector('.loading')&&document.querySelector('h1'),file);}
async function login(page,role,email=role+'@demo.gov'){await page.goto(url('index.html'));await ready(page,'index.html');await page.evaluate(async({role,email})=>{await Auth.login(email,role+'123',role);},{role,email});await page.goto(url(role+'-dashboard.html'));await ready(page,role+'-dashboard.html');}
async function create(page,purpose='An application to verify additional lifecycle actions.'){return page.evaluate(async purpose=>{const user=Auth.user;return API.applications.create({service_id:3,form_data:{full_name:user.name,email:user.email,phone:user.phone,address:user.address,purpose},documents:[{label:'Identity proof',name:'identity.txt',mime:'text/plain',size:4,content:'data:text/plain;base64,'+btoa('Demo')}]});},purpose);}
async function decision(page,status){await page.locator('input[name=decision][value="'+status+'"]').check();await page.locator('[data-template="0"]').click();await page.locator('#commit-decision').click();await page.locator('[data-confirm]').click();}
(async()=>{const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});const context=await browser.newContext({viewport:{width:1280,height:960},acceptDownloads:true});await context.setOffline(true);await context.addInitScript(()=>{let api;Object.defineProperty(window,'API',{configurable:true,get:()=>api,set:v=>{api=v;api.LATENCY=0;}});});context.on('page',page=>{page.on('pageerror',err=>errors.push(err.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});});try{
  const admin=await context.newPage(),citizen=await context.newPage(),officer=await context.newPage();await login(admin,'admin');await login(citizen,'citizen');await login(officer,'officer');
  const initial=Number(await admin.locator('#analytics-content .stat strong').first().textContent()),a=await create(citizen);
  await admin.waitForFunction(n=>Number(document.querySelector('#analytics-content .stat strong').textContent)===n,initial+1);console.log('PASS: citizen submission updates a different admin tab without reload, while offline.');
  await officer.goto(url('officer-review.html?id='+a.id));await ready(officer,'officer-review.html');await decision(officer,'UNDER_REVIEW');await officer.locator('input[value=NEEDS_INFO]').waitFor();await decision(officer,'NEEDS_INFO');await officer.locator('.decision-panel').filter({hasText:'Waiting for the applicant'}).waitFor();
  await citizen.goto(url('citizen-application.html?id='+a.id));await ready(citizen,'citizen-application.html');await citizen.locator('#response').fill('The requested address information is correct and I have clarified it for the reviewing officer.');await citizen.locator('#response-form button[type=submit]').click();await citizen.locator('#response-form').waitFor({state:'detached'});assert.equal(await citizen.evaluate(id=>API.applications.get(id).then(a=>a.status),a.id),'UNDER_REVIEW');
  await citizen.locator('#withdraw').click();await citizen.locator('#withdraw-reason').fill('I no longer require this application because the supporting record has already been obtained.');await citizen.locator('#withdraw-form button[type=submit]').click();await citizen.locator('dialog').waitFor({state:'detached'});await citizen.locator('#page>.scope-bar [data-status=WITHDRAWN]').waitFor();
  const forwarded=await create(citizen);await officer.goto(url('officer-queue.html'));await ready(officer,'officer-queue.html');await officer.locator('#queue-search').fill(forwarded.reference);await officer.locator('[data-row-id="'+forwarded.id+'"]').check();await officer.locator('#bulk-assign').click();await officer.waitForFunction(()=>document.querySelector('#bulk-assign').disabled&&document.querySelector('#selection-label').textContent.startsWith('Select open'));
  await officer.locator('#queue-table a').filter({hasText:forwarded.reference}).click();await ready(officer,'officer-review.html');await decision(officer,'UNDER_REVIEW');await officer.locator('input[value=FORWARDED]').check();await officer.locator('#forward-department').selectOption('2');await officer.locator('#forward-officer option[value="6"]').waitFor({state:'attached'});await officer.locator('#forward-officer').selectOption('6');await officer.locator('[data-template="0"]').click();await officer.locator('#commit-decision').click();await officer.locator('[data-confirm]').click();await ready(officer,'officer-queue.html');
  await login(officer,'officer','officer20@demo.gov');await officer.goto(url('officer-review.html?id='+forwarded.id));await ready(officer,'officer-review.html');await decision(officer,'UNDER_REVIEW');await officer.locator('input[value=REJECTED]').waitFor();await decision(officer,'REJECTED');await officer.locator('#review-print').waitFor();await citizen.waitForFunction(async id=>(await API.applications.get(id)).status==='REJECTED',forwarded.id);console.log('PASS: information request → citizen response → withdrawal; queue assignment → forwarding to another officer → rejection.');
  await admin.goto(url('admin-departments.html'));await ready(admin,'admin-departments.html');await admin.locator('#new-department').click();await admin.locator('dialog #name').fill('Archive Desk');await admin.locator('dialog #code').fill('ARC');await admin.locator('dialog #description').fill('A temporary department for verifying catalogue management.');await admin.locator('#department-form button[type=submit]').click();await admin.locator('dialog').waitFor({state:'detached'});await admin.locator('#edit-department').click();await admin.locator('dialog #name').fill('Archive & Records');await admin.locator('#department-form button[type=submit]').click();await admin.locator('dialog').waitFor({state:'detached'});await admin.locator('#new-service').click();await admin.locator('dialog #name').fill('Archive Search');await admin.locator('dialog #description').fill('Search historical public service records through the archive desk.');await admin.locator('dialog #fee').fill('200');await admin.locator('#service-form button[type=submit]').click();await admin.locator('dialog').waitFor({state:'detached'});await admin.locator('[data-edit-service]').click();await admin.locator('dialog #fee').fill('275');await admin.locator('dialog #sla_days').fill('16');await admin.locator('dialog input[value="Address proof"]').check();await admin.locator('#service-form button[type=submit]').click();await admin.locator('dialog').waitFor({state:'detached'});await admin.locator('#service-table').filter({hasText:'16 days'}).waitFor();assert.ok((await admin.locator('#service-table').innerText()).includes('Address proof'));await admin.locator('[data-delete-service]').click();await admin.locator('[data-confirm]').click();await admin.locator('#service-table .empty').waitFor();await admin.locator('#delete-department').click();await admin.locator('[data-confirm]').click();await admin.waitForFunction(()=>!document.querySelector('.department-list').textContent.includes('Archive & Records'));
  await admin.goto(url('admin-users.html'));await ready(admin,'admin-users.html');await admin.locator('#user-search').fill('citizen1@demo.gov');await admin.locator('[data-toggle-user]').click();await admin.locator('[data-confirm]').click();await admin.locator('#user-table [data-status=WITHDRAWN]').waitFor();await admin.locator('[data-toggle-user]').click();await admin.locator('[data-confirm]').click();await admin.locator('#user-table [data-status=APPROVED]').waitFor();
  const one=await create(citizen),two=await create(citizen);await admin.goto(url('admin-applications.html'));await ready(admin,'admin-applications.html');await admin.locator('#master-search').fill(one.reference.slice(0,-1));await admin.locator('[data-row-id="'+one.id+'"]').check();await admin.locator('[data-row-id="'+two.id+'"]').check();await admin.locator('#master-assign').click();await admin.locator('#assignment-officer').selectOption('2');await admin.locator('#reassign-form button[type=submit]').click();await admin.locator('dialog').waitFor({state:'detached'});assert.equal(await admin.evaluate(id=>API.applications.get(id).then(a=>a.officer_id),one.id),2);assert.equal(await admin.evaluate(id=>API.applications.get(id).then(a=>a.officer_id),two.id),2);console.log('PASS: department and service create/edit/delete, account activation, and bulk reassignment.');
  await admin.goto(url('admin-reports.html'));await ready(admin,'admin-reports.html');await admin.locator('#report-department').selectOption('1');await admin.locator('#report-status').selectOption('SUBMITTED');await admin.locator('#report-form button[type=submit]').click();await admin.waitForFunction(()=>document.querySelector('#report-banner').textContent.includes('Revenue & Certificates · Submitted'));const total=await admin.evaluate(async()=>{const f={department_id:1,status:'SUBMITTED',from:document.querySelector('#report-from').value,to:document.querySelector('#report-to').value};return (await API.applications.list(f)).length;});assert.equal(Number(await admin.locator('#report-content .stat strong').first().textContent()),total);
  await admin.setViewportSize({width:900,height:1000});await admin.waitForTimeout(150);assert.ok(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
  await admin.evaluate(()=>{const area=UI.el('section',{id:'chart-validation',class:'grid-2'});document.querySelector('#page').append(area);const data=[{label:'A < B',value:5,second:3},{label:'Second',value:9,second:2},{label:'Third',value:7,second:4}];for(const type of ['area','line','groupedBars','stackedBars','horizontalBars','donut','gauge','sparkline']){const el=UI.el('div',{id:'test-'+type,class:'chart'});area.append(el);Charts[type](el,type==='gauge'?60:data,{series:[{key:'value',label:'First'},{key:'second',label:'Second'}]});}});assert.equal(await admin.locator('#chart-validation svg').count(),8);const before=await admin.locator('#test-line path').first().getAttribute('stroke');await admin.evaluate(()=>UI.theme('dark'));const after=await admin.locator('#test-line path').first().getAttribute('stroke');assert.notEqual(before,after);await admin.locator('#test-line [data-tip]').first().focus();await admin.locator('.chart-tooltip').filter({hasText:'A < B'}).waitFor();await admin.setViewportSize({width:390,height:844});await admin.waitForTimeout(150);assert.ok(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await admin.emulateMedia({media:'print'});await admin.pdf({path:path.join(out,'service-report.pdf'),format:'A4',printBackground:true});assert.ok(fs.statSync(path.join(out,'service-report.pdf')).size>5000);await admin.emulateMedia({media:'screen'});
  await citizen.evaluate(()=>API.users.update(Auth.user.id,{name:'Test <img src=x onerror=alert(1)>'}));await citizen.goto(url('citizen-profile.html'));await ready(citizen,'citizen-profile.html');assert.equal(await citizen.locator('img[src=x]').count(),0);assert.ok((await citizen.locator('.profile-head').innerText()).includes('<img src=x'));const csvPromise=admin.waitForEvent('download');await admin.evaluate(()=>UI.csv('formula-safety',[{value:'=1+1',name:'<test>'}]));const csv=await csvPromise;await csv.saveAs(path.join(out,'formula-safety.csv'));assert.ok(fs.readFileSync(path.join(out,'formula-safety.csv'),'utf8').includes("'=1+1"));
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'interactions.json'),JSON.stringify({timestamp:new Date().toISOString(),crossTab:true,lifecycleBranches:true,crud:true,bulkAssignment:true,reportScope:true,chartTypes:8,tablet:true,printPDF:true,escaping:true,csvFormulaSafety:true,consoleErrors:errors},null,2));console.log('PASS: report scope, tablet resize, eight chart types, tooltips, theme redraw, PDF, HTML escaping, CSV formula safety. Zero browser errors.');
}finally{await context.close();await browser.close();}})().catch(err=>{console.error(err);console.error(errors);process.exitCode=1;});
