'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('../.test-tools/node_modules/playwright'),{setup,Client,report}=require('./live-support.cjs');
let checks=0;const check=(v,m)=>{checks++;assert.ok(v,m);};
const fixtures=JSON.parse(fs.readFileSync(path.join(__dirname,'../.test-tools/identity/face-inputs.json'),'utf8'));
async function fillLogin(page,base,code){await page.goto(base+'/login');await page.getByText('Development test accounts',{exact:true}).click();await page.getByRole('button',{name:'Fill Citizen demo'}).click();await page.getByRole('button',{name:'Sign in',exact:true}).click();if(code){await page.getByLabel('Authenticator or recovery code').fill(code);await page.getByRole('button',{name:'Verify and sign in'}).click();}await page.waitForURL('**/citizen');}
async function consent(page){await page.getByLabel(/I consent to temporary face/).check();await page.getByLabel(/I consent to age-consistency/).check();await page.getByRole('button',{name:'Accept and continue'}).click();}
let blinkChecked=0;const B=require('../server/identity/biometrics.cjs');
async function captures(page){await page.getByRole('button',{name:'Start camera',exact:true}).click();await page.waitForTimeout(200);console.log('Camera start feedback:',await page.locator('.alert.danger').allTextContents());const steps=B.health().blink?5:4;for(let i=0;i<steps;i++){const capture=page.getByRole('button',{name:'Start this step',exact:true});await capture.waitFor();const response=page.waitForResponse(r=>r.url().endsWith('/frames')&&r.request().method()==='POST');await capture.click();const r=await response;if(r.status()!==200)console.log('Frame request failed:',r.status(),await r.text());check(r.status()===200,'frame request succeeds');const frameResult=await r.json();const area=r.request().postDataJSON().region;check(area&&Math.abs(area.cx-0.5)<0.02&&area.rx>0.1&&area.rx<0.4&&area.ry>0.2&&area.ry<0.6,'the on-screen oval is sent as the verification area '+JSON.stringify(area));console.log('Camera step',i,frameResult.state,frameResult.feedback);check(frameResult.accepted,'server accepts measured synthetic pose');if(frameResult.blink){blinkChecked++;check(frameResult.blink.count>=2,'blink step measures blinks');await page.locator('.blink-signature.is-ok').waitFor();check(await page.locator('.blink-signature .blink-dip').count()===frameResult.blink.count,'blink signature marks each counted blink');}}if(steps===5)check(blinkChecked>0,'blink step ran in the browser');check(await page.evaluate(()=>window.__tracks.every(t=>t.readyState==='ended')),'camera stops after final capture');}
(async()=>{const ctx=await setup(),MFA=require('../server/identity/mfa.cjs'),B=require('../server/identity/biometrics.cjs');let browser;const errors=[],expectedErrors=[];
try{
 browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 const context=await browser.newContext({acceptDownloads:true,colorScheme:'light'});
 await context.addInitScript(f=>{
  const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);window.__tracks=[];
  navigator.mediaDevices.getUserMedia=async options=>{const s=await original(options?.video?{...options,video:{...options.video,width:{exact:640},height:{exact:480}}}:options);window.__tracks.push(...s.getTracks());return s;};
  // Test-only adapter: fictional portrait frames exercise the real server model.
  // This is not evidence of physical-camera liveness or presentation-attack resistance.
  const native=HTMLCanvasElement.prototype.toDataURL,counters={},images=Object.fromEntries(['FORWARD','LEFT','RIGHT','CLOSER','BLINK'].map(k=>[k,f[k].map(src=>Object.assign(new Image(),{src}))]));
  HTMLCanvasElement.prototype.toDataURL=function(...args){if(this.width!==640||this.height!==480)return native.apply(this,args);const text=document.querySelector('.camera-instruction')?.textContent||'';const action=text.startsWith('Blink')?'BLINK':text.includes('your left')?'LEFT':text.includes('your right')?'RIGHT':text.includes('closer')?'CLOSER':'FORWARD';const i=counters[action]||0;counters[action]=i+1;const img=images[action][i%images[action].length],c=document.createElement('canvas');c.width=640;c.height=480;const x=c.getContext('2d');x.drawImage(img,0,0);x.fillStyle='#000';x.fillRect(4+(i%40)*8,4,6,6);return native.call(c,'image/jpeg',0.92);};
 },fixtures);
 const page=await context.newPage();page.setDefaultTimeout(20000);let expected=false;
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')(expected?expectedErrors:errors).push(m.text());});
 await page.goto(ctx.base+'/login');check(await page.getByLabel('Language',{exact:true}).locator('option').count()===23,'English and 22 scheduled locales');
 await page.getByLabel('Language',{exact:true}).selectOption('hi');await page.getByText('English is used where reviewed translations are not yet available.').waitFor();await page.getByLabel('Language',{exact:true}).selectOption('en');
 await page.getByText('Development test accounts',{exact:true}).click();await page.getByRole('button',{name:'Fill Citizen demo'}).click();await page.getByRole('button',{name:'Show password',exact:true}).click();check(await page.getByLabel('Password',{exact:true}).getAttribute('type')==='text','password show');await page.getByRole('button',{name:'Hide password',exact:true}).click();check(await page.getByLabel('Password',{exact:true}).getAttribute('type')==='password','password hide');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/citizen');
 const themeSaved=page.waitForResponse(r=>r.url().endsWith('/preferences/theme')&&r.request().method()==='PUT');await page.getByRole('button',{name:'Switch to dark mode'}).click();await themeSaved;await page.reload();await page.getByRole('button',{name:'Switch to light mode'}).waitFor();check(await page.evaluate(()=>document.documentElement.dataset.theme)==='dark','manual theme survives reload through API');const lightSaved=page.waitForResponse(r=>r.url().endsWith('/preferences/theme')&&r.request().method()==='PUT');await page.getByRole('button',{name:'Switch to light mode'}).click();await lightSaved;
 await page.goto(ctx.base+'/security');await page.getByRole('button',{name:'Set up MFA',exact:true}).click();const secret=await page.getByLabel('Manual setup key').inputValue();check(secret.length>=20,'real MFA secret issued');await page.getByLabel('Code from your authenticator').fill(MFA.totp(secret));await page.getByRole('button',{name:'Activate MFA',exact:true}).click();const pre=page.locator('.recovery-codes pre');await pre.waitFor();const codes=(await pre.innerText()).trim().split('\n');check(codes.length===10,'ten one-time recovery codes');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download codes'}).click();check(fs.readFileSync(await (await download).path(),'utf8').split('\n').length===10,'real recovery-code download');await page.getByRole('button',{name:'I saved my codes'}).click();
 await page.getByRole('button',{name:'Trust this device'}).click();await page.getByText('Trusted',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Account menu'}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/login*');await fillLogin(page,ctx.base,codes[0]);checks++;
 await page.goto(ctx.base+'/identity/face');await page.getByLabel('Synthetic date of birth').fill('1996-01-01');await page.getByRole('button',{name:'Start face enrollment'}).click();await consent(page);await captures(page);await page.getByRole('button',{name:'Complete verification'}).click();await page.getByRole('heading',{name:'Verification completed'}).waitFor();check((await page.locator('main').innerText()).includes('XXXX XXXX'),'masked sandbox result');
 await page.goto(ctx.base+'/recover-identity');await page.getByLabel('Registered email address').fill('citizen@demo.gov');await page.getByRole('button',{name:'Continue',exact:true}).click();await consent(page);await captures(page);await page.getByLabel('Authenticator or recovery code').fill(codes[1]);await page.getByRole('button',{name:'Verify code',exact:true}).click();await page.getByRole('button',{name:'Complete verification'}).click();await page.getByRole('heading',{name:'Identity verified'}).waitFor();checks++;
 // Permission denial and cancellation use the actual component and state machine.
 await page.goto(ctx.base+'/identity/face');await page.getByLabel('Synthetic date of birth').fill('1996-01-01');await page.getByRole('button',{name:'Start face enrollment'}).click();await consent(page);await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Test permission denied','NotAllowedError');};});await page.getByRole('button',{name:'Start camera'}).click();await page.getByRole('alert').filter({hasText:'Camera permission was denied'}).waitFor();check(await page.getByRole('link',{name:'Request in-person verification / visit a center'}).count()===1,'accessible camera fallback');await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Start face enrollment'}).waitFor();
 // Appointment form, persisted booking, and cancellation.
 await page.goto(ctx.base+'/identity/appointments');await page.getByLabel('Address or agreed center location').fill('Synthetic Academic Test Center');await page.getByLabel(/I consent to sharing this visit/).check();await page.getByRole('button',{name:'Request appointment'}).click();await page.getByText('Synthetic Academic Test Center',{exact:true}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByText('Cancelled',{exact:true}).waitFor();checks++;
 // Expire this account's sessions on the test owner connection only.
 await ctx.owner.execute("UPDATE sessions s JOIN users u ON u.id=s.user_id SET s.expires_at=UTC_TIMESTAMP(3)-INTERVAL 1 MINUTE WHERE u.email='citizen@demo.gov'");expected=true;await page.getByRole('link',{name:'Security',exact:true}).first().click();await page.waitForURL('**/login?expired=1');await page.getByText('Your session expired or was revoked. Sign in again to continue.').waitFor();checks++;
 // Network errors are explicit; login never succeeds offline.
 await page.route('**/api/portal/auth/login',r=>r.abort('failed'));await page.getByText('Development test accounts',{exact:true}).click();await page.getByRole('button',{name:'Fill Citizen demo'}).click();await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('alert').filter({hasText:'Cannot connect to the server'}).waitFor();checks++;await page.unroute('**/api/portal/auth/login');
 await context.close();
 // Actual local recovery delivery -> reset page -> new password login.
 const c=new Client(ctx.base),email='reset-browser-'+Date.now()+'@example.test';await c.request('GET','/api/portal/auth/me');const registered=await c.request('POST','/api/portal/auth/register',{full_name:'Synthetic Reset User',email,password:'BeforeReset123!',phone:'9876543210',address:'42 Academic Test Road',city:'Hyderabad'});check(registered.status===201,'reset fixture registered');
 const resetContext=await browser.newContext(),resetPage=await resetContext.newPage();resetPage.setDefaultTimeout(20000);resetPage.on('pageerror',e=>errors.push(e.message));resetPage.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await resetPage.goto(ctx.base+'/forgot-password');await resetPage.getByLabel('Email address').fill(email);await resetPage.getByRole('button',{name:'Prepare recovery instructions'}).click();await resetPage.waitForTimeout(500);console.log('Recovery page feedback:',await resetPage.locator('.alert').allTextContents());await resetPage.getByText(/If the account can receive recovery instructions/).waitFor();const outbox=path.join(__dirname,'../.runtime/outbox'),mail=fs.readdirSync(outbox).map(n=>JSON.parse(fs.readFileSync(path.join(outbox,n),'utf8'))).find(m=>m.to===email&&m.url);check(!!mail,'local recovery message created');const token=new URL(mail.url).searchParams.get('token');await resetPage.goto(ctx.base+'/reset-password?token='+token);await resetPage.getByLabel('New password',{exact:true}).fill('AfterReset123!');await resetPage.getByRole('button',{name:'Update password'}).click();await resetPage.getByText('Your password was updated. Sign in with your new password.').waitFor();await resetPage.goto(ctx.base+'/login');await resetPage.getByLabel('Email address',{exact:true}).fill(email);await resetPage.getByLabel('Password',{exact:true}).fill('AfterReset123!');await resetPage.getByRole('button',{name:'Sign in',exact:true}).click();await resetPage.waitForURL('**/citizen');checks++;await resetContext.close();
 assert.deepEqual(errors,[]);report('security-browser.json',{passed:true,checks,errors,expectedNetworkOrExpiryErrors:expectedErrors.length,verified:['language fallback','password reveal','MFA QR/manual enrollment','recovery-code download','MFA login','trusted device','browser camera protocol with fictional frames and real inference','blink step with signature waveform','masked recovery with MFA','camera cleanup','permission denial','appointment booking and cancellation','expired session','network failure','password-reset delivery and sign-in'],limitation:'Camera input is automated synthetic media, not a physical-camera or spoof-resistance study'});console.log('PASS security browser:',checks,'checks');
}finally{B.stop();if(browser)await browser.close();await ctx.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
