const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('../../.test-tools/node_modules/playwright');
const base=process.env.AMAP_REACT_URL||'http://127.0.0.1:4173';
async function ready(page){await page.locator('main h1').first().waitFor();await page.waitForFunction(()=>!document.querySelector('[aria-label="Loading records"]'),null,{timeout:15000});}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),measurements=[],external=[],errors=[];try{for(const role of ['Admin','Officer']){const context=await browser.newContext(),page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(base))external.push(r.url());});page.on('framenavigated',f=>{if(f===page.mainFrame())console.log('Performance:',f.url());});await page.goto(base+'/login');await page.getByRole('button',{name:'Fill '+role+' demo'}).click();await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>u.pathname!=='/login');
for(const route of role==='Admin'?['/admin/applications','/admin/reports']:['/officer/queue']){let start=Date.now();await page.goto(base+route);await ready(page);const load=Date.now()-start;console.log('Loaded',route,load);
if(route.includes('reports')){start=Date.now();await page.getByLabel('Date range',{exact:true}).selectOption('all');await page.waitForFunction(()=>!document.body.innerText.includes('Updating report…'));await page.getByLabel('Department',{exact:true}).selectOption('1');await page.waitForFunction(()=>!document.body.innerText.includes('Updating report…'));measurements.push({route,loadMs:load,scopeChangeMs:Date.now()-start});}
else{start=Date.now();await page.getByLabel('Search applications',{exact:true}).last().fill('Income');await page.waitForTimeout(200);await page.waitForFunction(()=>!document.querySelector('.table-wrap')?.parentElement.hasAttribute('aria-busy')||document.querySelector('.table-wrap')?.parentElement.getAttribute('aria-busy')==='false');const search=Date.now()-start;console.log('Searched',route,search);assert.ok((await page.locator('tbody').innerText()).includes('Income'));
start=Date.now();await page.getByLabel('Sort order').selectOption('submitted_at:asc');await page.waitForTimeout(150);await page.waitForFunction(()=>document.querySelector('.table-wrap')?.parentElement.getAttribute('aria-busy')==='false');const sort=Date.now()-start;console.log('Sorted',route,sort);
const next=page.getByRole('button',{name:'Next page'});let pagination=null;if(await next.isEnabled()){const first=await page.locator('tbody tr').first().innerText();start=Date.now();await next.click();await page.waitForFunction(old=>document.querySelector('tbody tr')?.innerText!==old,first);pagination=Date.now()-start;}
measurements.push({route,loadMs:load,searchMs:search,sortMs:sort,paginationMs:pagination,rowsRendered:await page.locator('tbody tr').count()});}
await page.screenshot({path:path.resolve(__dirname,'../../test-results/phase2-'+route.slice(1).replaceAll('/','-')+'.png'),fullPage:true});
}
console.log('Checking reading preferences');await page.goto(base+'/profile');await ready(page);console.log('Ready to enlarge text');await page.getByRole('button',{name:'Use larger text',exact:true}).click();console.log('Text enlarged');await page.getByRole('button',{name:'Use high contrast',exact:true}).click();console.log('Contrast enabled');await page.setViewportSize({width:390,height:960});console.log('Mobile viewport set');await page.reload({timeout:15000});console.log('Reloaded');await ready(page);const preferences=await page.evaluate(()=>({text:document.documentElement.dataset.text,contrast:document.documentElement.dataset.contrast,width:innerWidth,scroll:document.documentElement.scrollWidth}));console.log('Reading preferences',preferences);assert.equal(preferences.text,'large');assert.equal(preferences.contrast,'high');assert.ok(preferences.scroll<=preferences.width+1);await context.close();}
assert.deepEqual(external,[]);assert.deepEqual(errors,[]);for(const result of measurements){assert.ok(result.loadMs<10000);for(const key of ['searchMs','sortMs','paginationMs','scopeChangeMs'])if(result[key]!=null)assert.ok(result[key]<3000,result.route+' '+key+' too slow');}fs.writeFileSync(path.resolve(__dirname,'../../test-results/react-performance.json'),JSON.stringify({datasetApplications:6006,measurements,externalRequests:external,errors,readingPreferencesPersist:true},null,2));console.log(JSON.stringify(measurements,null,2));}catch(e){console.error('Performance failure:',e);throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
