import {useState} from 'react';
import {useParams} from 'react-router';
import API from '../../data/api.js';
import useApi from '../../hooks/useApi.js';
import {useAuth} from '../../context/AuthContext.jsx';
import {useToast} from '../../context/ToastContext.jsx';
import {Alert,ApiState,Button,ButtonLink,Card,Dropzone,Field,Modal,PageHead,Progress,Timeline,useConfirm} from '../../components/ui/index.jsx';
import {ApplicationFields,DocumentList} from '../../components/ApplicationRecord.jsx';
import {printApplication} from '../../lib/print.jsx';
export default function Application(){const {id}=useParams(),{user}=useAuth(),toast=useToast(),confirm=useConfirm(),[upload,setUpload]=useState(false),[files,setFiles]=useState([]),[remarks,setRemarks]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const state=useApi(async()=>{const application=await API.applications.get(id);const [documents,logs]=await Promise.all([API.applications.documents(application.id),API.applications.logs(application.id)]);return {application,documents,logs};},[id]);const a=state.data?.application;
  async function withdraw(){if(await confirm({title:'Withdraw this application?',message:'The department will stop reviewing this request. Your application and its history will remain visible.',confirmLabel:'Withdraw application',danger:true})){setBusy(true);try{await API.applications.transition(a.id,'WITHDRAWN',user,'Applicant requested withdrawal of this open application.');toast('Application withdrawn.');}catch(e){toast(e.message,'error');}finally{setBusy(false);}}}
  async function save(){setBusy(true);setError('');try{if(files.length)await API.applications.addDocuments(a.id,files);if(a.status==='NEEDS_INFO')await API.applications.transition(a.id,'UNDER_REVIEW',user,remarks);setUpload(false);setFiles([]);setRemarks('');toast(a.status==='NEEDS_INFO'?'Response sent for review.':'Documents uploaded.');state.refetch();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <ApiState state={state}>{a&&<><PageHead title={a.service.name} lead={a.ref}><ButtonLink to="/citizen/applications" variant="outline">All applications</ButtonLink><Button variant="outline" icon="print" onClick={()=>{try{printApplication(a);}catch(e){toast(e.message,'error');}}}>Print acknowledgment</Button>{a.status==='APPROVED'&&<Button onClick={()=>{try{printApplication(a,true);}catch(e){toast(e.message,'error');}}}>Print sample certificate</Button>}</PageHead><div className="dash-grid"><div className="col-8 stack"><Card title="Application details"><Progress application={a}/>{a.remarks&&<div className="mb-5"><Alert type={a.status==='REJECTED'?'danger':a.status==='NEEDS_INFO'?'warning':'info'}>{a.remarks}</Alert></div>}<ApplicationFields application={a}/></Card><Card title="Uploaded documents" actions={a.isOpen&&<Button variant="outline" onClick={()=>setUpload(true)}>{a.status==='NEEDS_INFO'?'Respond with information':'Add documents'}</Button>}><DocumentList documents={state.data.documents}/></Card>{a.isOpen&&<Card title="Manage this request"><p className="muted mb-4">You can withdraw an open application if you no longer need the service.</p><Button variant="outline" busy={busy} onClick={withdraw}>Withdraw application</Button></Card>}</div><div className="col-4 stack"><Card title="Application timeline"><Timeline logs={state.data.logs}/></Card><Card title="Need help with this request?"><p className="muted mb-4">File a grievance for the department to review.</p><ButtonLink to={'/citizen/grievances?about='+encodeURIComponent(a.ref)} variant="outline">File a grievance</ButtonLink><p className="hint mt-4">{a.department.name} · Academic demonstration</p></Card></div></div>{upload&&<Modal title={a.status==='NEEDS_INFO'?'Respond to the officer':'Add supporting documents'} busy={busy} onClose={()=>{if(!busy)setUpload(false);}} actions={<><Button variant="outline" onClick={()=>setUpload(false)} disabled={busy}>Cancel</Button><Button busy={busy} disabled={a.status==='NEEDS_INFO'?remarks.trim().length<20:!files.length} onClick={save}>{a.status==='NEEDS_INFO'?'Send response':'Upload documents'}</Button></>}>{error&&<Alert type="danger">{error}</Alert>}{a.status==='NEEDS_INFO'&&<Field label="Your response" as="textarea" value={remarks} onChange={e=>setRemarks(e.target.value)} minLength={20} hint="Explain your response in at least 20 characters."/>}<Dropzone files={files} onChange={setFiles} requiredDocs={a.service.docs}/></Modal>}</>}</ApiState>;}
