'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {pool,rows,transaction,normalize}=require('../db.cjs'),S=require('../security.cjs'),P=require('../passwords.cjs'),V=require('../validation.cjs'),R=require('../repository.cjs'),{config}=require('../config.cjs');
const C=require('./crypto.cjs'),MFA=require('./mfa.cjs'),Risk=require('./risk.cjs'),Audit=require('./audit.cjs');
let dummy;
async function signals(req,userId){const failures=await rows(pool,"SELECT event,COUNT(*) n FROM security_events WHERE user_id=? AND created_at>UTC_TIMESTAMP(3)-INTERVAL 30 MINUTE AND outcome='FAILURE' GROUP BY event",[userId]);const count=e=>Number(failures.find(r=>r.event===e)?.n||0);const [device]=await rows(pool,'SELECT * FROM trusted_devices WHERE user_id=? AND token_hash=? AND revoked_at IS NULL',[userId,C.hash(req.deviceToken)]);req.device=device||null;req.network=await require('./network.cjs').lookup(req.ip);const [previous]=await rows(pool,"SELECT country,region,metadata,created_at FROM security_events WHERE user_id=? AND event='LOGIN_SUCCESS' ORDER BY created_at DESC LIMIT 1",[userId]);return Risk.assess({...req.network,...require('./network.cjs').travel(req.network,previous),trusted:!!device?.trusted,failedPasswords:count('LOGIN_FAILURE'),failedMfa:count('MFA_FAILED'),failedRecovery:count('FACE_REJECTED'),failedLiveness:count('LIVENESS_FAILED')});}
async function device(req,res,user,c){const hash=C.hash(req.deviceToken);let [d]=await rows(c,'SELECT * FROM trusted_devices WHERE token_hash=? AND user_id=?',[hash,user.id]);
 if(!d){const id=crypto.randomUUID();await c.execute('INSERT INTO trusted_devices(id,user_id,token_hash,browser,platform) VALUES(?,?,?,?,?)',[id,user.id,hash+'' /* unique cookie rotates across accounts below */,String(req.get('User-Agent')||'Unknown browser').slice(0,100),String(req.get('Sec-CH-UA-Platform')||'').slice(0,80)]);d={id,trusted:false};}
 await c.execute('UPDATE trusted_devices SET last_seen=UTC_TIMESTAMP(3) WHERE id=?',[d.id]);req.device=d;
}
async function login(req,res,portal=false){const d=V.fields(req.body,['email','password','role']),email=V.email(d.email),password=V.text(d.password,'Password',1,100),role=String(d.role||'').toLowerCase();const [u]=await rows(pool,'SELECT * FROM users WHERE email=?',[email]);dummy||=P.hash(C.token());const correct=await P.verify(password,u?.password_hash||await dummy);
 if(!correct||!u?.active||role&&u.role!==role){await Audit.event(req,'LOGIN_FAILURE','FAILURE',{},pool,u?.id);V.fail('Email, password, or selected role is incorrect.',401);}
 if(u.role==='verification_agent'){const [a]=await rows(pool,"SELECT user_id FROM verification_agents WHERE user_id=? AND status='APPROVED' AND authorized_until>=UTC_DATE()",[u.id]);if(!a)V.fail('This account is not authorized to sign in.',403);}
 req.risk=await signals(req,u.id);if(req.risk.level==='CRITICAL'){await Audit.event(req,'LOGIN_BLOCKED','BLOCKED',{},pool,u.id);V.fail('Sign-in is temporarily restricted. Use account recovery or contact support.',429);}
 const [m]=await rows(pool,'SELECT enabled FROM mfa_methods WHERE user_id=?',[u.id]);
 if(m?.enabled){const token=C.token();await pool.execute('INSERT INTO auth_challenges(token_hash,user_id,purpose,device_hash,expires_at) VALUES(?,?,?,?,?)',[C.hash(token),u.id,'LOGIN',C.hash(req.deviceToken),new Date(Date.now()+5*60000)]);return {mfa_required:true,challenge:token,expires_in:300};}
 if(req.risk.level==='HIGH')V.fail('Use identity recovery or an existing trusted session to continue.',403);
 await completeLogin(req,res,u,false);return portal?{user:portalUser(u)}:S.safeUser(u);
}
async function completeLogin(req,res,u,mfa){await transaction(async c=>{const [locked]=await rows(c,'SELECT * FROM users WHERE id=? FOR UPDATE',[u.id]);if(!locked?.active||locked.password_hash!==u.password_hash)V.fail('Please sign in again.',401);
 // One browser cookie may be used by multiple local demo accounts; bind by user.
 const [other]=await rows(c,'SELECT id FROM trusted_devices WHERE token_hash=? AND user_id<>?',[C.hash(req.deviceToken),u.id]);if(other){req.deviceToken=C.token();res.cookie('amap-device',req.deviceToken,{...S.cookieOptions,maxAge:90*86400000});}
 await device(req,res,u,c);await S.issueSession(req,res,u,c,{deviceId:req.device.id,mfa});await Audit.event(req,'LOGIN_SUCCESS','SUCCESS',{mfa},c,u.id);
 if(!req.device.trusted)await R.notify(c,u.id,null,'Sign-in from an untrusted device','Review Login Activity in Security if this was not you.');});}
async function challenge(req,res){const d=V.fields(req.body,['challenge','code']);const hash=C.hash(V.text(d.challenge,'Challenge',64,64));const [row]=await rows(pool,'SELECT * FROM auth_challenges WHERE token_hash=?',[hash]);if(!row||row.purpose!=='LOGIN'||row.used_at||row.attempts>=5||new Date(row.expires_at)<new Date()||row.device_hash!==C.hash(req.deviceToken))V.fail('This sign-in challenge expired. Sign in again.',401);await pool.execute('UPDATE auth_challenges SET attempts=attempts+1 WHERE token_hash=?',[hash]);
 let u;try{u=await transaction(async c=>{const [locked]=await rows(c,'SELECT * FROM auth_challenges WHERE token_hash=? FOR UPDATE',[hash]);if(locked.used_at)V.fail('Sign in again.',401);const method=await MFA.verify(c,row.user_id,d.code);await c.execute('UPDATE auth_challenges SET used_at=UTC_TIMESTAMP(3) WHERE token_hash=?',[hash]);if(method==='RECOVERY_CODE')await Audit.event(req,'RECOVERY_CODE_USED','SUCCESS',{},c,row.user_id);return R.one(c,'users',row.user_id);});}catch(e){await Audit.event(req,'MFA_FAILED','FAILURE',{},pool,row.user_id);throw e;}
 req.risk=await signals(req,u.id);if(req.risk.level==='CRITICAL')V.fail('Sign-in is temporarily restricted. Use assisted account recovery.',429);await completeLogin(req,res,u,true);return {user:portalUser(u)};
}
function portalUser(u){if(!u)return null;return {id:u.id,full_name:u.name,email:u.email,phone:u.phone,address:u.address,city:u.city||'',id_last4:u.id_last4||'',role:u.role.toUpperCase(),department_id:u.department_id,status:u.active?'ACTIVE':'INACTIVE',created_at:normalize(u).created_at};}
async function reauthenticate(req,c=pool){const u=await R.one(c,'users',req.user.id);if(!await P.verify(V.text(req.body.password,'Password',1,100),u.password_hash))V.fail('Reauthentication failed.',401);const [m]=await rows(c,'SELECT enabled FROM mfa_methods WHERE user_id=?',[u.id]);if(m?.enabled)await MFA.verify(c,u.id,req.body.code);await c.execute('UPDATE sessions SET reauthenticated_at=UTC_TIMESTAMP(3) WHERE token_hash=?',[S.digest(req.sessionToken)]);return u;}
function recent(req){if(!req.sessionRow?.reauthenticated_at||Date.now()-new Date(req.sessionRow.reauthenticated_at)>5*60000)V.fail('Confirm your password in Security before this sensitive action.',428);}
async function forgot(req){if(config.production)V.fail('A delivery provider must be configured before password recovery is available.',503);const email=V.email(req.body.email);const [u]=await rows(pool,'SELECT id FROM users WHERE email=? AND active=TRUE',[email]);if(u){const token=C.token();await pool.execute('INSERT INTO auth_challenges(token_hash,user_id,purpose,device_hash,expires_at) VALUES(?,?,?,?,?)',[C.hash(token),u.id,'PASSWORD_RESET',C.hash(req.deviceToken),new Date(Date.now()+20*60000)]);
 if(config.production) V.fail('A delivery provider must be configured before password recovery is available.',503);
 const dir=path.join(config.root,'.runtime','outbox');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,crypto.randomUUID()+'.json'),JSON.stringify({to:email,subject:'AMAP password recovery (local development only)',url:(process.env.FRONTEND_URL||req.get('Origin')||config.origin)+'/reset-password?token='+token,expires_minutes:20}),{mode:0o600});}
 return {message:'If the account can receive recovery instructions, they have been prepared. Development deliveries are captured locally; no external email is sent.'};}
async function reset(req){const token=C.hash(V.text(req.body.token,'Reset token',64,64)),encoded=await P.hash(V.password(req.body.password));return transaction(async c=>{const [r]=await rows(c,"SELECT * FROM auth_challenges WHERE token_hash=? AND purpose='PASSWORD_RESET' FOR UPDATE",[token]);if(!r||r.used_at||new Date(r.expires_at)<new Date())V.fail('This reset link is invalid or expired.',400);await c.execute('UPDATE users SET password_hash=? WHERE id=?',[encoded,r.user_id]);await c.execute('UPDATE auth_challenges SET used_at=UTC_TIMESTAMP(3) WHERE token_hash=?',[token]);await c.execute('DELETE FROM sessions WHERE user_id=?',[r.user_id]);await c.execute('UPDATE trusted_devices SET trusted=FALSE WHERE user_id=?',[r.user_id]);await Audit.event(req,'PASSWORD_RESET','SUCCESS',{},c,r.user_id);return {ok:true};});}
module.exports={login,challenge,completeLogin,portalUser,reauthenticate,recent,signals,forgot,reset};
