'use strict';
const express=require('express'),{pool,rows,transaction,normalize}=require('../db.cjs'),S=require('../security.cjs'),V=require('../validation.cjs'),Auth=require('./auth.cjs'),I=require('./service.cjs'),Audit=require('./audit.cjs');
function routes(){const api=express.Router(),citizen=S.allow('citizen'),limiter=S.rateLimit(90,15*60000),startLimit=S.rateLimit(12,60*60000);api.use(limiter);
 api.get('/health',(req,res)=>{const {installed,model}=require('./biometrics.cjs').health();res.json({installed,model,provider:'sandbox',uidai_connected:false});});
 api.get('/overview',citizen,async(req,res)=>{const [p]=await rows(pool,'SELECT masked_identity,status,last_verified_at,dob,provider FROM identity_profiles WHERE user_id=?',[req.user.id]),[f]=await rows(pool,'SELECT enrolled_at,model FROM face_templates WHERE user_id=?',[req.user.id]),[m]=await rows(pool,'SELECT enabled FROM mfa_methods WHERE user_id=?',[req.user.id]);res.json({profile:p?normalize(p):null,face_enrolled:!!f,enrolled_at:f?.enrolled_at,mfa_enabled:!!m?.enabled,policy_version:I.POLICY,provider:'sandbox'});});
 api.get('/history',citizen,async(req,res)=>res.json((await rows(pool,'SELECT id,kind,state,created_at,updated_at,liveness_passed,blink_count,face_passed,age_consistency FROM identity_verification_sessions WHERE user_id=? ORDER BY created_at DESC LIMIT 100',[req.user.id])).map(normalize)));
 api.get('/consents',citizen,async(req,res)=>res.json((await rows(pool,'SELECT id,type,policy_version,accepted_at,revoked_at FROM consent_records WHERE user_id=? ORDER BY accepted_at DESC LIMIT 100',[req.user.id])).map(normalize)));
 api.delete('/consents/face',citizen,async(req,res)=>{Auth.recent(req);await transaction(async c=>{await c.execute('DELETE FROM face_templates WHERE user_id=?',[req.user.id]);await c.execute("UPDATE consent_records SET revoked_at=UTC_TIMESTAMP(3) WHERE user_id=? AND type IN ('FACE_ENROLLMENT','FACE_VERIFICATION','AGE_CONSISTENCY') AND revoked_at IS NULL",[req.user.id]);await c.execute("UPDATE identity_verification_sessions SET state='CANCELLED',evidence_cipher=NULL WHERE user_id=? AND state NOT IN ('COMPLETED','FAILED','CANCELLED','BLOCKED','EXPIRED')",[req.user.id]);await Audit.event(req,'FACE_CONSENT_REVOKED','SUCCESS',{},c);});res.json({ok:true});});
 api.post('/sessions',startLimit,async(req,res)=>res.status(201).json(await I.start(req)));
 api.get('/sessions/:id',async(req,res)=>res.json(I.publicState(await I.get(req))));
 for(const [path,fn]of [['consent',I.consent],['camera',I.camera],['frames',I.capture],['challenge',I.refresh],['mfa',I.mfa],['send-code',I.sendAdditional],['additional',I.additional],['complete',I.complete]])api.post('/sessions/:id/'+path,async(req,res)=>res.json(await fn(req)));
 api.delete('/sessions/:id',async(req,res)=>{const s=await I.get(req);I.expect(s,'ACCOUNT_IDENTIFIED','CONSENT_ACCEPTED','CAMERA_STARTED','LIVENESS_PASSED','FACE_VERIFIED','MFA_REQUIRED','MFA_VERIFIED','ADDITIONAL_VERIFICATION_REQUIRED','VERIFIED');await pool.execute("UPDATE identity_verification_sessions SET state='CANCELLED',evidence_cipher=NULL WHERE id=?",[s.id]);res.json({ok:true});});
 return api;
}
module.exports={routes};
