import {createContext,useContext,useEffect,useState} from 'react';
import API from '../data/api.js';
// All 22 scheduled languages have stable locale IDs. Missing messages explicitly
// fall back to English; selecting a locale never pretends it is fully translated.
export const languages=[['en','English'],['as','অসমীয়া'],['bn','বাংলা'],['brx','बड़ो'],['doi','डोगरी'],['gu','ગુજરાતી'],['hi','हिन्दी'],['kn','ಕನ್ನಡ'],['ks','کٲشُر'],['kok','कोंकणी'],['mai','मैथिली'],['ml','മലയാളം'],['mni','মৈতৈলোন্'],['mr','मराठी'],['ne','नेपाली'],['or','ଓଡ଼ିଆ'],['pa','ਪੰਜਾਬੀ'],['sa','संस्कृतम्'],['sat','ᱥᱟᱱᱛᱟᱲᱤ'],['sd','سنڌي'],['ta','தமிழ்'],['te','తెలుగు'],['ur','اردو']];
const translations={hi:{'Sign in':'साइन इन करें','Email address':'ईमेल पता','Password':'पासवर्ड','Forgot password?':'पासवर्ड भूल गए?','Create a citizen account':'नागरिक खाता बनाएँ','Digital Identity':'डिजिटल पहचान','Security':'सुरक्षा','Cancel':'रद्द करें','Continue':'जारी रखें','Save':'सहेजें'},te:{'Sign in':'సైన్ ఇన్','Email address':'ఈమెయిల్ చిరునామా','Password':'పాస్‌వర్డ్','Forgot password?':'పాస్‌వర్డ్ మర్చిపోయారా?','Create a citizen account':'పౌర ఖాతా సృష్టించండి','Digital Identity':'డిజిటల్ గుర్తింపు','Security':'భద్రత','Cancel':'రద్దు చేయి','Continue':'కొనసాగించు','Save':'సేవ్ చేయి'}};
const Context=createContext({t:s=>s,language:'en'});
export function LanguageProvider({children}){const [language,setLanguage]=useState('en');useEffect(()=>{API.preferences.get('language').then(l=>{if(languages.some(([code])=>code===l))setLanguage(l);}).catch(()=>{});},[]);function change(code){setLanguage(code);API.preferences.set('language',code).catch(()=>{});}const t=s=>translations[language]?.[s]||s;return <Context.Provider value={{t,language,setLanguage:change}}>{children}</Context.Provider>;}
export const useLanguage=()=>useContext(Context);
export function LanguageSelect(){const {language,setLanguage}=useLanguage();return <div className="language-select"><label htmlFor="portal-language">Language</label><select id="portal-language" className="select" value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select>{language!=='en'&&<small role="status">English is used where reviewed translations are not yet available.</small>}</div>;}
