'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {setup,Client,report}=require('./live-support.cjs');
const {STATUSES}=require('../server/validation.cjs');
let checks=0,transitionCases=0;
function equal(actual,expected,message){assert.deepEqual(actual,expected,message);checks++;}
function ok(value,message){assert.ok(value,message);checks++;}
const remarks='The submitted evidence was reviewed carefully and the applicant has been informed of the next step.';
function payload(name='identity-proof.txt',content='Synthetic identity proof for the backend integration test.'){const bytes=Buffer.from(content);return {service_id:3,form_data:{full_name:'Aarav Sharma',email:'citizen@demo.gov',phone:'9810012345',address:'1 Lakeview Road, Hyderabad',purpose:'Requesting a birth certificate for college admission records.'},documents:[{name,label:'Identity proof',size:bytes.length,mime:'text/plain',content:'data:text/plain;base64,'+bytes.toString('base64')}]};}
(async()=>{
  const t=await setup();const clients=['guest','citizen','officer','admin'].map(()=>new Client(t.base));const [guest,citizen,officer,admin]=clients;
  const query=async(sql,params=[])=> (await t.owner.execute(sql,params))[0];
  const status=async(client,method,url,data,expected=200,extra)=>{const r=await client.request(method,url,data,extra);equal(r.status,expected,method+' '+url+': '+JSON.stringify(r.body));return r.body;};
  try{
    await status(guest,'GET','/api/auth/me',undefined,200);await status(guest,'GET','/api/preferences');await status(guest,'PATCH','/api/preferences',{theme:'dark'});equal((await status(guest,'GET','/api/preferences')).theme,'dark');
    equal((await status(guest,'GET','/api/departments')).length,8);equal((await status(guest,'GET','/api/services')).length,25);equal((await status(guest,'GET','/api/analytics/public')).applications,420);
    for(const endpoint of ['/applications','applications/1','users','grievances','notifications','analytics/dashboard','documents/1'])await status(guest,'GET','/api/'+endpoint.replace(/^\//,''),undefined,401);
    await status(guest,'POST','/api/auth/register',{...{name:'Escalated Person',email:'escalated@example.test',phone:'9876543210',address:'11 Safe Avenue',password:'Example123'},role:'admin'},400);
    await status(guest,'POST','/api/auth/login',{email:'admin@demo.gov',password:'wrong123',role:'admin'},401);
    for(const [role,client]of [['citizen',citizen],['officer',officer],['admin',admin]]){const signed=await client.login(role);equal(signed.body.role,role);ok(signed.headers.getSetCookie().some(v=>v.includes('amap-session=')&&v.includes('HttpOnly')&&v.includes('SameSite=Lax')),'Session cookie protections');ok(!JSON.stringify(signed.body).includes('password'),'No credential fields in auth response');}
    const rawToken=citizen.cookies.get('amap-session');const sessions=await query('SELECT token_hash FROM sessions');ok(sessions.every(s=>s.token_hash!==rawToken&&s.token_hash.length===64),'Only token hashes stored in MySQL');
    await status(citizen,'PATCH','/api/preferences',{theme:'light'},403,{headers:{'X-CSRF-Token':null}});
    await status(citizen,'PATCH','/api/preferences',{theme:'light'},403,{headers:{Origin:'https://untrusted.example'}});
    await status(citizen,'PATCH','/api/preferences',{theme:'light'},403,{headers:{'X-CSRF-Token':'a'.repeat(48)+'.'+'b'.repeat(64)}});
    await status(citizen,'POST','/api/departments',{},403);await status(officer,'POST','/api/users',{},403);await status(citizen,'PATCH','/api/users/1',{role:'admin'},400);await status(citizen,'PATCH','/api/users/3',{name:'Changed admin'},403);
    const all=await status(admin,'GET','/api/applications'),mine=await status(citizen,'GET','/api/applications'),department=await status(officer,'GET','/api/applications');equal(all.length,420);ok(mine.every(a=>a.citizen_id===1));ok(department.every(a=>a.department_id===1));ok(all.every(a=>typeof a.processingDays==='number'&&typeof a.isOverdue==='boolean'&&a.created_at.endsWith('Z')));
    const foreign=all.find(a=>a.citizen_id!==1&&a.department_id!==1);await status(citizen,'GET','/api/applications/'+foreign.id,undefined,403);await status(officer,'GET','/api/applications/'+foreign.id,undefined,403);const foreignDetail=await status(admin,'GET','/api/applications/'+foreign.id);await status(citizen,'GET','/api/documents/'+foreignDetail.documents[0].id,undefined,403);
    equal((await status(citizen,'GET','/api/applications?citizen_id='+foreign.citizen_id)).length,0);equal((await status(officer,'GET','/api/applications?department_id=2')).length,0);equal((await status(admin,'GET','/api/applications?search='+encodeURIComponent("' OR 1=1 --"))).length,0);
    const before=(await query('SELECT COUNT(*) n FROM applications'))[0].n;
    await status(citizen,'POST','/api/applications',{...payload(),documents:[]},400);
    const fake=payload();fake.documents[0].size=1;await status(citizen,'POST','/api/applications',fake,400);
    const binary=payload('identity-proof.pdf');binary.documents[0].mime='application/pdf';binary.documents[0].content=binary.documents[0].content.replace('text/plain','application/pdf');await status(citizen,'POST','/api/applications',binary,400);
    const pathFile=payload('../identity.txt');await status(citizen,'POST','/api/applications',pathFile,400);
    const large=payload('identity.txt','A'.repeat(1048577));await status(citizen,'POST','/api/applications',large,413);
    equal((await query('SELECT COUNT(*) n FROM applications'))[0].n,before,'Upload rejection rolls back the application and reference allocation');
    const a=await status(citizen,'POST','/api/applications',payload(),201);equal(a.status,'SUBMITTED');ok(/^GOV-\d{4}-\d{6}$/.test(a.reference));const detail=await status(citizen,'GET','/api/applications/'+a.id);equal(detail.logs.length,1);equal(detail.documents.length,1);const document=await status(citizen,'GET','/api/documents/'+detail.documents[0].id);equal(Buffer.from(document.content.split(',')[1],'base64').toString(), 'Synthetic identity proof for the backend integration test.');
    await status(citizen,'POST','/api/applications/'+a.id+'/transitions',{status:'APPROVED',remarks},409);await status(officer,'POST','/api/applications/'+a.id+'/transitions',{status:'UNDER_REVIEW',remarks:'yes'},400);
    await status(officer,'POST','/api/applications/assign',{ids:[a.id],officer_id:2});
    await status(officer,'POST','/api/applications/'+a.id+'/transitions',{status:'UNDER_REVIEW',remarks});
    await status(officer,'POST','/api/applications/'+a.id+'/transitions',{status:'NEEDS_INFO',remarks:'Please provide updated address evidence for verification.'});
    await status(officer,'POST','/api/applications/'+a.id+'/transitions',{status:'UNDER_REVIEW',remarks},403);
    await status(citizen,'POST','/api/applications/'+a.id+'/transitions',{status:'UNDER_REVIEW',remarks:'Aarav Sharma citizen@demo.gov 9810012345: here is the updated supporting record.',documents:payload().documents});
    const concurrent=await Promise.all(['APPROVED','REJECTED'].map(value=>officer.request('POST','/api/applications/'+a.id+'/transitions',{status:value,remarks})));
    equal(concurrent.map(r=>r.status).sort(),[200,409],'Only one concurrent final decision commits');
    const decided=await status(citizen,'GET','/api/applications/'+a.id);equal(decided.logs.length,6);equal((await query('SELECT COUNT(*) n FROM notifications WHERE application_id=?',[a.id]))[0].n,6);ok(decided.decided_at);equal(decided.isOverdue,false);
    const tracked=await status(guest,'GET','/api/track/'+a.reference);equal(tracked.applicant_name,'A••• S•••');for(const secret of ['Aarav Sharma','citizen@demo.gov','9810012345','Lakeview'])ok(!JSON.stringify(tracked).includes(secret),'Public tracking must not reveal '+secret);equal(tracked.form_data,undefined);equal(tracked.documents,undefined);
    const batch=await Promise.all([1,2,3].map(()=>citizen.request('POST','/api/applications',payload())));ok(batch.every(r=>r.status===201));equal(new Set(batch.map(r=>r.body.reference)).size,3,'Concurrent references are unique');const open=batch[0].body;
    await status(admin,'POST','/api/applications/assign',{ids:[open.id,a.id],officer_id:2},409);equal((await status(citizen,'GET','/api/applications/'+open.id)).officer_id,null,'Bulk reassignment is atomic');
    await status(officer,'POST','/api/applications/'+open.id+'/transitions',{status:'UNDER_REVIEW',remarks});await status(officer,'POST','/api/applications/'+open.id+'/transitions',{status:'FORWARDED',remarks,department_id:2,officer_id:6});await status(officer,'GET','/api/applications/'+open.id,undefined,403);
    const receiver=new Client(t.base);clients.push(receiver);await receiver.login('officer','officer20@demo.gov','officer123');await status(receiver,'POST','/api/applications/'+open.id+'/transitions',{status:'UNDER_REVIEW',remarks});await status(receiver,'POST','/api/applications/'+open.id+'/transitions',{status:'REJECTED',remarks});
    const withdrawal=batch[1].body;await status(officer,'POST','/api/applications/'+withdrawal.id+'/transitions',{status:'WITHDRAWN',remarks},403);await status(citizen,'POST','/api/applications/'+withdrawal.id+'/transitions',{status:'WITHDRAWN',remarks});
    const grievance=await status(citizen,'POST','/api/grievances',{application_id:a.id,subject:'Clarify the decision and certificate',description:'Please explain how to access the certificate after the application decision.'},201);
    await status(citizen,'PATCH','/api/grievances/'+grievance.id,{status:'IN_PROGRESS'},403);await status(receiver,'PATCH','/api/grievances/'+grievance.id,{status:'IN_PROGRESS'},403);await status(officer,'PATCH','/api/grievances/'+grievance.id,{status:'RESOLVED',resolution:remarks},409);await status(officer,'PATCH','/api/grievances/'+grievance.id,{status:'IN_PROGRESS'});await status(admin,'PATCH','/api/grievances/'+grievance.id,{status:'RESOLVED',resolution:remarks});const resolved=(await status(citizen,'GET','/api/grievances')).find(g=>g.id===grievance.id);equal(resolved.logs.map(l=>l.to_status),['OPEN','IN_PROGRESS','RESOLVED']);
    const notes=await status(citizen,'GET','/api/notifications');await status(citizen,'PATCH','/api/notifications/'+notes[0].id,{read:true});await status(citizen,'PATCH','/api/notifications/all',{read:true});ok((await status(citizen,'GET','/api/notifications')).every(n=>n.read));await status(officer,'PATCH','/api/notifications/'+notes[0].id,{read:true},403);
    const d=await status(admin,'POST','/api/departments',{name:'Integration Department',code:'INTEG',icon:'shield',description:'A temporary department for API integration verification.'},201);await status(admin,'PATCH','/api/departments/'+d.id,{name:'Integration Department Updated',code:'INTEG',icon:'building',description:'Updated department configuration for integration verification.'});
    const s=await status(admin,'POST','/api/services',{department_id:d.id,name:'Integration Permit',description:'A temporary permit with a required identity document.',fee:75,sla_days:12,required_documents:['Identity proof']},201);await status(admin,'PATCH','/api/services/'+s.id,{...{department_id:d.id,name:s.name,description:s.description,fee:100,sla_days:15,required_documents:s.required_documents}});
    const staff=await status(admin,'POST','/api/users',{name:'New Integration Officer',email:'new.officer@example.test',role:'officer',department_id:1,password:'OfficerNew123'},201);const newcomer=new Client(t.base);clients.push(newcomer);await newcomer.login('officer',staff.email,'OfficerNew123');await status(admin,'PATCH','/api/users/'+staff.id,{active:false});await status(newcomer,'GET','/api/applications',undefined,401);await status(admin,'PATCH','/api/users/'+staff.id,{active:true});await status(admin,'GET','/api/users?role=officer&department_id=1&active=true');await status(officer,'GET','/api/users?role=officer&department_id=2&active=true');
    await status(admin,'DELETE','/api/services/'+s.id);await status(admin,'DELETE','/api/departments/'+d.id);await status(admin,'DELETE','/api/services/3',undefined,409);await status(admin,'POST','/api/demo/reset',{},409);await status(citizen,'POST','/api/demo/reset',{},403);
    for(const part of ['dashboard','kpis','monthly','daily','status','departments','services','officers','sla','activity']){
      const data=await status(admin,'GET','/api/analytics/'+part+'?department_id=1&from=2026-01-01&to=2026-12-31');ok(data!==null,part);const personal=await status(citizen,'GET','/api/analytics/'+part);ok(personal!==null);
    }
    const analytics=await status(admin,'GET','/api/analytics/dashboard');equal(analytics.status.reduce((sum,s)=>sum+s.value,0),analytics.kpis.total);equal(analytics.sla.distribution.reduce((sum,s)=>sum+s.value,0),analytics.kpis.decided);equal(analytics.departments.reduce((sum,d)=>sum+d.total,0),analytics.kpis.total);
    await status(admin,'GET','/api/applications?from=2026-12-31&to=2026-01-01',undefined,400);
    const second=new Client(t.base);clients.push(second);await second.login('citizen');await status(citizen,'PATCH','/api/users/1',{name:'Aarav Sharma',phone:'9810012345',address:'1 Lakeview Road, Hyderabad'});await status(citizen,'POST','/api/auth/password',{current_password:'citizen123',new_password:'ChangedCitizen123'});await status(second,'GET','/api/applications',undefined,401);await status(citizen,'POST','/api/auth/password',{current_password:'ChangedCitizen123',new_password:'citizen123'});
    const registered=new Client(t.base);clients.push(registered);await status(registered,'GET','/api/auth/me');const reg=await status(registered,'POST','/api/auth/register',{name:'New API Citizen',email:'api.citizen@example.test',phone:'9876543210',address:'22 Testing Avenue',password:'CitizenNew123'},201);equal(reg.role,'citizen');equal((await status(registered,'GET','/api/applications')).length,0);const stolen=registered.cookies.get('amap-session');await status(registered,'POST','/api/auth/logout',{});registered.cookies.set('amap-session',stolen);await status(registered,'GET','/api/applications',undefined,401);
    // Exhaust every role × from-state × to-state combination over real HTTP.
    const allowed={citizen:{SUBMITTED:['WITHDRAWN'],UNDER_REVIEW:['WITHDRAWN'],NEEDS_INFO:['UNDER_REVIEW']},officer:{SUBMITTED:['UNDER_REVIEW'],UNDER_REVIEW:['APPROVED','REJECTED','NEEDS_INFO','FORWARDED'],FORWARDED:['UNDER_REVIEW']}};allowed.admin=allowed.officer;
    for(const [role,client]of [['citizen',citizen],['officer',officer],['admin',admin]])for(const from of STATUSES)for(const to of STATUSES){
      const id=550000+transitionCases++;await query('INSERT INTO applications(id,reference,citizen_id,service_id,department_id,officer_id,status,form_data,fee,sla_days,decided_at,last_actor_id,last_remarks) VALUES(?,?,1,3,1,2,?,JSON_OBJECT(),100,14,?,1,?)',[id,'GOV-2026-'+id,from,['APPROVED','REJECTED','WITHDRAWN'].includes(from)?new Date():null,remarks]);
      const response=await client.request('POST','/api/applications/'+id+'/transitions',{status:to,remarks,...(to==='FORWARDED'?{department_id:1,officer_id:2}:{})});equal(response.status===200,Boolean(allowed[role][from]?.includes(to)),role+': '+from+' -> '+to+' '+JSON.stringify(response.body));
    }
    for(const sql of ["UPDATE status_logs SET remarks='tampered' WHERE id=1",'DELETE FROM status_logs WHERE id=1',"INSERT INTO status_logs(application_id,actor_id,to_status,remarks) VALUES(1,1,'SUBMITTED','tampered')"]){await assert.rejects(t.pool.execute(sql),error=>error.code==='ER_TABLEACCESS_DENIED_ERROR');checks++;}
    for(const file of ['/.env','/server/config.cjs','/database/schema.sql','/node_modules/express/package.json','/.runtime/local-db.json']){const response=await fetch(t.base+file);equal(response.status,404,'Private file exposure: '+file);}
    const contracts=[...fs.readFileSync(path.join(__dirname,'../js/api.js'),'utf8').matchAll(/\/\/ (GET|POST|PATCH|DELETE) (\/api\/[^\s(]+)/g)].map(m=>m[1]+' '+m[2]);const covered=new Set(clients.flatMap(c=>[...c.coverage]));for(const contract of contracts){const pattern=new RegExp('^'+contract.replace(/:[a-z_]+/g,'[^/]+')+'$');ok([...covered].some(item=>pattern.test(item)),'Untested API contract: '+contract);}equal(contracts.length,42);
    report('live-api.json',{passed:true,checks,transitionCases,contracts:contracts.length,isolatedDatabase:true});console.log('PASS live API: '+checks+' checks, '+transitionCases+' state/role cases, all 42 endpoint contracts, security, concurrent writes, uploads, audit and SQL privileges.');
  }finally{await t.close();}
})().catch(error=>{report('live-api.json',{passed:false,checks,transitionCases,error:error.stack});console.error(error);process.exitCode=1;});
