import {useState} from 'react';
import API from '../../data/api.js';
import useApi from '../../hooks/useApi.js';
import Icon from '../../components/Icon.jsx';
import {ApiState,ButtonLink,Details,Modal} from '../../components/ui/index.jsx';
import {money} from '../../lib/format.js';
export default function Home(){
  const [service,setService]=useState(null);
  const state=useApi(async()=>{const [departments,services]=await Promise.all([API.departments.list(),API.services.list()]);return {departments,services};},[]);
  return <><section className="entry-hero"><div className="entry-container"><p className="eyebrow">Public services, a little simpler</p><h1>Apply once.<br/>Follow every step.</h1><p className="entry-purpose">AMAP helps citizens apply for public services and follow each request, from submission to decision.</p><div className="entry-actions"><ButtonLink to="/citizen/apply" icon="arrowRight">Apply for a service</ButtonLink><ButtonLink to="/track" variant="outline">Track an application</ButtonLink></div></div></section><section className="entry-catalogue entry-container" id="services"><div className="entry-section-head"><div><p className="eyebrow">Find the right department</p><h2>What do you need help with?</h2></div><p>Check the documents, fee and timeline<br className="desktop-only"/> before you begin.</p></div><ApiState state={state}>{state.data&&<div className="entry-service-grid">{state.data.departments.map((dep,i)=><article className="entry-department" key={dep.id}><div className="entry-department-title"><Icon name={dep.icon} size={23}/><h3>{dep.name}</h3><span className="department-number" aria-hidden="true">{String(i+1).padStart(2,'0')}</span></div><ul>{state.data.services.filter(s=>s.department_id===dep.id&&s.is_active).map(s=><li key={s.id}><button onClick={()=>setService(s)}><span>{s.name}</span><Icon name="arrowUpRight" size={15}/></button></li>)}</ul>{!state.data.services.some(s=>s.department_id===dep.id&&s.is_active)&&<p className="muted text-sm">No services accepting applications yet.</p>}</article>)}</div>}</ApiState></section><section className="entry-how entry-container"><h2>A clear path from here.</h2><ol>{[['Create your account','Register once with your basic details.'],['Send your application','Choose a service and attach your documents.'],['Follow the review','See updates and respond if more details are needed.'],['Get your decision','Read the outcome and save your acknowledgment.']].map(([title,text],i)=><li key={title}><span className="step-index">{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>{service&&<Modal title={service.name} onClose={()=>setService(null)} actions={<ButtonLink to={'/citizen/apply?service='+service.id}>Apply for this service</ButtonLink>}><p className="muted mb-5">{service.description}</p><Details items={[["Department",state.data.departments.find(d=>d.id===service.department_id)?.name],["Demo fee",money(service.fee)],["Published timeline",service.sla_days+' days']]}/><h3 className="mt-5 mb-3">Documents to keep ready</h3><ul className="document-checklist">{service.docs.map(doc=><li key={doc}>{doc}</li>)}</ul><p className="hint mt-5">This is an academic demonstration. No payment is collected and no official document is issued.</p></Modal>}</>;
}
